- framework/encode/trace_manager.cpp
- framework/util/logging.h
- framework/util/platform.h
- tools/compress/main.cpp
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/toascii/main.cpp
* Set default log level to info
* Add null checks to platform wrapper functions that dereference pointers
* FileOpen returns 0 on success instead of errno
* Convert some memcpy calls to assignments
> Utility Code Cleanup

- framework/encode/trace_manager.cpp
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Remove the page guard option for disabling shadow memory and watching mapped memory directly. Testing of this option indicates that attempting to watch any memory type returned by vkMapMemory with VirtualProtect() or mprotect() results in undefined behavior.
The option was originally implemented for testing with HOST_CACHED memory types.
> Remove "no shadow" Page Guard Option

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- layer/trace_layer.cpp
When layer initialization fails, the layer will skip the call to the next vkCreateInstance function in its call chain and return VK_ERROR_INITIALIZATION_FAILED.
- Moves layer initialization from a custom pre-call command to the layer's dispatch_CreateInstance function.
- Adds a CreateInstance post-call command to check the result of the vkCreateInstance call and handle failure.
> Fail vkCreateInstance When Layer Initialization Fails

- framework/util/CMakeLists.txt
- framework/util/date_time.h
Updates to the timestamp generation code for Linux/Android.
- Use CLOCK_MONOTONIC_RAW or CLOCK_MONOTONIC instead of CLOCK_REALTIME with clock_gettime() when available.
- Update CMake to check for presence of clock_gettime in librt and add librt link target if necessary.
> Linux Timestamp Update

- CMakeLists.txt
- framework/util/compressor.h
- framework/util/page_guard_manager.h
- framework/util/page_status_tracker.h
Minor changes to address build errors with gcc 5.4.0 on Ubuntu 16.04
systems:
- Add <stddef> includes for size_t
- Set CMAKE_CXX_STANDARD to ensure appropriate C++ version is enabled
> Fix gcc 5.4 compilation errors

- framework/format/format_util.cpp
- tools/compress/main.cpp
When output resulted in a compression, we were not using the correct
GFXRECON_WRITE_CONSOLE macro to output the message.  We were using
a standard printf.  This resulted in no carraige return being
added.
Also, I noticed that both compress/main.cpp and format/format_util.cpp
had the same error message which caused me some confusing when
investigating it.  So I added more details to the format_util.cpp
error message.
> compress: Fix print and log statements

- framework/decode/vulkan_decoder_base.h
- framework/format/api_call_id.h
The range of supported API call IDs was not updated with the last header
update, and any API calls introduced with that update are not being
decoded during replay.  This is causing replay issues with titles that
use transform feedback.
This change adds a sentinel value to the end of the API call ID list,
which is now referened by the decoder in place of the specific API call
ID for the last item in the list.
> Fix Vulkan Decoder API Range

- layer/trace_layer.cpp
Add the VKAPI_ATTR/AKAPI_CALL decorations to the layer's
dispatch_CreateDevice and dispatch_CreateInstance function definitions,
to match the function declarations.  The mismatch was causing the 32-bit
Windows builds to fail.
> Use stdcall for Layer Create Funcs

- framework/generated/generated_layer_func_table.h
- framework/generated/vulkan_generators/layer_func_table_generator.py
- layer/trace_layer.cpp
Remove the layer's vk_layerGetPhysicalDeviceProcAddr function.
This is an optional function from the layer loader interface, which
the layer does not use directly. All calls to this function result
in the layer calling down the chain, which is not working correctly
with some versions of the loader. Because the function is optional,
it has been removed to work around the existing issue.
> Remove GetPhysicalDeviceProcAddr Layer Function

- framework/decode/vulkan_replay_consumer_base.cpp
- tools/replay/desktop_main.cpp
Updates to replay error handling:
- Stop replay if an API call that succeeded on capture fails on replay.
- Remove warning messages for API calls that failed during capture.
These are typically out of memory errors from descriptor allocations
or out of date errors from window resize, which were handled by the
captured application.
> Stop Replay on Error

- framework/format/api_call_id.h
- framework/format/platform_types.h
- framework/generated/generated_decode_pnext_struct.cpp
- framework/generated/generated_encode_pnext_struct.cpp
- framework/generated/generated_layer_func_table.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_api_call_encoders.h
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/generated_vulkan_ascii_consumer.h
- framework/generated/generated_vulkan_consumer.h
- framework/generated/generated_vulkan_decoder.cpp
- framework/generated/generated_vulkan_decoder.h
- framework/generated/generated_vulkan_dispatch_table.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_replay_consumer.h
- framework/generated/generated_vulkan_struct_decoders.cpp
- framework/generated/generated_vulkan_struct_decoders.h
- framework/generated/generated_vulkan_struct_decoders_forward.h
- framework/generated/generated_vulkan_struct_encoders.cpp
- framework/generated/generated_vulkan_struct_encoders.h
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.h
- framework/generated/vulkan_generators/platform_types.json
- framework/generated/vulkan_generators/vulkan_dispatch_table_generator.py
- Update volk and Vulkan-Headers submodules
- Add API Call IDs for:
* vkGetPhysicalDeviceCooperativeMatrixPropertiesNV
* vkGetImageViewHandleNVX
* vkCreateMetalSurfaceEXT
- Add PLATFORM_METAL_EXT declarations to platform_types.h
- Add CAMetalSurface* entry to platform_types.json, to instruct the
code generators to treat this type as void*
- Add a uint32_t entry to the dispatch table generator's default return
value table, which defines the value that should be returned by the
generated no-op functions that return this type
(vkGetImageViewHandleNVX is the first Vulkan API call to return this
type)
- Generate code from the 1.1.102 version of vk.xml
> Update for header 1.1.102

- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.h
- framework/generated/vulkan_generators/base_generator.py
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_header_generator.py
Code generation for mapping handles in structs was using the following
criteria to determine if a struct contained handles:
- A struct member has a handle type
- A struct member is a struct that has a member with a handle type
- The struct contains a pNext member
Structs with pNext members were processed for handle mapping even if
the valid extension structs did not contain handles. This was due to
code generator not having information for the valid extension structs
at the time that the parent struct was processed.
This change adds support for retrieiving extension struct information
from the registry when processing the parent struct, changing the pNext
criteria to:
- The struct contains a pNext member that can point to a structure that
has a member with a handle type.
> Refine Handle Processing for pNext Extensions Structs

- framework/decode/vulkan_replay_consumer_base.cpp
If VkSurface creation fails on replay, destroy the window that was created for that surface.
> Destroy Window if Surface Creation Fails

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
Add support for tracking buffer resource memory state and writing buffer memory content to the trimming state snapshot that is written before the trimmed frames.  Writing buffer memory to the state snapshot requires staging copies for device local memory.
> Add Buffer Memory to Trim Snapshot

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Add support for tracking image memory state and writing image memory content to the trimming state snapshot, which is written before the trimmed frames. Writing image memory to the state snapshot requires staging copies for device local memory.
> Add Image Memory to State Snapshot

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
Parameters for all commands recorded to a command buffer are tracked until the command buffer is reset. Each command buffer's tracked calls are written to the state snapshot for replay after the command buffer is created.
> Add Command Buffer Tracking for Trimming Snapshot

- android/tools/replay/src/main/res/values/styles.xml
Change the app theme for the Android replay application from
Theme.NoTitleBar.OverlayActionModes to Theme.NoTitleBar.Fullscreen. The
"OverlayActionModes" style renders some UI overlay components that
impact replay performance.
> Use Fullscreen Theme for Android Replay Tool

- android/framework/encode/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/custom_encoder_commands.h
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/descriptor_update_template_info.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
Initial support for tracking descriptor updates, which are written to the trimming state snapshot for all active descriptor sets.  Does not currently support push descriptor updates.
> Add Descriptor Update Tracking for Trimming Snapshot

- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
* Track swapchain image with swapchain wrapper.
* Write window resize commands to state snapshot prior to writing swapchain creation packet.
> Additional Swapchain Tracking for Trimming State Snapshot

- framework/encode/CMakeLists.txt
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Track results from the following VkPhsyicalDevice and VkSurfaceKHR property query calls, which will be written to the state snapshot after physical device/surface creation. The calls are only written to the state snapshot if they were previously made by the application being captured.
* vkGetPhysicalDeviceQueueFamilyProperties2
* vkGetPhysicalDeviceQueueFamilyProperties2KHR
* vkGetPhysicalDeviceSurfaceSupportKHR
* vkGetPhysicalDeviceSurfaceCapabilitiesKHR
* vkGetPhysicalDeviceSurfaceFormatsKHR
* vkGetPhysicalDeviceSurfacePresentModesKHR
Adding these calls to the trimming state snapshot removes validation errors generated by vkCreateDevice and VkSwapchainKHR related calls, which expect the queries to be made.
> Add 'Get Property' API Call Tracking for Trimming State Snapshot

- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Update the trimming state tracker to track swapchain image acquire and present info, including a Boolean value to indicate that the image is currently acquired, handles for the fence and/or semaphore specified at image acquire, the handle to the queue that the image was last presented on, and the index of the last presented image.
When writing the state snapshot, swapchain images are processed with two passes. The first pass acquires each image, transitions it to the present source layout, and submits it to release it.  The second pass acquires all images up to the last presented image, in order to increase chance that the first image acquired on replay is the same image acquired by the first captured frame.  Images that are not currently acquired are released with present, while images …
> Add Swapchain Image Acquired/Submitted State Tracking for Trimming

- framework/encode/trace_manager.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
* When writing descriptor updates to the trimming state snapshot, omit descriptor update writes that refer to Vulkan objects that no longer exist (descriptor sets may outlive objects that they reference).
* Change the data structure used for live object tracking from std::unordered_map to std::map, so that objects can be processed in order of creation when writing the trimming state snapshot (currently requires VK_LAYER_GOOGLE_unique_objects to ensure that handle values are sequence numbers).
* Fix offset specified for staging buffer copy when writing buffer memory content to the trimming state snapshot.
* When processing Vulkan object destroy calls for state tracking, ignore handles with the VK_NULL_HANDLE value.
> Misc Fixes for Trimming State Track/Write

- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/util/file_path.cpp
- framework/util/file_path.h
- framework/util/settings_loader.cpp
- framework/util/settings_loader.h
Add new settings to enable trimming by specifying one or more file ranges to capture.  Settings are:
- Desktop environment variable: GFXRECON_CAPTURE_FRAMES
- Android property: debug.gfxrecon.capture_frames
- vk_layer_settings.txt: lunarg_gfxrecon.capture_frames
Valid values for the setting consist of a string of comma separated list of frame ranges.  Frame ranges are specified for a single frame with a single number or a range of frames with two numbers separated by a '-' character specifying the first and last frame to capture.  For example, the string "20,31-35" captures frame 20 and frames 31, 32, 33, 34, and 35.  Each range is written to a separate file, where the file name includes the frame range (e.g. gfxrecon_capture_frame_20.gfxr).
> Add Trimming Setting

- android/framework/encode/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_command_buffer_util.cpp
- framework/generated/generated_vulkan_command_buffer_util.h
- framework/generated/vulkan_generators/codegen.pyproj
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
- framework/generated/vulkan_generators/vulkan_command_buffer_util_body_generator.py
- framework/generated/vulkan_generators/vulkan_command_buffer_util_header_generator.py
Track values for handles recorded to a command buffer. When writing the state snapshot, if a handle that was recorded to a command buffer has been destroyed, omit the packets for the the tracked commands that were recorded to the command buffer from the snapshot. This fixes a case where handles referenced by a previously executed command buffer have been destroyed, but the command buffer has not been reset prior to start of the trimmed frame.
Handle tracking is currently incomplete, with the code generator not handling some cases (handle within a struct within a struct). To be completed in a future change.
> Additional Command Buffer State Tracking for Trimming

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Track active/available state for queries and write begin/end calls to the trimming state snapshot for available queries.  Calls to vkGetQueryPoolResults made by the trimmed frame for these queries will succeed, but the query results will not be valid.  This prevents replay of the trimmed frame from waiting indefinitely for vkGetQueryPoolResults to return VK_SUCCESS.
> Add Query Tracking for Trimming State Snapshot

- framework/encode/vulkan_state_table.h
- framework/encode/vulkan_state_writer.cpp
The trimming state tracker will keep track of acquired swapchain images and the handles for the semaphore/fence objects specified when acquiring them.  Calls to vkAcquireNextImageKHR will be written to the trimming state snapshot for each image in the acquired state, with the semaphore/fence originally used to acquire them.  This change handles a case where the semaphore/fence associated with an acquired image was destroyed before the state snapshot was written.  This can happen when an application creates a new semaphore/fence before calling vkAcquireNextImageKHR and then destroys the object prior to calling vkQueuePresentKHR.
> Fix Swapchain Image State Snapshot for Trimming

- framework/encode/capture_settings.cpp
- framework/encode/trace_manager.cpp
- layer/USAGE_android.md
- layer/USAGE_desktop.md
Complete the implementation of the capture option to flush the output stream after each packet is written to the capture file:
- Move API call flush within file lock scope.
- Add flush after meta-data write.
- Document new setting.
> Finish Capture File Flush Option

- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
Replay will treat an incomplete block at the end of a file as a warning instead of an error, printing a warning message along with the timing/FPS information that is normally printed for successful replay.
> Warn on Incomplete Block at End of File

- framework/encode/custom_encoder_commands.h
- framework/format/api_call_id.h
- framework/format/platform_types.h
- framework/generated/generated_decode_pnext_struct.cpp
- framework/generated/generated_encode_pnext_struct.cpp
- framework/generated/generated_layer_func_table.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_api_call_encoders.h
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/generated_vulkan_ascii_consumer.h
- framework/generated/generated_vulkan_consumer.h
- framework/generated/generated_vulkan_decoder.cpp
- framework/generated/generated_vulkan_decoder.h
- framework/generated/generated_vulkan_dispatch_table.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_replay_consumer.h
- framework/generated/generated_vulkan_struct_decoders.cpp
- framework/generated/generated_vulkan_struct_decoders.h
- framework/generated/generated_vulkan_struct_decoders_forward.h
- framework/generated/generated_vulkan_struct_encoders.cpp
- framework/generated/generated_vulkan_struct_encoders.h
- framework/generated/vulkan_generators/base_generator.py
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/platform_types.json
- Update VUlkan-Headers submodule
- Add API Call IDs for:
* ApiCall_vkCreateStreamDescriptorSurfaceGGP
* ApiCall_vkSetLocalDimmingAMD
* ApiCall_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV
* ApiCall_vkGetPhysicalDeviceSurfacePresentModes2EXT
* ApiCall_vkAcquireFullScreenExclusiveModeEXT
* ApiCall_vkReleaseFullScreenExclusiveModeEXT
* ApiCall_vkGetDeviceGroupSurfacePresentModes2EXT
* ApiCall_vkCreateHeadlessSurfaceEXT
* ApiCall_vkResetQueryPoolEXT
- Add PLATFORM_GGP declarations to platform_types.h
- Add VK_EXT_full_screen_exclusive declarations to platform_types.h (WIN32 specific extension)
- Add GgpStreamDescriptor and GgpFrameToken to platform_types.json
- Add HMONITOR to platform_types.json
- Generate code from the 1.1.108 version of vk.xml
> Update to Vulkan 1.1.108

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- tools/replay/replay_settings.h
Add an option to gfxrecon-replay to specify the physical device to use for replay, `--gpu <index>`, where `index` is the zero-based index to the array of physical devices returned by vkEnumeratePhysicalDevices.
The new replay device must be compatible with the capture device for successful replay.   Replay will currently fail if the devices do not have compatible memory heaps/types, or if the replay device does not support the device features and extensions that were enabled during capture.
Addresses #247
> Add Option to Select Replay Device

- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
When writing the trimming state snapshot, splits the buffer/image initialization into separate passes for buffer/image creation and memory bind/upload. Memory allocation had been performed for the trimming state snapshot before buffer/image initialization, which consisted of buffer/image creation, memory binding, and memory content upload. The buffer/image initialization needed to be split into separate passes for buffer/image creation and memory bind/upload to allow memory allocation to be performed after buffer/image creation for cases where valid buffer/image handles are required by memory allocation extensions such as dedicated allocation.
> Separate Passes for Trimming Resource Create/Bind

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/swapchain_image_tracker.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_object_mapper.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/format/format.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
When initializing API state for replay of a trimmed frame, pre-acquire
all swapchain images and transition them to the layout specified in the
state snapshot. Changes the existing swapchain image setup behavior from
a pattern that acquires, transitions, and presents images to a pattern
of acquire, transition, and store the image until first use. This avoids
multiple queue present operations at state setup, which would lead to
the screenshot layer generating invalid image files.
Includes the following:
- Adds a new packet type to describe swapchain image state. This
replaces Vulkan calls to acquire and transition swapchain images in
the state snapshot.
- Modifies capture and replay to use the new packet for swapchain image
state initialization.
- Modifies semaphore state snapshot data such …
> Swapchain image pre-acquire for trim state setup

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/trace_manager.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
Write markers to the capture file before and after the trimming state
snapshot data. Markers are used at replay to distinguish between API
calls that are part of the state setup for the first frame to be rendered
and API calls that are part of frame rendering process. The marker data
includes the number of the first frame from the trim range associated
with the state snapshot.
> Add markers for trim state snapshot begin/end

- framework/application/xcb_window.cpp
Add a 0.05 second delay after resizing an XCB window with xcb_configure_window() and waiting for the XCB_CONFIGURE_NOTIFY event generated for the associated cookie, to prevent a swapchain creation failure observed with some window managers. This should serve as a workaround for the problem until a better solution can be found.
> Workaround XCB window resize issue

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_state_writer.cpp
- framework/format/format.h
When initializing swapchain image state for replay of a trimmed file, handle the case where it is not possible to acquire all swapchain images at the same time.
> Update Swapchain Image Init for Trim Replay

- android/tools/replay/build.gradle
Add the capture layer to the replay tool's APK to use for trimming
files during replay.
> Add Capture Layer to Replay APK

- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
When reading buffer and image resource data for the trimming state
snapshot, call vkInvalidateMappedMemoryRanges after calling
vkMapeMemory when the memory type does not support the HOST_COHERENT
property.
> Invalidate Non-Coherent Memory After Map

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_writer.cpp
Miscellaneous fixes for trim state write at capture and initialization at replay:
* Fix potential null pointer dereference during resource snapshot, if the application had not previously called vkGetPhysicalDeviceMemoryProperties().
* Skip image layout transitions when processing images with the UNDEFINED or PREINITIALIZED layouts.
* Cleanup value initialization for swapchain image state tracking and state snapshot write.
* Treat a return value of VK_SUBOPTIMAL_KHR as success for tracking swapchain image acquired state.
> Trimming State Tracking/Initialization Fixes

- layer/USAGE_android.md
- layer/USAGE_desktop.md
Add documentation for the GFXRECON_CAPTURE_FRAMES environment variable and debug.gfxrecon.capture_frames Android system property.
> Add Documentation for Trimming Environment Variable

- framework/generated/vulkan_generators/gencode.py
Change time.clock() to time.process_time() to address the following
deprecation warning:
DeprecationWarning: time.clock has been deprecated in Python 3.3 and
will be removed from Python 3.8: use time.perf_counter or
time.process_time instead
> Fix Python 3.7 Warning

- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
- Enusre that DestoryWrappedHandles() is called by the capture layer when handles are destroyed/freed.
- Remove VkPhysicalDevice, and associated VkDisplayKHR and VkDisplayModeKHR, objects from the trimming state tracker when their parent VkInstance object is destroyed.
- Destory VkDisplayKHR and VkDisplayModeKHR handle wrappers associated with a VkPhysicalDevice wrapper when the VkPhysicalDevice wrapper is destroyed.
> Fix handle wrapper memory leak

- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/capture_overrides.json
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
- layer/trace_layer.cpp
Updates for the "page guard" memory tracking mode:
* Remove unused experimental and debug options
* Add an experimental option using VK_EXT_external_memory_host to eliminate the need for shadow memory to detect write access to mapped memory.  The current implementation only works reliably on Windows with AMD GPUs.
* Add settings file/environment variable options for controlling page guard behavior:
- GFXRECON_PAGE_GUARD_COPY_ON_MAP to enable/disable copy from mapped
memory to shadow memory after map.
- GFXRECON_PAGE_GUARD_LAZY_COPY to change the copy on map behavior
such that the copy is performed for individual pages on first access.
- GFXRECON_PAGE_GUARD_EXTERNAL_MEMORY to enable the experimental
feature that eliminates the need for shadow allocations.
Closes #205
> Mapped Memory Tracking Updates

- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Adds trimming state tracking for the following:
* Track IDs for image views specified for framebuffer creation and omit  framebuffers from the trimming state snapshot if any of their associated image views have been destroyed.
* Track IDs for buffers used for buffer view creation and omit buffer views from the trimming state snapshot if their associated buffer has been destroyed.
* Track IDs for images used for image view creation and omit image views from the trimming state snapshot if their associated image has been destroyed.
> Additional Resource Dependency Tracking

- framework/encode/trace_manager.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
The trimming state tracker was treating the semaphore parameter of vkAcquireNextImageKHR/vkAckquireNextImage2KHR as a VkSemaphore array of size 1, and was not correctly handle the case where the value of semaphore was VK_NULL_HANDLE.
> Fix Image Acquire Semaphore Tracking

- CMakeLists.txt
- android/framework/cmake-config/PlatformConfig.cmake
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Adds the following to the Android and Desktop Linux "page guard" implementation:
* The page guard signal handler for ARM will now check the WnR bit of the ESR register value provided through the signal handler's ucontext parameter to determine if the SIGSEGV signal was generated by a read or a write.  Makes the Android page guard behavior equivalent to the Desktop behavior.
* The Linux and Android signal handlers will now call abort(), instead of hanging, when receiving a SIGSEGV signal that was not generated by a read or write access to memory that the page guard implementation has protected with mprotect().
> PageGuard Improvements for Android/Linux

- framework/encode/trace_manager.cpp
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Update the capture layer to handle the case where the same VkDeviceMemory object is mapped more than once. In its vkMapMemory implementation, when the page guard memory tracking mode is enabled, the layer was correctly skipping the page guard initialization for the second vkMapMemory call, but was returning the real pointer returned by vkMapMemory instead of the pointer to the shadow memory allocation used for detecting memory modifications. As a result, no data written to mapped memory was recorded to the capture file. The layer now returns the pointer to the shadow allocation from the duplicate vkMapMemory call.
This case had been handled correctly before the trimming feature was implemented, but was lost with the changes for the trimming state tracking.
> Fix Capture Issue with Duplicate vkMapMemory Calls

- framework/encode/trace_manager.cpp
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
* When writing resource data to the trimming state snapshot, omit data from uninitialized images.
* When writing object initialization commands to the trimming state snapshot, handle the case where a VkMemory object has been destroyed, but VkImage and VkBuffer objects bound to that memory object have not been destroyed.
* When tracking mapped memory, ignore calls to vkFreeMemory with a null handle.
> Fixes for Trimming Memory/Resource Handling

- framework/encode/vulkan_state_writer.cpp
When writing a window resize command to the trimming state snapshot, a pointer to a SurfaceWrapper struct was incorrectly treated as a wrapped VkSurfaceKHR handle and was being unwrapped. The type casting performed for unwrapping produced a valid result with 64-bit builds where the size of a pointer matches the size of a Vulkan handle, but produced an invalid result with 32-bit address sizes.
> Fix Surface Handle Unwrap Issue

- framework/encode/trace_manager.h
- framework/encode/vulkan_state_tracker.h
Fix trimming state tracking issue with handles retrieved through vkEnumeratePhysicalDeviceGroups:
- Remove explicit template argument specification from AddStructGroupEntry invocation to allow for non-template function overloads.
- Refactor AddStructGroupEntry to avoid attempting to acquire the same lock twice.
> Fix Physical Device Group Handle Tracking

- framework/encode/trace_manager.cpp
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
When capturing with GFXRECON_PAGE_GUARD_EXTERNAL_MEMORY=1 on Windows, use the Win32 GetWriteWatch() function to obtain a list of modified pages.  Replaces use of VirtualProtect() to generate exceptions on page write to detect modifications to mapped memory.
> Detect Modified Pages with GetWriteWatch

- framework/decode/compression_converter.cpp
- framework/decode/compression_converter.h
Update gfxrecon-compress to support the meta-data blocks added for trimmed files.
> Add Trimmed File Support to gfxrecon-compress

- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/encode/trace_manager.cpp
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Add an option to enable/disable page guard support for tracking read and write memory accesses separately. When enabled, the accessed page will be copied from the mapped memory to shadow memory on every read. The option is enabled by default.
> Add Page Guard Option for Separate Read/Write Tracking

- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Reset query pools after creation during state setup for trimmed file replay.
> Reset Query Pool After Creation at Trim State Setup

- framework/util/argument_parser.cpp
Change-Id: Idc0ef10d0903be333518fc4579b100228183bae7
> arg parsing: Fix crash when arg has long string for value

- framework/decode/vulkan_replay_consumer_base.cpp
Make sure that the replay override for vkCreateDebugReportCallbackEXT uses the modified VkDebuReportCallbackDreateInfoEXT struct that references the replay tool's debug callback function.
> Fix debug report callback override

- framework/generated/.clang-format
This should allow running `git clang-format` without it modifying the generated files.  .clang-format file copied from KhronosGroup/Vulkan-ValidationLayers which has a similar need.
> Tell clang-format to ignore generated directory

- framework/decode/struct_pointer_decoder_nvx.h
- framework/util/argument_parser.cpp
- framework/util/file_path.cpp
- framework/util/file_path.h
- framework/util/logging.cpp
- framework/util/logging.h
- framework/util/memory_output_stream.cpp
- framework/util/memory_output_stream.h
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
- framework/util/settings_loader.cpp
Fixes for simple issues reported by clang-tidy for the util library code on Linux, with some additional cleanup.
> Fixes for clang-tidy issues from util code

- CMakeLists.txt
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_initializer.cpp
- framework/encode/vulkan_handle_wrapper_util.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/base_generator.py
- framework/util/settings_loader.cpp
* Fix warnings generated for size_t comparison/conversion.
* Fix std::transform warning generated by VS2015.
* Enable warnings as errors.
> Fix compiler warnings

- framework/application/xcb_window.cpp
Change comparison operation for sequence numbers returned by Xcb requests and sequence numbers received with events from == to >=, so that we handle cases where we never receive an event with a sequence number that is equal to the one generated by the request, but do receive an event with a sequence number that is greater than the one generated by the request.
> Update Xcb Event Wait

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_state_tracker.cpp
- For replay, change log level for VK_INCOMPLETE return values from Debug to Warning.
- For capture, add assertion checks for index values used with the vector of swapchain image info structs maintained by the trimming state tracker. When vkGetSwapchainImagesKHR returns VK_INCOMPLETE, the index can be outside of the expected range. Primarily intended to detect the case where trimming a replay will fail when the image count read from the capture file is smaller than the image count generated for replay.
> Warn for VK_INCOMPLETE on replay

- framework/application/win32_application.cpp
Modify the event handling for the Windows replay tool to handle the F10
syskey and disable the default F10 system behavior that activates the
replay window's menu bar and puts replay into some sort of idle state
until the F10 key is pressed a second time or the user interacts with
the window.
> Override default F10 key behavior on Windows

- framework/util/lz4_compressor.cpp
- framework/util/zlib_compressor.cpp
* Use LZ4_compress_fast() and LZ4_decompress_safe() instead of LZ4_compress_fast_continue() and LZ4_decompress_safe_continue() when compressing/decompressing capture packets.
* Remove try-catch statements with empty catch blocks from compression code.
> Use Non-streaming LZ4 Functions

- framework/application/android_window.cpp
- framework/application/android_window.h
- framework/application/wayland_window.cpp
- framework/application/wayland_window.h
- framework/application/win32_window.cpp
- framework/application/win32_window.h
- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/window.h
Set VkFullScreenExclusiveWin32InfoEXT::hmonitor to a valid value when replaying a capture on the WIN32 platform.
> Add Replay Support for the FullScreen Exclusive WIN32 Extension

- framework/generated/generated_vulkan_command_buffer_util.cpp
- framework/generated/vulkan_generators/vulkan_command_buffer_util_body_generator.py
Address compile and clang-tidy warnings generated by AndroidStudio for generated_vulkan_command_buffer_util.cpp:
- Ensure nested for loop counters have unique names.
- Add a default case to switch statements.
> Fix Command Buffer State Tracking Warnings

- BUILD.md
- android/framework/encode/CMakeLists.txt
- android/layer/CMakeLists.txt
- android/layer/build.gradle
- android/tools/replay/build.gradle
- framework/decode/api_decoder.h
- framework/decode/custom_vulkan_struct_decoders.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
* For capture, add support for recording description info and content for AHardwareBuffer objects referenced by VkImportAndroidHardwareBufferInfoANDROID.
* For replay, add support for creating and writing data to AHardwareBuffer objects referenced by VkImportAndroidHardwareBufferInfoANDROID.
> Add Capture/Replay Support for AHardwareBuffer

- framework/encode/capture_settings.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Removes the data structure and lock used to track persistent shadow memory allocations.  These allocations are now stored in the VkDeviceMemory handle wrapper.
> Remove Persistent Shadow Memory Table

- framework/decode/vulkan_consumer_base.h
- framework/generated/generated_vulkan_consumer.h
- framework/generated/vulkan_generators/vulkan_consumer_header_generator.py
- tools/CMakeLists.txt
- tools/info/CMakeLists.txt
- tools/info/main.cpp
Adds a new command line utility to print statistics for a capture file, including:
- Total frame count
- Application info
- Physical device info
- Total number of memory allocations, with min and max sizes.
- Total number of created pipelines
Fixes #329
> Add a gfxrecon-info command line utility

- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.h
Add support to the trimming state tracker for tracking buffer and image memory bindings performed with the following:
- vkBindBufferMemory2
- vkBindBufferMemory2KHR
- vkBindImageMemory2
- vkBindImageMemory2KHR
Does not currently track extensions structures provided to these calls. #273 will be updated to track the current state of trimming support for the BindMemory2 calls.
> Add Trimming Support for vkBindBufferMemory2 and vkBindImageMemory2

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
- tools/replay/replay_settings.h
This creates a command line option --replace-shaders <dir> which replaces the shader code in a CreateShaderModule call with the contents of the file <dir>/sh<hash> if present, where <hash> is the xor sum of the original shader contents.
This feature is designed to work along with a shader extraction feature which creates a baseline shader set for a trace.
> Shader replace feature

- cmake/FindWAYLAND.cmake
- framework/application/CMakeLists.txt
- framework/application/wayland_application.cpp
- framework/application/wayland_application.h
- framework/application/wayland_window.cpp
- framework/application/xcb_application.cpp
- framework/application/xcb_application.h
- framework/application/xcb_window.cpp
- framework/util/CMakeLists.txt
- framework/util/wayland_loader.cpp
- framework/util/wayland_loader.h
- framework/util/xcb_loader.cpp
- framework/util/xcb_loader.h
- tools/replay/README.md
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
Modify gfxrecon-replay so the Linux windowing system selection is not hard-coded at build:
- dlopen XCB and Wayland instead of linking directly
- Add fallback logic to automatically select a compatible WSI platform at run-time
- Add switch --wsi to override the automatic WSI platform selection
> Allow linux replay WSI selection at run time

- framework/decode/vulkan_replay_consumer_base.cpp
- tools/extract/main.cpp
This replaces a hash of the shader contents. It causes some replication
in the extracted shaders but associating shaders with their handle ids has
debugging benefits.
Change-Id: I3e9f43292684451b781c543a7f4fc1a49ce1d11c
> Use handle id in filename for shader extract and replace.

- BUILD.md
- android/framework/util/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/util/CMakeLists.txt
- framework/util/keyboard.cpp
- framework/util/keyboard.h
- framework/util/xcb_keysyms_loader.cpp
- framework/util/xcb_keysyms_loader.h
- Move platform-specific keyboard code out of TraceManager and into separate utility
- dlopen libxcb-keysyms.so instead of linking so capture does not fail on systems without that library
- Add hotkey capture support for Xlib surfaces using XGetXCBConnection and existing XCB implementation
- Better error reporting if a user tries to use hotkey capture and it either isn't supported or encounters an error
> dlopen capture trigger on linux

- tools/extract/main.cpp
- tools/replay/README.md
- tools/replay/replay_settings.h
Now that handle_id is used for shader file names.
Change-Id: I63eb712f73cc1067f63879b6e507bcab7b057500
> Fix usage for gfxrecon-extract and gfxrecon --replace shaders.

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
Update replay to handle the case where switchable graphics layers for managing iGPU/dGPU device selection will reorder or remove entries from the list of physical device handles returned by vkEnumeratePhysicalDevices.  The capture layer can intercept vkEnumeratePhysicalDevices before the list of physical devices is modified, while replay receives the modified list.  
At device creation, replay will now compare the vendor and device IDs from the capture device with the IDs from the available replay devices.  If the device list was reordered, logical device creation will use the physical device with matching IDs.  If the device was removed, replay will warn that there is no match for the capture device.
> Handle vkEnumeratePhysicalDevices Capture/Replay Differences

- framework/decode/vulkan_resource_initializer.cpp
Fixes a memory offset issue when creating and loading data to buffer and image resources during state setup for trimmed files.  The memory offset was specified when mapping memory and was later added to the mapped memory address, resulting in the offset being applied twice.  The offset is no longer applied to the mapped memory address.
> Fix trim issue with non-zero memory offsets

- framework/decode/vulkan_default_allocator.cpp
- framework/decode/vulkan_default_allocator.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
- framework/decode/vulkan_remap_allocator.cpp
- framework/decode/vulkan_remap_allocator.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_allocator.h
* Fix memory offset calculation in VulkanRebindAllocator when reconstructing mapped memory writes on replay.
* Check vkAllocateMemory parameters for valid memory type index at replay, and recommend enabling memory translation when index is valid.
* Update VulkanRebindAllocator memory type selection to ensure that memory allocations captured on discrete GPUs for memory types with both the HOST_VISIBLE and DEVICE_LOCAL properties remain HOST_VISIBLE on replay.
> Fixes for Replay Memory Translation

- framework/decode/vulkan_replay_consumer_base.cpp
For replay on Linux, check for libvulkan.so.1 before libvulkan.so when attempting to dlopen the Vulkan loader.
> Adjust Loader Search Order

- framework/decode/value_decoder.h
- framework/format/platform_types.h
- framework/util/CMakeLists.txt
* Ensure that CheckLibraryExists.cmake is included in CMakeLists.txt prior to using the CHECK_LIBRARY_EXISTS macro.
* Support building with VK_USE_PLATFORM_XLIB_XRANDR_EXT enabled when VK_USE_PLATFORM_XLIB_KHR is disabled.
> Minor Build Fixes

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/custom_vulkan_struct_handle_mappers.cpp
- framework/decode/vulkan_handle_mapping_util.h
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.h
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_header_generator.py
Consolidate duplicate utility code for mapping object IDs to handles created on replay.  Some of the duplicated code was not properly updated for a recent change, which led to a replay issue with descriptor updates.
> Eliminate Duplicate Handle Mapping Code

- framework/decode/vulkan_replay_consumer_base.cpp
The recent changes for memory translation did not support replay of calls to vkDestroyBuffer, vkDestroyImage, and vkFreeMemory with a VK_NULL_HANDLE parameter value.
> Fix replay for image/buffer destroy w/null handle

- scripts/check_code_style.py
Use sys.exectuable when invoking a Python subprocess from within a Python script.
> Use sys.executable to invoke Python

- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
For trimmed files, ensure that the VkDescriptorSetLayout object used to allocate an active VkDescriptorSet is created during the initial state setup.  Addresses the case where the VkDescriptorSetLayout object used for descriptor set allocation is destroyed prior to start of capture.
> Track descriptor set dependencies for trim

- framework/decode/vulkan_replay_consumer_base.cpp
Fixes a warning with a signed/unsigned comparison in an assert statement that was generated by a size_t to int32_t conversion check for a vector of VkPhysicalDevice handles retrieved with vkEnumeratePhysicalDevices.
> Fix 32-bit debug build warning

- tools/extract/main.cpp
Update the gfxrecon-extract consumer class for recent changes to the consumer interface that changed const reference parameters to non-const pointers.
> Update extract consumer interface

- BUILD.md
- CONTRIBUTING.md
- Move clang-format installation instructions from BUILD.md to CONTRIBUTING.md
- Update CONSTRIBUTING.md to specify that changes be submitted against the dev branch
- Add 32-bit build instructions for Linux to BUILD.md
Includes changes from #357
> Update Build and Contributing Documentation

- .clang-format
- CONTRIBUTING.md
- framework/decode/handle_pointer_decoder.h
- framework/encode/capture_settings.cpp
- framework/encode/trace_manager.cpp
- framework/format/platform_types.h
- framework/util/page_guard_manager.h
- layer/trace_layer.cpp
- tools/compress/main.cpp
- Add 'AfterCaseLabel: true' to .clang-format
- Reenable 'AfterExternBlock: true'
- Rearrange declarations in capture_settings.cpp to avoid different formatting results produced by 'clang-format' and 'git clang-format', which seem to be caused by preprocessor directives
- Apply clang-format to the current source
> Update for ClangFormat v9

- framework/util/zstd_compressor.cpp
Use the ZSTD_compressBound function instead of the ZSTD_COMPRESSBOUND macro, which is not available with older versions of the source.
> Use ZSTD_compressBound function

- framework/decode/file_processor.cpp
- framework/decode/pointer_decoder.h
- tools/info/main.cpp
* Handle null application and engine name strings in gfxrecon-info
* Ensure that an incomplete block at the end of a file is treated as a warning for all cases
* Add missing member initializations
> Minor File Processing Updates

- framework/decode/CMakeLists.txt
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Replay does not currently attempt to destroy Vulkan resources that are still active on exit.  For surfaces, when the capture file does not include a vkDestroySurfaceKHR call, the window associated with the surface will be destroyed on exit while the surface is still active.  For Xcb surfaces, a segfault can sometimes be generated on exit when calling xcb_disconnect with active surfaces.
This change ensures that surfaces are destroyed before their associated windows are destroyed.  Support for cleaning up all active Vulkan resources will be added in the future.
Fixes #328
> Ensure surfaces are destroyed on replay exit

- framework/decode/api_decoder.h
- framework/decode/compression_converter.cpp
- framework/decode/compression_converter.h
- framework/encode/trace_manager.cpp
- Add implementations for the virtual methods responsible for processing AHB, device property, and device memory property meta-data to the CompressionConverter class.
- Change the virtual meta-data dispatch methods declared in the ApiDecoder base class to pure virtual to avoid this problem in the future.
> Add missing meta-data types to gfxrecon-compress

- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
Send all Xcb atom requests before waiting for a reply. Splits the XcbWindow::GetAtom method into separate SendAtomRequest and GetAtomReply methods.
> Send all Xcb intern atom requests before waiting for a reply

- tools/compress/main.cpp
- tools/extract/main.cpp
- tools/info/main.cpp
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
- tools/toascii/main.cpp
Add -h and --help options to command line utilities, which will print usage information and exit with a zero return code.
Fixes: #368
> Add -h option to command line utilities

- framework/decode/copy_shaders.h
- framework/decode/custom_vulkan_struct_decoders.h
- framework/decode/vulkan_default_allocator.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_realign_allocator.cpp
- framework/decode/vulkan_realign_allocator.h
- framework/decode/vulkan_resource_initializer.cpp
- framework/decode/vulkan_resource_tracking_consumer.cpp
- framework/decode/vulkan_resource_tracking_consumer.h
- framework/encode/trace_manager.cpp
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- framework/generated/generated_vulkan_struct_decoders.h
- framework/generated/vulkan_generators/vulkan_struct_decoders_header_generator.py
Updates for the '-m realign' memory translation mode to apply memory binding offset changes to parameters from the following API calls:
* vkBindBufferMemory2/vkBindImageMemory2
* vkFlushMappedMemoryRanges/vkInvalidateMappedMemoryRanges
> Updates for Realign Memory Translation Mode

- framework/application/android_window.cpp
- framework/application/android_window.h
- framework/application/wayland_window.cpp
- framework/application/wayland_window.h
- framework/application/win32_window.cpp
- framework/application/win32_window.h
- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
- framework/decode/api_decoder.h
- framework/decode/compression_converter.cpp
- framework/decode/compression_converter.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/window.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
When determining screen orientation for Android replay, consider both the swapchain width/height and pre-transform values.  Adds a new resize window meta-data type that includes width, height, and pre-transform value.
Fixes #347
> Consider swapchain pre-transform value when determining Android screen orientation

- framework/decode/compression_converter.cpp
- framework/encode/trace_manager.cpp
- framework/encode/vulkan_state_writer.cpp
The compression converter was writing a meta-data block with an invalid ID. 
CompressionConverter::DispatchResizeWindowCommand2 was using the kResizeWindowCommand ID instead of the kResizeWindowCommand2 ID, which produced a decode failure on replay.
> Fix invalid block ID from compression conversion

- BUILD.md
Add the zlib dev packages to the list of Ubuntu/Fedora package dependencies.
- Add zlib1g-dev to the Ubuntu package list.
- Add zlib-devel to the Fedora package list.
> Update required package list from BUILD.md

- framework/decode/compression_converter.cpp
- framework/format/format_util.cpp
- tools/compress/main.cpp
Updates to gfxrecon-compress:
- Help will no longer list compression types that were disabled at compile time.
- Cleanup error reporting for unsupported/unrecognized formats.
> Update gfxrecon-compress option handling

- framework/format/format_util.cpp
- framework/format/format_util.h
- tools/info/main.cpp
Update gfxrecon-info to report the capture file's compression format.
Fixes: #410
> Add compression format to gfxrecon-info

- framework/decode/compression_converter.cpp
- framework/encode/trace_manager.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/format/format_util.h
Add a utility function to compute the base size of meta-data blocks.
> Add meta-data block size utility functions

- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
Update the replay code that checks for the capture layer name in the list of layers enabled through the VK_INSTANCE_LAYERS environment variable.  It now only reports exact matches for the layer name and does not report a match for values like 'xxVK_LAYER_LUNARG_gfxreconstructXX'.
Fixes: #293
> Refine replay layer check

- .github/workflows/ci_build.yml
- .github/workflows/release_build.yml
- .github/workflows/sdk_android_build.yml
- .gitignore
- CMakeLists.txt
- cmake/CodeStyle.cmake
- cmake/Test.cmake
- scripts/build.py
- scripts/test.py
Updates to PR #417 to add configurable build and install directories to the build.py script.  Includes the following:
* New --build-dir and --install-dir options for build.py
* Each configuration + platform + architecture configuration now has it's own output directory
* Each configuration + platform + architecture configuration now has it's own cmake files output directory
> Changes to build.py output directories

- framework/application/android_window.cpp
- framework/application/android_window.h
- framework/application/wayland_window.cpp
- framework/application/wayland_window.h
- framework/application/win32_window.cpp
- framework/application/win32_window.h
- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/window.h
* Make the window that creates the surface responsible for destroying the surface.
* Track surfaces with capture ID instead of replay handle.
> Update replay surface management

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/file_processor.cpp
- framework/decode/referenced_resource_table.cpp
- framework/decode/referenced_resource_table.h
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/decode/vulkan_referenced_resource_consumer_base.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_referenced_resource_consumer.cpp
- framework/generated/generated_vulkan_referenced_resource_consumer.h
- framework/generated/vulkan_generators/codegen.pyproj
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_referenced_resource_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_referenced_resource_consumer_header_generator.py
- tools/CMakeLists.txt
- tools/optimize/CMakeLists.txt
- tools/optimize/main.cpp
- tools/optimize/optimizing_file_processor.cpp
- tools/optimize/optimizing_file_processor.h
Adds a new command line utility, gfxrecon-optimize, to remove unused buffer and image initialization data from trimmed capture files.  
For trimmed capture files, a snapshot of the Vulkan API state is written at the start of the file.  This state snapshot includes the data for all buffers and images that were live at the time that capture started.  Some of the buffer and image objects captured in the state snapshot may go unreferenced by the captured frames and their data can be removed from the capture file.
The new file optimization utility will process trimmed files to identify buffer and image objects that were initialized in the state snapshot, but were not used by any of the captured frames, and generate a new capture file that omits the data for these unused buffer and image …
> Add trimmed file "optimization" utility

- USAGE_android.md
- USAGE_desktop.md
- android/scripts/gfxrecon.py
- tools/replay/replay_settings.h
Change to remove the -s option before creating a stable release from the dev branch.  The --sync option was recently added to dev, with -s as an alternative.  The -s option will be used for selecting swapchain modes in the future.
> Remove alternate --sync option

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/vulkan_handle_mapping_util.h
- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_cleanup_util.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.h
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_header_generator.py
If instance or device objects are still live at replay exit, replay will now destroy them and any objects that may have been created from them.  If no instance or device objects were live at replay exit, but other Vulkan objects are live, replay will report the total number of Vulkan objects of each type that were leaked.
This change is primarily targeted at trimmed files, which may not have recorded the API calls to destroy objects.  For Android, leaked resource can be an issue as the replay Activity starts and stops, but the process does not always exit, so consecutive replays either leak resources until the process runs out of memory or start with layers in the state from the previous replay because a VkInstance object was not destroyed and the layer libraries remained loaded by the …
> Destroy Live Vulkan Objects on Replay Exit

- framework/generated/generated_vulkan_referenced_resource_consumer.h
- framework/generated/vulkan_generators/vulkan_referenced_resource_consumer_header_generator.py
Updates to the generated VulkanReferencedResourceConsumer code for consistency with other consumer classes:
- Add the override keyword to the VulkanReferencedResourceConsumer virtual function overrides.
- Add the virtual keyword to the VulkanReferencedResourceConsumer virtual function overrides.
- Fix indentation of VulkanReferencedResourceConsumer method declarations.
> Fix VulkanReferencedResourceConsumer virtual function override declarations

- USAGE_android.md
- USAGE_desktop.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- tools/replay/replay_settings.h
Android replay currently has a single activity, providing a single ANativeWindow with support for creation of a single surface/swaphcain.  This change adds a new command line option for replay to specify the index for a surface to be used for rendering.  Surface/swapchain creation will only be performed for the specified surface.  Creation for other surfaces/swapchains will be skipped.  If swapchain creation is skipped, images will be created to replace that swapchain's images for rendering.
Fixes: #415
> Support Android replay with multiple surfaces

- USAGE_android.md
- USAGE_desktop.md
- android/framework/decode/CMakeLists.txt
- android/scripts/gfxrecon.py
- framework/decode/CMakeLists.txt
- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_feature_util.cpp
- framework/generated/vulkan_generators/codegen.pyproj
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_feature_util_body_generator.py
- tools/replay/replay_settings.h
Adds a new option named --remove-unsupported to adjust instance and device creation parameters to remove unsupported extensions and features.  This can cause replay to fail if the extensions/features are required, but can in some cases make replay work on different devices/drivers for applications that enable more features than they use.
> Add a replay option to disable unsupported extensions and device features

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
Replay will now alter the vkQueuePresentKHR pPresentInfo parameter to ensure that its image indices match the indices returned by vkAcquireNextImageKHR.  This prevents OUT_OF_DATE errors generated by an acquire/present index
mismatch when replaying on Android.  In the case of an index mismatch, rendering is still performed with the image that was acquired on capture, and not the image acquired on replay.  The incorrect render target issue will be addressed by #277.
> Fix acquire/present image index mismatch on replay

- framework/util/logging.cpp
Change the Android logging code responsible for processing the fatal log level to use __android_log_assert, which generates an ANDROID_LOG_FATAL log entry before calling abort, instead of __android_log_print(ANDROID_LOG_FATAL).
> Add assert to fatal log errors for Android

- framework/decode/CMakeLists.txt
- framework/encode/CMakeLists.txt
Update the CMake logic responsible for enabling /bigobj for some files to apply this option for MSVC_VERSION values less than 1920.  It was previously applied for MSVC_VERSION values less than 1910.  This will apply the option for VS2017 and older.
> Apply /bigobj option to VS2017 builds

- CMakeLists.txt
The user's compiler may not be the same as the developer's compiler and its useful to allow disabling `-Werror` in such cases. By default it will be enabled to avoid changing the current behavior, but can be disabled by passing `-DBUILD_WERROR=OFF` as a cmake argument.
> cmake: Add BUILD_WERROR.

- framework/decode/vulkan_replay_consumer_base.cpp
Update the recently added vkDestroyDescriptorPool replay override to handle the case where the VkDescriptorPool handle is VK_NULL_HANDLE.
> Fix descriptor pool destroy override

- framework/decode/screenshot_handler.cpp
- framework/decode/screenshot_handler.h
- framework/decode/vulkan_default_allocator.cpp
- framework/decode/vulkan_default_allocator.h
- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_resource_allocator.h
- framework/decode/vulkan_resource_initializer.cpp
- framework/decode/vulkan_resource_initializer.h
Adds new methods to the VulkanResourceAllocator interface that allow replay to allocate staging resources through the resource allocator, while bypassing the capture-memory-type to replay-memory-type translation that is performed by some allocator implementations.  Replay allocates staging resources, which were not created during capture, for operations such as screen shot creation and resource initialization during the initial state setup for trimmed files.  Allocating staging resources through the resource allocator allows the resource allocator to be aware of all memory allocations performed for replay.
> Add direct allocation calls to resource allocator

- framework/application/xlib_window.cpp
- framework/util/xlib_loader.cpp
- framework/util/xlib_loader.h
Obtain a valid Display* and VisualID to use in vkGetPhysicalDeviceXlibPresentationSupportKHR instead of nullptr and 0.
> Fix Xlib GetPhysicalDevicePresentationSupport

- CMakeLists.txt
- cmake/CodeStyle.cmake
- Apply the BUILD_WERROR option to MSVC builds.
- Set the minimum required CMake version to 3.10.2
Fixes #460
> CMake Updates

- framework/decode/test/main.cpp
- framework/encode/test/main.cpp
Change the log level for test cases to error and above to prevent warnings from being printed in the build output when all tests pass.
> Set log level for tests to error and above

- framework/generated/generated_vulkan_dispatch_table.h
- framework/generated/vulkan_generators/vulkan_dispatch_table_generator.py
The function dispatch tables used for capture and replay never contain null function pointers.  Instead, dispatch table entries for Vulkan functions that are not available from the current implementation are set to a no-op function, which would silently do nothing.  This change updates the no-op functions to print a warning when they are called.
This should help identify issues like the one fixed by #467
> Warn when a no-op function is called

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
When creating the VulkanResourceAllocator during replay, initialize its function table based on the API version specified at VkInstance creation and the extensions enabled at VkInstance and VkDevice creation.  The logic for the function table initialization had looked like:
```
if (device_table->BindBufferMemory2 != nullptr)
functions.bind_buffer_memory2 = device_table->BindBufferMemory2;
else
functions.bind_buffer_memory2 = device_table->BindBufferMemory2KHR;
```
Because the function pointers in the replay dispatch tables are never null, this resulted in no-op behavior for extension or version 1.1 functions that were not enabled.
> Initialize the allocator function table based on API version/enabled extensions

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/capture_overrides.json
Adds support for vkGetBufferOpaqueCaptureAddress to allow capture and replay of applications that use buffer device address features. Handles the setup of the device features and the capture and replay of the buffer addresses.
- Default initialize replay API version to 1.0
- Enable bufferDeviceAddressCaptureReplay bit
- Initial support for opaque buffer addresses
> Add support for opaque buffer addresses

- framework/decode/vulkan_handle_mapping_util.h
Fixes an issue where invalid/uninitialized values could be added to a list of descriptor sets owned by a descriptor pool when replay of vkAllocateDescriptorSets failed with VK_ERROR_OUR_OF_POOL_MEMORY.
> Fix replay issue with descriptor set allocation failure

- android/framework/decode/CMakeLists.txt
- android/framework/util/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/custom_vulkan_struct_decoders.cpp
- framework/decode/custom_vulkan_struct_decoders.h
- framework/decode/decode_allocator.cpp
- framework/decode/decode_allocator.h
- framework/decode/descriptor_update_template_decoder.cpp
- framework/decode/descriptor_update_template_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/handle_pointer_decoder.h
- framework/decode/pointer_decoder.h
- framework/decode/string_array_decoder.h
- framework/decode/string_decoder.h
- framework/decode/struct_pointer_decoder.h
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/generated/generated_decode_pnext_struct.cpp
- framework/generated/generated_vulkan_struct_decoders.cpp
- framework/generated/generated_vulkan_struct_decoders.h
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/vulkan_generators/decode_pnext_struct_generator.py
- framework/generated/vulkan_generators/vulkan_struct_decoders_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_decoders_header_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_mappers_body_generator.py
- framework/util/CMakeLists.txt
- framework/util/monotonic_allocator.cpp
- framework/util/monotonic_allocator.h
Add a custom monotonic/bump allocator for use during decoding. The allocator reserves system memory and provides the decoding functions with fast allocations from that memory. After a function call decode has completed, all custom-allocated objects are simultaneously freed and their memory is available for reuse in future allocations.
- Add MonotonicAllocator utility class
- Create class interface for decode allocations
- Use DecodeAllocator when decoding structs
- Use DecodeAllocator when decoding pointer types
- Use DecodeAllocater when decoding pNext structs
> Add a custom allocator for use during decoding

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
Fix Android build warning and remove unused var.
- Cleanup: remove unused variable
- Fix unhandled enumeration values warning
> Warning fix and code clean up

- framework/decode/pointer_decoder_base.h
- framework/decode/vulkan_handle_mapping_util.cpp
- framework/encode/vulkan_handle_wrapper_util.cpp
These changes fix some issues when replaying ray tracing application captures.
- Enable KHR acceleration structure wrapping
- Read outer array length when decoding 2D arrays
> Fixes for replaying ray tracing enabled apps

- framework/decode/vulkan_replay_consumer_base.cpp
Change replay behavior for vkCmdSetCheckpointNV to silently ignore the pCheckpointMarker value.  Previous behavior was to print a message for each vkCmdSetCheckpointNV call to indicate that the pCheckpointMarker parameter was not an object handle type that replay knew how to map.
> Suppress 'unsupported external object type' messages generated for vkCmdSetCheckpointNV replay

- tools/replay/desktop_main.cpp
For Windows, when a new cmd.exe window is opened at gfxrecon-replay.exe process start, which will close at process termination, wait for user input before exiting the process.  This will keep the cmd.exe window open until a key is pressed, allowing the user to read replay output.
The WIN32 GetConsoleProcessList API call is used to determine if the cmd.exe instance was created when gfxrecon-replay.exe started.  This results in the following scenarios:
- If the user started gfxrecon-replay.exe from an existing cmd.exe instance, the process will exit normally.
- If the user did not start gfxrecon-replay.exe from an existing cmd.exe instance (e.g. the user dragged and dropped a capture file onto the gfxrecon-replay.exe program icon in the file explorer, or launched gfxrecon-replay.exe from …
> Prevent cmd.exe from closing on replay exit

- USAGE_desktop.md
- framework/decode/vulkan_replay_options.h
- framework/encode/capture_settings.cpp
- framework/util/argument_parser.cpp
- framework/util/logging.h
- tools/capture/gfxrecon-capture.py
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
Adds the following command line options to gfxrecon-replay:
--log-level <level> Specify highest level message to log. Options are:
debug, info, warning, error, and fatal. Default is
info.
--log-file <file>   Write log messages to a file at the specified path.
Default is: Empty string (file logging disabled).
--log-debugview     Log messages with OutputDebugStringA (Windows only)
Change-Id: If73a5be5ab1161bf96b7c312313eb6a09381d6f8
> Add logging options to gfxrecon-replay

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Apply the same processing that is performed at capture and replay for vkEnumeratePhysicalDevices to vkEnumeratePhysicalDeviceGroups.  Required for applications that call vkEnumeratePhysicalDeviceGroups instead of vkEnumeratePhysicalDevices.
Fixes: #477
> Treat vkEnumeratePhysicalDeviceGroups like vkEnumeratePhysicalDevices

- tools/capture/gfxrecon-capture.py
- Convert relative capture file paths to an absolute path based on the script's working directory so that capture files are created relative to the script's CWD and not the CWD of the application being captured.  Fixes: #486
- Stop prepending either ./ or the value of the optional working directory argument to relative executable paths. Fixes: #385
> Updates for gfxrecon-capture.py

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- Update Android Gradle plugin version to 4.1.1
- Update Gradle version to 6.5
- Remove ndkVersion from build.gradle files
> Update Gradle version for Android build

- framework/encode/CMakeLists.txt
- framework/encode/trace_manager.cpp
Fixes a crash when capturing a ray tracing app with trimming enabled. Also restores a header file to the generated encode project.
- Fix incorrect type used when wrapping accel struct
- Restore header file to project sources
> Fix accel struct wrapper and missing project file

- android/tools/replay/src/main/AndroidManifest.xml
Add android:extractNativeLibs="true" to the replay tool's Android manifest file.
> Set extractNativeLibs in Android manifest

- framework/decode/vulkan_replay_consumer_base.cpp
Fixes for initialization of the rebind memory allocator, related to enabled extensions:
- Fix missing initialization of the enabled instance extension list that is tracked with VkInstance/VkPhysicalDevice handles.  The extension list was not properly initialized when it was added with commit 9773aded.
- For allocator initialization, use the modified device extension list that was specified when replaying vkCreateDevice, instead of the unmodified list that was captured.
> Fix replay extension tracking for -m rebind

- framework/encode/vulkan_state_writer.cpp
By spec only COHERENT is mandatory, so it is possible finding a driver
not supporting CACHED. The current caller for CreateStagingBuffer
already checks if the buffer is coherent or not.
====
As a specific example, right now the v3dv driver (Mesa vulkan driver for V3D Broadcom GPUs, developed specifically for the rpi4) doesn't support CACHED. This change is needed when capturing with a initial frame different to 1 (that is useful when you want to skip intros, menu UI, etc).
The contribution guide recommends to test this change with DOTA, but that seems too much for the embedded device. I have tested it with Quake3e (a vulkan port of quake3 [1]), with vkQuake2 [2], and Unreal 4 Shooter Game demo [3]
[1] https://github.com/ec-/Quake3e
[2] https://github.com/kondrak/vkQuake2/
[3] …
> Use host coherent as fallback when creating a staging buffer

- framework/decode/descriptor_update_template_decoder.cpp
- framework/decode/descriptor_update_template_decoder.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/custom_vulkan_api_call_encoders.h
- framework/encode/descriptor_update_template_info.h
- framework/encode/trace_manager.cpp
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_api_call_encoders.h
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/generated_vulkan_ascii_consumer.h
- framework/generated/generated_vulkan_consumer.h
- framework/generated/generated_vulkan_decoder.cpp
- framework/generated/generated_vulkan_decoder.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_replay_consumer.h
- framework/generated/vulkan_generators/blacklists.json
- framework/graphics/vulkan_util.h
Support trimming for applications that use KHR ray tracing. Also adds support for acceleration structure descriptor updates with template and a warning if unsupported host acceleration structure functions are used.
- Add trimming support for KHR ray tracing pipelines
- Add util to get pNext struct by type
- Add state tracking for accel struct descriptors
- Add support for accel struct descriptor templates
- Warn if unsupported host accel struct is used
> Add trimming support for ray tracing

- framework/encode/trace_manager.cpp
pMemory is converted to a WrappedHandle and should be unwrapped when used with VkDeviceMemoryOpaqueCaptureAddressInfo.memory. Otherwise, an invalid address will be returned from GetDeviceMemoryOpaqueCaptureAddress.
> Fix VkAllocateMemory with Capture/Replay

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Add trim support for VK_KHR_timeline_semaphore and VK_VALVE_mutable_descriptor_type as well as miscellaneous bug fixes for trim/replay on vkd3d(proton 5.13)+radv(mesa 21.1)
> Improve trim extension support

- android/framework/graphics/CMakeLists.txt
- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_encoder_commands.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/capture_overrides.json
- framework/generated/vulkan_generators/replay_overrides.json
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_device_util.cpp
- framework/graphics/vulkan_device_util.h
- framework/graphics/vulkan_util.cpp
- framework/graphics/vulkan_util.h
If the rayTracingPipelineShaderGroupHandleCaptureReplay feature is supported, attempt to capture and replay ray tracing pipeline's shader group handles. Capture the handles using vkGetRayTracingCaptureReplayShaderGroupHandlesKHR after pipeline creation. Then use the captured handles as pShaderGroupCaptureReplayHandle in VkRayTracingShaderGroupCreateInfoKHRs during replay pipeline creation. Also improve logging for unsupported capture and replay features to reduce false positives and refactor device feature/property setup code.
- Add overrides for vkCreateRayTracingPipelinesKHR
- Enable RT shader grp handle capture replay feature
- Get capture replay rt shader handle size property
- Refactor phys device feature and property util
- Capture ray tracing shader group handle data
- Replay ray …
> Capture and replay ray tracing shader group handles

- framework/decode/vulkan_default_allocator.h
- framework/decode/vulkan_rebind_allocator.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_allocator.h
The rebind allocator may interfere with the replay of device addresses.
Log a warning when trying to replay with the rebind option enabled for
an application that used device addresses.
> Log warning if -m rebind is used with dev addr

- framework/decode/screenshot_handler.cpp
- framework/decode/screenshot_handler.h
Fix mismatch with a comparison between the original image format and screenshot format when creating a staging resource for screenshots.
> Fix screenshot format comparison

- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/encode/trace_manager.cpp
Prevent settings loading from writing to stdout prior to log
initialization when GFXRECON_LOG_OUTPUT_TO_CONSOLE is false.
> Suppress stdout if output to console option is off

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
Track the acquired image index when initializing from trimmed state.
This fixes an issue where the first presented image could be incorrect
or replay could hang.
> Track trimmed state acquired image index

- CMakeLists.txt
- framework/application/CMakeLists.txt
- framework/application/headless_application.cpp
- framework/application/headless_application.h
- framework/application/headless_window.cpp
- framework/application/headless_window.h
- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/generated/vulkan_generators/base_generator.py
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
This adds support for the VK_EXT_headless_surface extension to gfxrecon-replay, allowing us to replay on platforms without a windowing system.
This is very useful for testing and performance tracking on development platforms!
> VK_EXT_headless_surface support

- android/framework/graphics/CMakeLists.txt
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/graphics/CMakeLists.txt
- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- tools/replay/desktop_main.cpp
Add console output for trimmed file state load time. Also, when computing
FPS, account for trimmed state load time (if any) and report as "Replay
FPS".
Example output with trimmed capture file:
```
Load time:  1.435010 seconds
Total time: 7.576557 seconds
Replay FPS: 285.107319 fps, 6.141547 seconds, 1751 frames, framerange 250-2000
```
Example output with complete (not trimmed) capture file:
```
Total time: 6.758087 seconds
Replay FPS: 254.361922 fps, 6.758087 seconds, 1719 frames, framerange 1-1719
```
> Include state load time in post-replay timing info

- framework/decode/vulkan_replay_consumer_base.cpp
vkDestroySwapchainKHR can be called with a null swapchain argument, so
null-check swapchain_info before accessing.
> Handle null swapchain in call to destroy swapchain

- framework/decode/screenshot_handler.cpp
By spec only COHERENT is mandatory, so it is possible finding a driver
not supporting CACHED. The current caller for CreateCopyResource
already checks if the buffer is coherent or not.
This is equivalent to #501 but for screenshot handler.
> Use host coherent as fallback when creating a screenshot copy resource

- framework/decode/descriptor_update_template_decoder.cpp
- framework/decode/descriptor_update_template_decoder.h
- framework/encode/custom_vulkan_api_call_encoders.cpp
Move acceleration structure descriptor data to the end of the encoded
data block for update descriptor with template API calls. Commit
c6ddb43a4e added acceleration structure data size at the start of the
block, breaking capture file compatibility across versions. This change
restores compatibilty. However, any captures made with the affected
change and that use descriptor update with templates may be invalid.
> Fix capture file format for update desc template calls

- layer/json/VkLayer_gfxreconstruct.json.in
Surrender gfxrecon layer settings to gfxrecon developers.
Vulkan Configurator will use these settings when loading the gfxrecon layer.
> Add layer settings to layer manifest

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/annotation_handler.h
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/format/format.h
- Adds a new annotation block type to the capture file format.  The annotation consists of a string with a name/label for the annotation and a string with the annotation data.  The data can be represented as plain text, XML, and JSON.
- Adds a new AnnotationHandler interface.  Custom handlers can be created for processing annotation data.
- Adds support to the FileProcessor for processing annotation blocks that are read from the capture file, passing the annotation name and data to an AnnotationHandler.
> Add annotations to capture file format

- cmake/FindVulkanVersion.cmake
- cmake/GenerateLayerJson.cmake
2 fixes for the layer json file
- Add `@only` to configure_file so it doesn't do substitution on the
vkconfig `${LOCAL}` variable in VkLayer_gfxreconstruct.json.in
- Update the CMake script that extracts version numbers from vulkan_core.h
to work with the new macros in version 176 of the header.
> Vulkan layer JSON fixes

- layer/json/VkLayer_gfxreconstruct.json.in
A bug caused old versions of vkconfig to crash when loading the layers settings from the layer repository.
To workaround this issue, the layer schema was modified, this change makes the layer manifest to match the updated layer schema.
This change need to be cherry picked to SDK-1.2.176 branch.
> Fix layer settings to match layer manifest schema

- android/framework/encode/CMakeLists.txt
- android/framework/util/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/parameter_buffer.h
- framework/encode/parameter_encoder.h
- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
- framework/util/CMakeLists.txt
- framework/util/compressor.h
- framework/util/file_output_stream.cpp
- framework/util/file_output_stream.h
- framework/util/lz4_compressor.cpp
- framework/util/lz4_compressor.h
- framework/util/memory_output_stream.h
- framework/util/platform.h
- framework/util/shared_mutex.cpp
- framework/util/shared_mutex.h
- framework/util/zlib_compressor.cpp
- framework/util/zlib_compressor.h
- framework/util/zstd_compressor.cpp
- framework/util/zstd_compressor.h
- tools/compress/compression_converter.cpp
This PR improves capture performance in some cases. There are two main components:
1. Buffered, thread-safe file writes - capture file blocks are now written in a single combined write containing both header and data. File writes are changed to use thread-safe file writing with fwrite and the file buffer is set to 256k with setvbuf.
2. Shared mutex for state tracking and writing - mutex contention is reduced by using a shared "reader/writer" mutex to guard around state writing. This replaces a single unique mutex that was acquired and released by all threads when writing to file. These mutex changes are dependent on the file writing changes from 1.
Changes:
- Combine block header and data into one file write
- Reserve space in compressed buffer for header
- Reserve header bytes in …
> Optimize capture with combined writes and shared mutex

- android/framework/graphics/CMakeLists.txt
- framework/application/headless_application.cpp
- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_util.cpp
Add a check for VK_EXT_headless_surface before starting replay with a headless surface.  Replay will currently attempt to use a headless surface when the `--wsi headless` option is specified, or when no other WSI platforms are available.  Currently, when VK_EXT_headless_surface is not supported by the replay instance, replay will fail with an error message similar to:
```
[gfxrecon] WARNING - Extension VK_EXT_headless_surface, is not supported by the replay device.
[gfxrecon] FATAL - API call vkCreateInstance returned error value VK_ERROR_EXTENSION_NOT_PRESENT that does not match the result from the capture file: VK_SUCCESS.  Replay cannot continue.
Replay has encountered a fatal error and cannot continue: the specified extension does not exist
```
This change adds a check for …
> Check for headless support

- framework/encode/trace_manager.cpp
When the "unassisted" mapped memory tracking mode is active, ensure that memory objects are removed from the mapped memory list if they are freed while mapped.
> Remove 'unassisted' memory entry on free

- layer/json/VkLayer_gfxreconstruct.json.in
Some gfxreconstruct settings are only available on Windows. The layer manifest schema support this as a result the Windows only settings won't be visible on other OS.
> manifest: some setting are only available on Windows

- .github/workflows/ci_build.yml
- .github/workflows/release_build.yml
Add an "apt-get update" command for the Linux builds defined in the ci_build.yml and release_build.yml actions files.
> Add apt-get update to Linux CI build

- .github/workflows/ci_build.yml
- .github/workflows/release_build.yml
- USAGE_android.md
- USAGE_desktop.md
Adds documentation for the GFXRECON_PAGE_GUARD_PERSISTENT_MEMORY and GFXRECON_PAGE_GUARD_ALIGN_BUFFER_SIZES options.  Also adds some recommendations for selecting page_guard settings for capture, with examples of when to use certain settings when dealing with performance or corruption issues.
> Add documentation for new page_guard settings

- framework/encode/trace_manager.cpp
- framework/encode/trace_manager.h
When an app is done trimming, the file is closed and GFXR sets a state
variable to indicate no additional API calls should be captured to the
file. However there was a race condition around changing the trim state
and the file close, so it was possible for a thread to try and write to file
after it was closed. This is fixed by acquiring the unique state lock
when opening and closing the file.
> Fix a race condition and crash when done trimming

- BUILD.md
- USAGE_android.md
This PR adds instructions for building gfxrecon-replay with Vulkan Validation Layer support and instructions for enabling validation during replay.
> Android VVL Documentation

- BUILD.md
- framework/graphics/vulkan_device_util.cpp
close: https://github.com/LunarG/gfxreconstruct/issues/548
1. Right now, Portal 2 doesn't use either `VK_EXT_buffer_device_address` and `VK_KHR_buffer_device_address` extensions. We also don't keep the old captured file to test, so the error can't be regenerated. 
2. https://github.com/locke-lunarg/Vulkan-Tools/tree/locke-test
I added `VK_EXT_buffer_device_address` into vkcube. It ran capture and replay successfully after I removed the `GFXRECON_LOG_ERROR`. (Some devices might not support `VK_EXT_buffer_device_address`) In this case, I think we should remove the `GFXRECON_LOG_ERROR`.
> Wrong error log for VK_EXT_buffer_device_address 

- framework/application/android_context.cpp
- framework/application/android_window.cpp
- framework/application/android_window.h
- framework/application/application.cpp
- framework/application/application.h
- framework/application/display_window.cpp
- framework/application/display_window.h
- framework/application/headless_window.cpp
- framework/application/headless_window.h
- framework/application/wayland_window.cpp
- framework/application/wayland_window.h
- framework/application/win32_window.cpp
- framework/application/win32_window.h
- framework/application/wsi_context.h
- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
- framework/application/xlib_window.cpp
- framework/application/xlib_window.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/window.h
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/tool_settings.h
This PR enables fallback WSI selection for gfxr replay.
The logic in this PR results in the following behavior...
If there is a WSI selection on the CLI, gfxr-replay will attempt to use that extension.
If the CLI WSI selection fails, gfxr-replay will attempt to fallback to the WSI extension used at capture time.
If the capture time WSI selection fails, gfxr-replay will attempt to fallback to an available WSI extension.
Note that there is no guarantee that WSI configuration will be successful if the playback WSI selection is different from the capture time selection.
This should address issue #583
> [patrick-lunarg][wsi-selection]

- tools/compress/main.cpp
Fixes #567 for the narrow case of a non-zero error code when `gfxrecon-compress` fails, see #627 for an extended task to review exit codes.
> exit with failure if FileProcessor can't be initialized

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
This's for `VK_EXT_full_screen_exclusive`. `vkGetPhysicalDeviceSurfaceCapabilities2KHR` could affect `VulkanReplayConsumerBase::ProcessSetSwapchainImageStateCommand` that's for replaying trimming `format::MetaDataType::kSetSwapchainImageStateCommand`.
In the previous commt, `Trimming: VK_EXT_full_screen_exclusive`, it recorded `vkGetPhysicalDeviceSurfacePresentModes2EXT`,  `vkGetDeviceGroupSurfacePresentModesKHR` and `vkGetDeviceGroupSurfacePresentModes2EXT`. But they might be not necessary.  The `presentMode` has been recorded in `vkCreateSwapchainKHR`. But I think it's ok to keep those code.
> Trimming replay SurfaceCapabilities

- layer/trace_layer.cpp
and fix clang-format for lines I didn't touch just in case CI will kick it back
> pass the layer name downchain to EnumerateDeviceExtensionProperties

- framework/util/argument_parser.cpp
- framework/util/argument_parser.h
- tools/toascii/main.cpp
This PR makes `IsArgumentSet()` behave like `IsOptionSet()`.
`IsOptionSet()` returns `true` when a given option has been set by the user on the cmd line and returns `false` when a given option has not be set by the user. 
`IsArgumentSet()` currenlty returns `true` for any valid argument, regardless of whether or not the argument is set.
This PR adds a member variable called `arguments_present_` and gives it the same treatment as the existing `options_present_` member variable.
> Make IsArgumentSet() Behave Like IsOptionSet()

- framework/decode/api_decoder.h
- framework/decode/custom_vulkan_ascii_consumer.cpp
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/decode/vulkan_ascii_consumer_base.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/decode/vulkan_referenced_resource_consumer_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_resource_tracking_consumer.cpp
- framework/decode/vulkan_resource_tracking_consumer.h
- framework/generated/base_generators/base_decoder_body_generator.py
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/generated_vulkan_ascii_consumer.h
- framework/generated/generated_vulkan_consumer.h
- framework/generated/generated_vulkan_decoder.cpp
- framework/generated/generated_vulkan_decoder.h
- framework/generated/generated_vulkan_referenced_resource_consumer.cpp
- framework/generated/generated_vulkan_referenced_resource_consumer.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_replay_consumer.h
- framework/generated/vulkan_generators/base_generator.py
- framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_decoder_header_generator.py
- tools/extract/main.cpp
- tools/info/main.cpp
This PR adds an `ApiCallInfo` member to `FileProcessor` that can be updated and passed to api call handlers.
> Add API call index and plumb ApiCallInfo down to consumers

- framework/encode/vulkan_state_writer.cpp
compressor == nullptr is a legal construction parameter for VulkanStateWriter (in the case there is no compressor) so remove an assert.
> restore trimming with NONE compression

- USAGE_desktop.md
- tools/CMakeLists.txt
- tools/toascii/README.md
Because of identified issues with the current `gfxrecon-toascii` implementation, `gfxrecon-toascii `is now temporarily removed from the build as we discussed in December.  Until resolved, build `gfxrecon-toascii`, provide the option `BUILD_TOASCII` with a non-false value during `cmake`, e.g.
```
cmake -Bbuild -DBUILD_TOASCII=true
```
Fixes #667
> temporarily disable toascii

- framework/util/logging.cpp
Remove unused variable `message_written` that prevents building with strict checking
> Remove unused variable message_written that prevents building with strict checking

- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_cleanup_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
Turns out we have dealt [with the same issue](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1894) in the past.
The problem is that the nvidia driver adds some XDisplay extensions along with a callback that is called when `XCloseDisplay` is called and for that reason we must first terminate the connection with X11 (call `XCloseDisplay`) and the destroy the `vkInstance` which effectively unloads the driver, causing the callbacks to segfault when called.
> Issue-506: Fix for XCloseDisplay segfaults

- framework/decode/vulkan_replay_consumer_base.cpp
This is a minor bug that could trigger in setups with multiple ICDs
present.
The logic in GetMatchingDevice was erroneously querying the physical
device information of the currently selected physical device, instead of
the one currently in its valuation list. As a result it was possible to
make a perfect match between two completely different physical devices.
> issue-515: Picking wrong physical device when multiple are present

- framework/application/application.cpp
- framework/application/application.h
- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/replay_options.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
@bradgrantham-lunarg @tomped01
I created a new PR for the framerange support PR submitted by @tomped01 
This PR incorporates all commits by Tom, the changes from Brad and a couple of fixes by me that fix a few issues I discovered:
1. There was no way to distinguish a measurement for frameranges that began from frame 1 and when the `--mfr` parameter was not specified.
2. Traces with no frames (i.e. vulkaninfo) were reported as traces with 1 frame, which was confusing.
3. Brad's changes were causing the report of the total frames replayed when the `--mfr` option was not specified to be off-by-1
The PR by @bradgrantham-lunarg that I tried to piggyback was causing some strange conflicts when trying to merge back to dev so I created a new one.
If you all agree with the changes I propose to …
> Framerange support

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
Commit 4ad06dc added a way to workaround the lack of support for
multiple Android surfaces, by giving the ability to choose which one to
create and render on, when a trace creates multiple surfaces/swapchains.
This commit adds a couple of checks for VK_NULL_HANDLE passed around as
surface handles that were missing causing assertion failures.
> Fix for multiple android surfaces workaround

- USAGE_android.md
- USAGE_desktop.md
Accesses done to the protected regions from the kernel will not generate
a segmentation fault and the access will fail.
> Documenting a known issue of the page guard mechanism

- framework/encode/capture_manager.cpp
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
A race condition - bad combination of mutexes existed in the the
codepath of vkCreateInstance which caused a hang when two threads called
the function at the same time. This commit addresses the issue.
Also the internal implementation of shared_mutex is removed in favor of
std::shared_timed_mutex.
> Fix for race condition - deadlock

- framework/format/format.h
- Reserve format::MetaDataType values for future use
- Prevent size_t from being used in capture format
> Misc format.h changes

- BUILD.md
Documented use of `CMAKE_BUILD_PARALLEL_LEVEL` with our Python build script.
> Documented Parallel Build via build.py

- framework/generated/generated_vulkan_struct_decoders_to_string.cpp
- framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
Fixes #790
Most traces don't have function pointers in them so shown to have no ill effects on lots of those locally, and shown to be correct on three traces which do use them, for example a Windows one:
```
"pCreateInfo": {                                 |      "pCreateInfo": {
"sType": "VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSE|          "sType": "VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT",
"pNext": null,                               |          "pNext": null,
"flags": 0,                                  |          "flags": 0,
"messageSeverity": 4352,                     |          "messageSeverity": 4352,
"messageType": 3,                            |          "messageType": 3,
"pfnUserCallback": "140698248157248",        |          "pfnUserCallback": "0x7ff6dd1a1840", …
```
> toascii - Changed Pointers to Functions to Output in hex

- framework/decode/custom_vulkan_ascii_consumer.h
- framework/generated/generated_vulkan_struct_decoders_to_string.cpp
- framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
Fixes #793
Standardises on a decimal integer for handles >= 1 and  the string "VK_NULL_HANDLE" for zero-value ones.
Removes one of the frequent uses of a temporary sstream in passing.
> Convert Handles to Strings using Common Path for Arguments and Members

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- skip dereferencing surface handle if surface is NULL
- don't dereference swapchain images if empty
> Fix crashes when Android surface can't be opened

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/format/format.h
Make a `CreateHardwareBufferCommandHeader2` with uint64_t, transition all encoding to the 2 version, and update `DispatchCreateHardwareBufferCommand` and `ProcessCreateHardwareBufferCommand` to take uint64_t usage, add an additional `FileProcessor` clause for the new `CreateHardwareBufferCommandHeader2`.
Fixes #745.
> create and use CreateHardwareBufferCommandHeader2

- framework/decode/vulkan_captured_swapchain.cpp
The message was warning but the function was LOG_FATAL.  This caused an otherwise potentially workable capture to fail.  Instead, just LOG_WARNING.
> just warn instead of fatal on different image index

- framework/decode/vulkan_handle_mapping_util.cpp
- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_info.h
- framework/encode/vulkan_handle_wrappers.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_object_info_table_base2.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_state_table.h
- framework/generated/vulkan_generators/base_generator.py
SetPrivateData and GetPrivateData need unwrapped objectHandle, like PrivateDataEXT. Also, VkPrivateDataSlotEXT and VkPrivateDataSlot are should be integrated.
> PrivateData handle unwrapped and duplicated

- framework/decode/CMakeLists.txt
- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/decode/vulkan_ascii_consumer_base.h
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py
- framework/util/to_string.h
The point of this PR is to enable a minimal diff from our current format to let it work as JSONLines. Another change may follow later to address the requirements of users.
Fixes Issue #765.
Fixes Issue #783
This is an alternative to [toascii - Minimal Change to Enable JSON Lines Output](https://github.com/LunarG/gfxreconstruct/pull/807), using a different top-level structure, and implying a different per-line dispatch mechanism in processing scripts. **This PR811 is the currently preferred option over PR807**.
The output is like the following examples.
```json
{"index":1,"vkFunc":{"name":"vkEnumeratePhysicalDevices","return":"VK_SUCCESS","args":{"instance":1,"[out]pPhysicalDeviceCount":1,"[out]pPhysicalDevices":[2]}}}
{"index":2,"vkFunc":{"name":"vkGetPhysicalDeviceQueueFamilyProperties"," …
```
> toascii - Minimal Change to Enable JSON Lines Output - Nested Body

- framework/decode/decode_allocator.cpp
- framework/decode/decode_allocator.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/generated/generated_vulkan_decoder.cpp
- framework/generated/generated_vulkan_decoder.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/base_generator.py
- framework/generated/vulkan_generators/blacklists.json
- framework/generated/vulkan_generators/replay_overrides.json
- framework/graphics/vulkan_device_util.cpp
- layer/trace_layer.cpp
The old PRs: https://github.com/LunarG/gfxreconstruct/pull/653, https://github.com/LunarG/gfxreconstruct/pull/773
This PR keeps the original order, so it needs to record parameters and their pointer's data of `CreateRayTracingPipelinesKHR` to avoid those parameters be modified or invalid.
Replay is more complicated than capture. It is to record decode data, like `StructPointerDecoder<Decoded_VkRayTracingPipelineCreateInfoKHR> pCreateInfos`. It added a switch in `DecodeAllocator::End()` to avoid it to clear memory before `DeferredOperationJoinKHR`. It might replay a lot of functions between CreateRayTracingPipelinesKHR and GetDeferredOperationResultKHR. Those functions' data will not be released until `DeferredOperationJoinKHR`. But I think the data size should be not big. A potential …
> Deferred operation for CreateRayTracingPipelinesKHR

- framework/decode/custom_vulkan_struct_decoders_to_string.cpp
Fixes #794
This did pass CI with toascii enabled, that commit since backed-out.
They now reflect current known support.
Refined Logging for untested and unknown descriptor types.
Added comments to explain what work remains.
Everything turned out to be fine just by moving up some IHV-extension image types to be dealt with on standard image path, with a couple of non-P1 types not yet tested but expected to work based on generated code looking correct. Logging adjusted in light of that.
Verification of non-P1 types deferred to a new issue: https://github.com/LunarG/gfxreconstruct/issues/823
> Toascii - Rearranged Cases in ToString (Decoded_VkWriteDescriptorSet&)

- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py
Fixes #819
This passed CI with toascii enabled, and has had the enablement commit backed-out ready for this to be merged.
With this change toascii no longer puts an "[out]" prefix on the names of
variables which point to things that are modified by Vulkan calls.
> Toascii - Strip "[out]" Prefix From Variable Names

- framework/encode/custom_vulkan_encoder_commands.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
- framework/util/platform.h
When page guard mechanism is in use, and the application performs cpu writes and gpu reads/copies to different buffers/images that are bound to the same page of mapped memory, data loss can occur which can lead to rendering artifacts. This can happen when resources are bound to device memory at offsets that are not multiples of the system page size. To work around this the "Page Guard Align Buffer Sizes" environment variable must be set to true (see usage for more information).
This commit will print a warning message when resources are bound at offsets that are not a multiples of the system's page size.
> Check resource binding alignment when page guard is in use

- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/decode/vulkan_ascii_consumer_base.h
- tools/toascii/main.cpp
Toascii - Header Line with source, version, commit.
Fixes #809
Toascii is disabled in the build, but this PR previously passed CI with it temporarily enabled. 
The headers look like:
```json
{
"header": {
"source-path": "<long string>.gfxr",
"json-version": "0.8.0",
"gfxrecon-version": "0.9.15-dev (branch:c13c3fe*)",
"vulkan-version": "1.3.224"
}
}
```
> Toascii - Header Line with source, version, commit.

- BUILD.md
- README.md
- tools/CMakeLists.txt
- tools/convert/CMakeLists.txt
- tools/convert/README.md
- tools/convert/main.cpp
Fixes #833
Part of https://github.com/LunarG/gfxreconstruct/issues/818
Best reviewed after https://github.com/LunarG/gfxreconstruct/pull/830.
gfxrecon-convert is currently disabled in the build but this PR has previously passed CI with it temporarily turned back on.
> Renamed gfxrecon-toascii to gfxrecon-convert

- tools/replay/android_main.cpp
The replay consumer's pointer to the FpsInfo struct wasn't initialized, leading to wrong fps calculation.
> Fix for android trimmed replay stats

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/util/page_guard_manager.cpp
- framework/util/platform.h
Fixes issue: https://github.com/LunarG/gfxreconstruct/issues/802
Replay which use VkImportMemoryHostPointerInfoEXT fails with error
` [gfxrecon] FATAL - API call vkAllocateMemory returned error value VK_ERROR_INVALID_EXTERNAL_HANDLE that does not match the result from the capture file: VK_SUCCESS. Replay cannot continue.`
Vulkan validation layers output:
```
Objects: 1
[0] 0x555cba6d96d0, type: 3, name: NULL
VUID_Undefined(ERROR / SPEC): msgNum: 2044605652 - Validation Error: 
[ VUID_Undefined ] Object 0: handle = 0x555cba6d96d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | 
VkImportMemoryHostPointerInfoEXT: required parameter pHostPointer specified as NULL.
Objects: 1
[0] 0x555cba6d96d0, type: 3, name: NULL
VUID-VkMemoryAllocateInfo-pNext-03332(ERROR / SPEC): msgNum: …
```
> Add VkImportMemoryHostPointerInfoEXT replaying support

- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- tools/convert/README.md
It seems to be a fairly trivial change @bradgrantham-lunarg.
It only counts blocks that were not skipped. Skipped ones are corrupt or were generated by a newer release of the gfxrecon layer than the one being used to convert it.
Alternatives:
1. Count Blocks that failed to decode too.
2. Expand the capture file format to hold the index and have capture write it in there for replay and tools to read out without having to count blocks themselves.
Not that this makes holes in the sequence of calls reported by `Convert`:
```json
{"index":0,"vkFunc":{"name":"vkCreateInstance","return":"VK_SUCCESS","args":{...
{"index":1,"vkFunc":{"name":"vkEnumeratePhysicalDevices","return":"VK_SUCCESS...
{"index":2,"vkFunc":{"name":"vkEnumeratePhysicalDevices","return":"VK_SUCCESS... …
```
> Changed JSON index From Just Functions to all Blocks.

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
Calling vkAcquireNextImage before vkGetSwapchainImages is a valid use
case but was not being handled properly when capturing (tracking)
outside of a trimmed range.
This commit fixes this issue for capturing and replaying
> Lazily resize tracked swapchain images vector

- android/framework/util/CMakeLists.txt
- framework/decode/annotation_handler.h
- framework/decode/file_processor.cpp
- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/decode/vulkan_ascii_consumer_base.h
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/format/format.h
- framework/format/format_util.h
- framework/util/CMakeLists.txt
- framework/util/strings.cpp
- framework/util/strings.h
- framework/util/test/main.cpp
- framework/util/to_string.h
- tools/convert/main.cpp
- tools/info/main.cpp
convert outputs the annotations.
```
{"index":0,"annotation":{"type":"kJson","label":"operation","data":"{\n    \"tool\": \"capture\",\n    \"gfxrecon-version\": \"0.9.15-dev (andy-fix-831-annotate-captures-with-layer-version:621b79a*)\",\n    \"vulkan-version\": \"1.3.231\"\n}\n"}}
```
info counts them and outputs the operation ones.
```
Annotation info:
Total annotations: 1
Operation annotations: 1
{
"tool": "capture",
"gfxrecon-version": "0.9.15-dev",
"vulkan-version": "1.3.231"
}
```
The other tools pass them through unchanged or ignore them as appropriate.
Fixes #831.
> Annotate Captures With Layer Version

- USAGE_android.md
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
Control trimmed capture by setting an env variable. More usefull in Android where setting a hot key is not as simple as on desktop
> Trigger trimming by env variable

- USAGE_android.md
- USAGE_desktop.md
- framework/encode/capture_manager.cpp
- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
This commit adds the possibility to configure the numer of times the signal handler watcher thread will attempt to restore the signal handler by setting an env variable. Setting the variable to a negative number will make the watcher thread run indefinitely.
> Make signal handler watcher thread more configurable

- framework/encode/capture_settings.cpp
This matches the behaviour of the other option parsers, presumably because gfxreconstruct doesn't distinguish between empty and unset environment variables.
> Don't warn on empty integer value

- framework/encode/CMakeLists.txt
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_wrapper_handle_list.h
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_wrapper_handle_list_header_generator.py
The application might use invalid handles that have destroyed. If
HandleWrappers are deleted when the handles are destroyed, it will get
invalid pointer address of HandleWrappers to crash when the application uses
invalid handles. So don't delete HandleWrappers when the handles are
destroyed. Delete HandleWrappers in the ending.
closed: https://github.com/LunarG/gfxreconstruct/issues/677
> Keep HandleWrappers for invalid handles

- framework/util/to_string.h
This is just a documentation quickie.
Added an assertion to the non-obvious template for flag sets
that should never be called. It isn't currently called.
> Documented some ToString Templates

- framework/decode/custom_vulkan_ascii_consumer.h
- framework/decode/custom_vulkan_struct_decoders_to_string.cpp
- framework/decode/vulkan_ascii_consumer_base.cpp
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/generated_vulkan_struct_decoders_to_string.cpp
- framework/generated/generated_vulkan_struct_to_string.cpp
- framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_to_string_body_generator.py
- framework/util/custom_vulkan_to_string.cpp
- framework/util/test/main.cpp
- framework/util/to_string.h
The generated and manual struct and function `ToString`/`ProcessX` functions were wrapping quotation marks around strings for correct JSON output with pairs of string binary additions generating temporary strings and looking messy.
This uses string appends which requires fewer temporary strings and is cleaner and more self documenting at the call sites.
I was about to use this function in my PR for #786 but realised it was inconsistent not to use it for other cases and it would obfuscate that PR to bring in the unrelated changes. I've therefore broken out into this one for easier review of this and of the 786 PR to follow.
This was thought of while contemplating #898 but does not directly address it.
> Added a Quote Function to Wrap Strings in Quotes

- layer/trace_layer.cpp
As noted in #734, `VK_EXT_shader_module_identifier` allows an app to query an identifier for a shader module which then can be used in place of a `VkShaderModule` object.  This causes a crash in capture.  @ishitatsuyuki , will you give this a try?
> block EXT_shader_module_identifier

- framework/encode/vulkan_state_writer.cpp
The Vulkan spec says in VkSemaphoreSignalInfo:
value must have a value greater than the current value of the semaphore.
The initial value is zero, so don't signal zero-valued semaphores.
> Don't write signal for zero valued timeline semaphores

- framework/decode/vulkan_ascii_consumer_base.h
- framework/generated/generated_vulkan_ascii_consumer.cpp
- framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py
- framework/util/to_string.h
Fixes Issue #912 and handles some other types noticed while investigating that.
Some examples of the changed output functions:
```cpp
void VulkanAsciiConsumer::Process_vkGetAccelerationStructureDeviceAddressKHR(
const ApiCallInfo&                          call_info,
VkDeviceAddress                             returnValue,
format::HandleId                            device,
StructPointerDecoder<Decoded_VkAccelerationStructureDeviceAddressInfoKHR>* pInfo)
{
WriteApiCallToFile(call_info, "vkGetAccelerationStructureDeviceAddressKHR", [&](std::stringstream& strStrm)
{
FieldToString(strStrm, true, "device", toStringFlags, tabCount, tabSize, HandleIdToString(device));
FieldToString(strStrm, false, "pInfo", toStringFlags, tabCount, tabSize, PointerDecoderToString(pInfo, toStringFlags, tabCount, …
```
> Convert: Handling for non-void non-VkResult return

- framework/generated/generated_vulkan_struct_decoders_to_string.cpp
- framework/generated/generated_vulkan_struct_to_string.cpp
- framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_to_string_body_generator.py
Uses the correct function for handle output for four cases that debug-related structs have handles represented as uint64_t.
> Correct JSON Output of Handles Represented as uint64_t

- layer/trace_layer.cpp
The old code was triggering a debug assertion in MS STL under rare circumstances.
Subscripting an empty vector is undefined behaviour but calling `data()` on one [is not](https://en.cppreference.com/w/cpp/container/vector/data).
> Removed Subscript of Potentially Empty Vector

- tools/gfxrecon/gfxrecon.py
`gfxrecon.py capture` was replaced with `gfxrecon.py capture-vulkan`. Restore `gfxrecon.py capture` as an alias of `gfxrecon.py capture-vulkan` and print a deprecation warning. Also make commands case-insensitive.
> Restore previous behavior of `gfxrecon.py capture`

- USAGE_desktop_Vulkan.md
- tools/compress/CMakeLists.txt
- tools/convert/CMakeLists.txt
- tools/extract/CMakeLists.txt
- tools/info/CMakeLists.txt
- tools/optimize/CMakeLists.txt
- tools/platform_debug_helper.cpp
- tools/replay/CMakeLists.txt
Add a new linker section in MSVC containing a variable with an initializer function that disables debug popups if GFXRECON_NO_DEBUG_POPUP has a non-empty value
Add some usage information for GFXRECON_NO_DEBUG_POPUP
> disable win dbg popup if GFXRECON_NO_DEBUG_POPUP has value

- framework/util/date_time.cpp
They were being counted from zero to eleven but now use one to twelve as expected.
Fixes https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1194
> Fixed UtcString Months

- framework/decode/dx12_replay_consumer_base.cpp
- framework/encode/dx12_state_writer.cpp
- framework/graphics/dx12_resource_data_util.cpp
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- Limit amount of mem used to read/write trim state
- To prevent paging memory to disk while reading or writing trim state.
- Use STATE_COMMON to read/write resource data
- To prevent occasional corruption of first frame in trimmed capture.
> DX12 trimming fixes

- scripts/gfxrecon-replay-renamed.py
Python script dumps all gfxr messages at the end of replay.
Modify script and instead `subprocess.check_output` use `subprocess.Popen` and loop the process until it is active.
**The result**
Realtime messages available during replay
> Rename script improvements

- framework/decode/dx12_object_info.h
- framework/decode/dx12_replay_consumer_base.cpp
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_writer.cpp
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
This patch queries for whether each device created on encode and decode side is based on a Unified Memory Architecture (UMA) and stores that information alongside the device wrappers . The stored bool is used during trimming to transfer data via the correct `DXGI_MEMORY_SEGMENT_GROUP`.
Unified Memory Architecture devices lack the `DXGI_MEMORY_SEGMENT_GROUP` `..._NON_LOCAL` since all memory is device-visible for them. For UMA devices like those on mobile SOCs and PC integrated GPUs we therefore use the `DXGI_MEMORY_SEGMENT_GROUP` `..._LOCAL` for our own transfers.
Fixes #954.
> Check Whether a Device is UMA During Staging

- BUILD.md
Not the ideal spot for it (should go in contribution.md in a nice new section on code generation), but added to a line that already looks like it needs revising at some point.
Figure it is better to have the variable mentioned somewhere than not at all.
> Noted SDK env var Needed for DX12 Codegen

- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
> Fixed CreateCreate typos and Regenerated for DX12

- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
Trimmed traces often exclude adapter info. The problem is in clearing adapters in `TrackAdapters` method. For trimmed trace we have additional `TrackAdapters` call after `PostProcess_D3D12CreateDevice` (this is where we retrieve which adapter is active). As a result, we are losing track of active adapter. Once it happened no data recorded to file about it.   
The solution is to clear only not active adapter instead of clearing all. This way we are not losing track of what is active at any moment.   
**Results + testing**
As a result of this fix, we have D3D12 adapter info available in every case (including titles where adapter info was missing). Tests performed on normal and trimmed traces.  
Example before changes:
After:
> Include missing adapters in trimmed traces

- framework/decode/vulkan_ascii_consumer_base.cpp
Absolute path to gfxr trace file verified as accepted by chocolatey-installed jq under ARM64 Windows 11 Powershell.
Fixes #1014
> Escaped Strings in JSON Header

- framework/encode/d3d12_capture_manager.cpp
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- framework/util/driver_info.cpp
- framework/util/driver_info.h
We need alternative solution to retrieve driver info in case AGS library would fail to retrieve it   
Read registry from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectX\*` and write it to file 
**Result**
We can use it as an alternative way to retrieve driver.
Example of registry info
> Registry driver version info

- framework/util/to_string.h
A 2D matrix in valid json is [[1,1],[1,1]], while now is represented as [1,1][1,1] which is invalid and jq fails to parse.
This patch fixes it.
> Fix JSON generated on Array2DMatrixToString

- framework/util/custom_vulkan_to_string.cpp
- framework/util/custom_vulkan_to_string.h
The VkPerformanceCounterResultKHR type never appears in the API because it is referred to by a void*, for example by vkGetQueryPoolResults(). Our layer can therefore never see it and have a need to convert it. We lack the local context when converting it to get the type out of the void pointer so adding back in this currently dead code would be a small part of a hypothetical future PR which achieved that feat.
The extension this is part of has also not seen broad support (VK_KHR_performance_query).
> Removed VkPerformanceCounterResultKHR ToString

- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
**Problem**
There are some extensions that we may want to outright ignore during replay.  This is especially true if the extension is present on the capture, but not the replay.
One such extension is the VK_EXT_tool_info extension.  This extension is exposed by the capture layer and may not be present on the system after the capture layer is removed.
**Solution**
Filter out the extension if it is requested when the underlying replay device does not support it.
**Testing**
- Android with capture layer present and then removed on replay
+ Android instance for UI can grab all listed extensions and enable for replay always.
+ However, the entrypoints were not used, just the extension name.
+ Replay worked with message about ignoring the extension.
- Linux with capture layer present for …
> Replay: Add ignorable extensions

- framework/decode/dx12_object_info.h
- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_writer.cpp
- framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
- framework/generated/generated_dx12_replay_consumer.cpp
- framework/graphics/dx12_resource_data_util.cpp
- framework/graphics/dx12_resource_data_util.h
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
In current trim process, if a resource is CPU accessible texture with unknown layout, when saving its data to trimmed trace file during capture, or uploading data to restore resource state during playback, normal resource mapping will be used to save or upload the resource data. However, this shouldn't be the case because texture with unknown layout is a special case for mapping and mapping such resource to get a mapped pointer is invalid. Such trim handling error cause GFXR failed to save or upload the resource data and make trim trace of some title missing HUD text because the title use texture with unknown layout for rendering these HUD text.
The pull request is the fix for the trim handling error. It avoid using normal resource map/unmap when …
> [Bugfix] DX12 Unknown layout texture save/restore

- framework/application/application.h
- framework/decode/vulkan_replay_consumer_base.cpp
Fixes #998 
**Problem**
--wsi replay option adds relevant surface extension on instance creation without removing other surface extensions used in the trace. That makes it impossible to replay on different platforms without --remove-unsupported option.
**Solution**
Surface extensions different than the one specified with --wsi option are removed on instance creation, --remove-unsupported is no longer required.
> Remove competing sufrace extensions with wsi option

- framework/decode/dx12_object_scanning_consumer.cpp
- framework/decode/dx12_object_scanning_consumer.h
- framework/decode/dx12_optimize_options.h
- tools/optimize/dx12_optimize_util.cpp
- tools/optimize/main.cpp
The --dxr optimization option can optimize both DXR and ExecuteIndirect workloads, but the optimization was only run if DXR was present. This change enables the optimization for captures that contain just EI workloads without DXR.
> Check for EI workloads when optimizing with --dxr

- USAGE_android.md
Quick fix for TOC entries that are not valid in updated Android USAGE file.
> Android docs: Fixed invalid TOC entries

- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- tools/optimize/dx12_optimize_util.cpp
- tools/replay/desktop_main.cpp
During replay some traces required agility SDK's D3D12 folder with dlls for it. We need a warning mechanism to notify the user.
I created `VerifyAgilitySDKRuntime` function in `dx12_util` that retrieves executable folder and checking that Agility SDK runtime is in place.
**Result**
Tested with replaying captures. Warning issues during replay if Agility SDK runtime is missing. Also optimizing process tested and warning issued when `--dxr` option was used.
> Logging if the D3D12 folder with DLLs do not exist

- framework/decode/dx12_enum_util.h
- framework/decode/dx12_replay_consumer_base.cpp
If an API call returns D3D12_ERROR_INVALID_REDIST, the expected version of the DX12 Agility SDK was not found and replay cannot continue.
With this change and PR #978, the behavior of replay is to log the below messages and exit when a failed API call is encoutered.
```
[gfxrecon] ERROR - Did not find Agility SDK runtimes. Verify \D3D12\D3D12Core.dll exists in the same directory as gfxrecon-replay.exe.
[gfxrecon] FATAL - D3D12CreateDevice returned D3D12_ERROR_INVALID_REDIST, which does not match the value returned at capture S_OK. Replay cannot continue.
Replay has encountered a fatal error and cannot continue: The D3D12 SDK version configuration of the host exe is invalid.
```
> Exit replay on D3D12_ERROR_INVALID_REDIST error

- framework/decode/vulkan_export_json_consumer_base.h
- framework/generated/generated_vulkan_export_json_consumer.cpp
- framework/generated/vulkan_generators/vulkan_export_json_consumer_body_generator.py
Generated JSON consumer no longer uses WriteApiCallToFile via a lambda and instead uses simple function calls that are easier to debug over/into and which results in three fewer lines of code per supoorted Vulkan function.
Also renamed the `parameters` field in the C++ to `args` to match its name in JSON.
`WriteApiCallToFile()` is retained for manually-written code where it still has the benefit of standardising the common pre and post code that all handlers must repeat.
> Removed Gratuitous Lambda

- framework/encode/capture_manager.cpp
Flush after presents to avoid some cases of capture files with incomplete final blocks. The application logic to quit (e.g. responding to a click on an exit button) is evaluated between a present and the next Vulkan call that would be made and there is lots of code that can crash between the end of one frame's rendering and the next frame's start and between a frame's end and the clean shutdown of the process.
In the event of a clean shutdown, the C standard library is expected to flush any data we have written to our capture file and log, so our concern is with the process we are capturing crashing or being killed by the system, either in any of the logic outside the rendering portion of its main loop, or during the shutdown sequence. By selectively flushing after presents we can take …
> Flush After Presents

- framework/decode/dx12_consumer_base.h
- framework/decode/dx12_replay_consumer_base.cpp
- tools/optimize/dx12_file_optimizer.cpp
- tools/optimize/dx12_file_optimizer.h
- tools/optimize/dx12_optimize_util.cpp
- tools/optimize/dx12_resource_value_tracking_consumer.cpp
If a capture file does not use DXR or EI, mark it as optimized. This
makes log messages more consistent and prevents unnecessary tracking
work done by `Dx12ResourceValueMapper` during replay.
Also make DXR/EI optimizer log messages more consistent.
> Mark captures that don't use DXR/EI as optimized

- tools/optimize/dx12_optimize_util.cpp
If a capture uses EI but doesn't need resource value mapping during replay, inject a noop optimization block to mark the file as optimized for DXR/EI.
> Fix some captures not marked as DXR/EI optimized

- CMakeLists.txt
- framework/application/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/format/CMakeLists.txt
- framework/graphics/CMakeLists.txt
- framework/util/CMakeLists.txt
- layer/CMakeLists.txt
- tools/compress/CMakeLists.txt
- tools/convert/CMakeLists.txt
- tools/extract/CMakeLists.txt
- tools/info/CMakeLists.txt
- tools/optimize/CMakeLists.txt
- tools/replay/CMakeLists.txt
We run unit tests on CI so cannot have interactive UI elements blocking them.
> Disable Debug Assert Popups in Unit Tests

- framework/decode/dx12_ascii_consumer_base.h
- framework/encode/capture_settings.cpp
- framework/util/options.cpp
- framework/util/strings.cpp
- framework/util/strings.h
- framework/util/test/main.cpp
- tools/platform_debug_helper.cpp
- tools/tool_settings.h
Tidied `GetMeasurementFrameRange` using `SplitString()`.
Also refactored duplicate code into `RemoveWhitespace()` and provided a unit test and documented its current (weird) behaviour. It is used where you might imagine trimming whitespace from left and right of a token but it actually removes all whitespace inside the string it is given too. So `"  Hello World!  "` becomes `"HelloWorld!"` rather than `"Hello World!"`.
A following PR will use these functions for other purposes but this PR stands alone as a refactor that pulls an algorithm out of the body of a function and makes it reusable and de-duplicates and documents.
If reviewing, ignore the commits from https://github.com/LunarG/gfxreconstruct/pull/1101. Hopefully they'll be merged to dev before this goes in.
> Added SplitString and RemoveWhitespace Functions

- framework/decode/vulkan_replay_consumer_base.h
This is not and will never be mutable state.
_Reviewers: it is a one-liner so quicker to review than to schedule a review for later!_
> Made Vulkan Replay Consumer Options Const

- framework/decode/dx12_stats_consumer.h
- framework/decode/file_processor.cpp
- framework/encode/d3d12_capture_manager.cpp
- framework/format/format.h
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- tools/info/main.cpp
When we run gfxrecon-info tool on the trace that was captured on the system with 2 GPUs we do not have information which of the adapters were active.
To determine the active adapter, we can track the Object_id by reading the adapters that recorded during capture (based on 'capture_id'), mapping it based on D3D12CreateDevice, CreateCommandQueue, and finally counting with ExecuteCommandLists. The ID with the largest count would indicate the active adapter. The Object_id could be associated with the LUID that belongs to the active adapter.
**Result and Test**
Test on dual GPU:
before:
after:
> Inject adapter ID into metadata and calculate submits per adapter

- BUILD.md
- USAGE_android.md
Link to the new HOWTO_android.md doc from inside the BUILD.md and USAGE_android.md docs so that people can know of the existence of this new document.
> docs: Link to HOWTO_android.md in other docs

- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
Don't assert some things are not null or NULL_HANDLE that can legitimately be null or NULL_HANDLE with graphics pipeline library.  Fix #889 and address the trimming failure noted in #1109.
> Support graphics_pipeline_library

- scripts/build.py
Currently, Launcher and Interceptor can only be built using CMake. 
This pull request provides an option '--build-launcher' that enables it.
**Result and Test**
By default, the "build-launcher" option is disabled, and it is only enabled when explicitly specified.
> enable launcher build from build script

- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_table_base.h
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_tracker.h
- framework/encode/dx12_state_writer.cpp
- framework/graphics/dx12_gpu_va_map.cpp
- framework/graphics/dx12_gpu_va_map.h
During trim state tracking of BuildRaytracingAccelerationStructure, GetResourceWrapperForGpuVa returns wrong resource for aliased resources and trigger GPU crash later.
When searching resource in GPU virtual address map for trim handling of BuildRaytracingAccelerationStructure, make sure the search condition includes and use end GPU address.
**Result**
Tested target title with the pull request, the result show the commit fix the issue.
> Fix raytracing trim error in state tracking

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
Allocating the backing store for all these containers on every call to the function and then freeing it on every exit can be avoided by having them be member variables that are cleared on each call. At least for the vectors this should change their size but not their capacity, and thus not hitting the heap allocation functions once a steady state of reserved capacity is reached.
> Moved Containers out of OverrideQueuePresentKHR

- framework/generated/generated_vulkan_struct_to_json.cpp
- framework/generated/vulkan_generators/vulkan_struct_to_json_body_generator.py
The hope is that replacing auto with the types makes the functions easier to eyeball and makes the large file they are in less of a stress-test for IDE Intellisense-type features.
The difference is like this for each function:
```diff
@@ -3960,8 +3960,8 @@ void FieldToJson(nlohmann::ordered_json& jdata, const Decoded_VkSubpassEndInfo*
{
if (data && data->decoded_value)
{
-        const auto& decoded_value = *data->decoded_value;
-        const auto& meta_struct   = *data;
+        const VkSubpassEndInfo& decoded_value = *data->decoded_value;
+        const Decoded_VkSubpassEndInfo& meta_struct = *data;
FieldToJson(jdata["sType"], decoded_value.sType, options);
FieldToJson(jdata["pNext"], meta_struct.pNext, options);
}
```
> Explicit Types Used to Convert Structs to JSON

- BUILD.md
- CMakeLists.txt
Issue a CMake warning if the SDK version doesn't match the version D3D12 was created with.
> Check Windows SDK version for D3D12 build in CMake

- framework/decode/dx12_replay_consumer_base.h
**Problem**
We were sometimes redundantly running object naming code on non-D3D12 objects
**Solution**
Only rename objects if they are indeed of D3D12 origin
**Testing**
Verified that traces ran correctly with --dx12-override-object-names
> Restrict ID3D12Object name overriding to D3D12 create calls

- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
When debug.gfxrecon.capture_android_trigger is switched between
true/false should now be visible in logcat
> Android capture trigger now appears in logcat

- framework/decode/vulkan_export_json_consumer_base.h
- framework/generated/generated_vulkan_export_json_consumer.cpp
- framework/generated/vulkan_generators/vulkan_export_json_consumer_body_generator.py
They were pretty long. Alternative names could also be:
* `"submit"`
* `"command"`
> Shortened Names of Nested Indexes in JSON

- framework/decode/custom_ags_replay_consumer.cpp
- framework/encode/custom_ags_wrappers.cpp
**Problem**
Some applications may call agsInitialize() with "config" parameter with callback pointer values. At replay, these callback pointer values can not be resolved and will cause replay crash. 
**Solution**
At the capture time, we will force the call with config=nullptr. The agsInitialize call will also be captured as config being nullptr. Implemented in the call wrapper, because adding log there is more straightforward. 
**Result**
Tested with an application passing in "config" parameter containing valid pointer values. The replay is still OK.
> Fix agsInitialize call capture

- framework/generated/generated_vulkan_export_json_consumer.cpp
This should not be here in a generated file. It must be a merge artifact from a PR made against a dev that predated the replacement of that JSON field.
> Replaced Stray "rec_command_index"

- BUILD.md
- HOWTO_android.md
- USAGE_android.md
- android/layer/build.gradle
- android/layer/src/main/AndroidManifest.xml
- android/tools/replay/build.gradle
- android/tools/replay/src/main/AndroidManifest.xml
There was a request to update our targetSdkVersion and compiledSdkVersion to a much more recent version.
Meanwhile, the minSdkVersion will continue to target the same Android release as before.
> android: Update target/compiled SDK versions

- android/layer/build.gradle
- android/tools/replay/build.gradle
A big deal of "warning: pointer is missing a nullability type specifier" kind of warnings were being generated from a third-party library when compiling for Android. This patch should silence those warnings
> Hush Android compile warnings

- android/layer/CMakeLists.txt
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/custom_layer_func_table.h
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/custom_vulkan_api_call_encoders.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- layer/CMakeLists.txt
- layer/trace_layer.cpp
GetBlockIndexGFXR() returns the current block index being processed by the capture manager.
> Expose GetBlockIndexGFXR() from capture layer

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
**Problem:**
--create-dummy-allocations not able to disturb PlacedResource allocation. There is chance that replay recreate PlacedResource at same GPUVA as capture.
**Solution:**
Create a dummy heap before real heap and then release it immediately.
> Add Dummy Heap

- USAGE_android.md
- android/scripts/gfxrecon.py
- tools/replay/android_main.cpp
Add the `--log-file` and `--log-level` options for android at replay time. It is needed in android environments where logcat isn't available.
> Fix --log-file option for Android during replay

- tools/compress/CMakeLists.txt
- tools/convert/CMakeLists.txt
- tools/extract/CMakeLists.txt
- tools/info/CMakeLists.txt
- tools/optimize/CMakeLists.txt
Previously each tool's CMakeLists.txt was restating the linkage for the replay tool.
> Fixed Linking disable_popup_result for all Tools

- framework/decode/dx12_replay_consumer_base.cpp
**Problem:**
The replayer removed all buffers if buffer_count = 0, not recreate buffers. So the no buffers for next rendering.
**Solution:**
If buffer_count == 0, recreate same amount of buffers during replay.
> Fix ResizeBuffers() with buffer_count is 0

- USAGE_desktop_D3D12.md
- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx_replay_options.h
- tools/optimize/dx12_optimize_util.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
**Problem:**
The replayer should always use 'discard-cached-psos'. Currently '--dcp' and '--discard-cached-psos' are options and could not be disabled. 
**Solution:**
Added option'--use-cached-psos' with default 'false'. 'discard_cached_psos' renamed to 'use_cached_psos' and would be set 'true' if used.
**Test:**
Tested with default, enabled and disabled. Warning issued when deprecated '--dcp' is used.
> discard-cached-psos renamed to use_cached_psos

- framework/encode/dx12_rv_annotator.cpp
**Problem:**
If two resources were created on same heap and same offset, released one resource deleted entire GPUVA range.
**Solution:**
If released resource associated to Heap, kept GPUVA range until Heap been released.
> Track removed resource GPUVA

- framework/generated/dx12_generators/blacklists.json
Reenables Python generation for DX12.
`python3.exe generate_dx12.py` was not working for some number of previous commits since the Vulkan blocklists file was changed and the DX12 version not similarly updated.
> Updated the DX12 BlockLists

- framework/generated/dx12_generators/dx12_call_id_to_string_header_generator.py
- framework/generated/generated_dx12_call_id_to_string.h
**Problem**
The `GetDx12CallIdString` generated func was returning "Unknown" for a few notable cases (i.e. ResourceBarrier)
**Solution**
Relax the `dx12_call_id_to_string_header_generator.py` logic for so that it doesn't exclude those cases
**Testing**
No more "Unknown" cases were hit while running `GetDx12CallIdString`
> Fix some call IDs missing in to-string generator

- framework/decode/vulkan_replay_consumer_base.cpp
When replaying vkAcquireNextImageKHR and vkAcquireNextImageKHR2, use an infinite timeout in vkAcquireNextImageKHR* calls if the expected result is VK_SUCCESS.  This prevents timeout errors during replay when the capture plays back faster than it did in the captured Vulkan program.
> gfxrecon_replay: Use infinite timeout in vkAcquireNextImageKHR

- framework/decode/screenshot_handler.cpp
- framework/decode/screenshot_handler.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Screenshot the renderpass's framebuffer color attachments that were used
in a command buffer that marks the end of a VR frame.
> Take screenshots of FB attachments for VR frames 

- framework/application/xlib_context.cpp
- framework/util/xlib_loader.cpp
- framework/util/xlib_loader.h
During shutdown, gfxrecon-replay would sometimes get the following error msg:
xcb_conn.c:215: write_vec: Assertion `!c->out.queue_len' failed.
This error can occur in multi-threaded apps that use xlib.  See man page for XInitThreads() for more info.
This commit adds a call to XInitThreads() before the first call to XOpenDisplay().
> gfxrecon_replay: Add call to XInitThreads on startup

- framework/util/platform.h
Use the appropriate Android NDK Api to get property values instead of launching a new process with popen("getprop ...");
Fixes #1231
> Use system_properties.h api instead of getprop

- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/generated/generated_vulkan_feature_util.cpp
- framework/generated/vulkan_generators/vulkan_feature_util_body_generator.py
In case vkCreateInstance and vkCreateDevice fail at replay time because of an EXTENSION_NOT_PRESENT error, should now print which were the extensions that were not supported on the replay gpu and triggered the error.
Similarly features requested with vkCreateDevice during capture will be compared with what the replay device offers and print a warning for each feature not supported.
> Print differences in supported extensions and features

- android/scripts/gfxrecon.py
- framework/decode/screenshot_handler.cpp
- framework/decode/screenshot_handler.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
Adds two new replay options that controls the screenshot dimensions:
`--screenshot-size <width>x<height>` explicitly sets the dimensions of the
generated screenshot
`--screenshot-scale <number>` Scales the swapchain images by that number.
Number can be decimal
> Screenshot size during replay is now configurable

- .gitignore
- framework/decode/vulkan_captured_swapchain.cpp
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/decode/vulkan_virtual_swapchain.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Modify virtual swapchain to create a command buffer per queue and and per swapchain image.  Then when a vkQueuePresent occurs, perform the blits in the same queue as the presented queue to reduce race conditions.
This resolves the issue where a QueuePresent is presented inline in a queue, but has no wait semaphore information.  Instead, the QueuePresent relied upon the previous submit (also in the same queue) to perform the synchronization.
Previously, the virtual swapchain had it's own Queue that it used which caused a race condition resulting in old images being used.
Fixes: #1122
> Modify virtual swapchain behavior

- tools/launcher/CMakeLists.txt
`gfxrecon_interceptor.dll` is missing when using `build.py --build-launcher` option.
`cmakelists.txt` include install files command.
**Result**
`gfxrecon_interceptor.dll` is copied to bin folder.
> copy gfxrecon_interceptor.dll to bin

- .gitignore
- framework/decode/vulkan_captured_swapchain.cpp
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/decode/vulkan_virtual_swapchain.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
- tools/launcher/CMakeLists.txt
- tools/tool_settings.h
When replaying:
vkAcquireProfilingLockKHR
vkWaitForPresentKHR
vkWaitSemaphores
use an infinite timeout if the expected result is VK_SUCCESS.
> gfxrecon-replay: Use infinite timeout for 3 Vulkan api calls

- USAGE_android.md
- USAGE_desktop_D3D12.md
- USAGE_desktop_Vulkan.md
- tools/replay/replay_settings.h
Adding some more documentation for --screenshot-size and --screenshot-scale that were ommited from b76260d2
> Additional documentation for screenshot dimension options

- USAGE_desktop_Vulkan.md
- framework/decode/vulkan_rebind_allocator.cpp
The debug compiled version of gfxrecon_replay would crash with an assert failure in VMA because the captured app did not destroy all images or buffers that it created before calling vkDestroyDevice. This fix changes the assert failure to a warning.
> gfxrecon_replay: Define VMA_ASSERT to avoid assert crashes

- framework/generated/dx12_generators/dx12_ascii_consumer_body_generator.py
- framework/generated/dx12_generators/gencode.py
- framework/generated/vulkan_generators/base_generator.py
Several generator base class variables have always been shared static variables (effectively global variables which all the generator types can see) rather than ordinary member variables. This has made the order in which generators are run matter since later generators have been seeing the mutations of the variables made by previously run generators.
Prior to this PR, `Dx12AsciiConsumerBodyGenerator` in particular was blocking generation of lots of functions for any consumer added after it.
Rather than adding a workaround like saving/restoring state between generator runs, making the variables ordinary members seems to be the correct fix and that is what this PR does.
> Fix Codegen Side Effects of Modification of Shared Static Variables

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
Adds call index and thread id to the error message displayed when the returned value does not match the original one
> Display call index and thread on failing calls

- android/layer/CMakeLists.txt
- android/tools/replay/CMakeLists.txt
One issue is that the layer and the replay tool both rely on parts of the framework, and they both build the framework into the same output directory.  It also builds each ABI variant into the same output directory, so when doing a subsequent build, even if no inputs have changed, the outputs had been overwritten by other ABI builds, so it has to rebuild for each ABI.
> Fix Android incremental builds

- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
The sequence number in the cookie returned by many xcb calls (i.e. xcb_map_window) is 32 bits. The sequence number in the event returned by xcb_wait_for_event is 16 bits. When comparing the two sequence numbers to see if the xcb call has completed, need to mask off the top 16 bits from the cookie sequence number.
> gfxrecon-replay - handle wrap around of xcb events sequence numbers

- framework/decode/api_decoder.h
It is barely used and there is a second mechanism for sending the current block index around also in use. Clarifies that this is the block index rather than the i'th API call.
```
struct ApiCallInfo
{
/// The block index of a function call. Stream processors like FileProcessor
/// must set this before dispatching function calls to decoders.
/// @note This is lightly used: only for a log output in replay and for JSON
/// Convert.
/// @see ApiDecoder::SetCurrentBlockIndex() which can pass the block index
/// to decoders so it is available for any block type, not just API calls.
uint64_t         index{ 0 };
format::ThreadId thread_id{ 0 };
};
```
> Documented ApiCallInfo.index

- framework/decode/file_processor.cpp
Previously only function calls had their index set in ApiCallInfo. I noticed all the methods had index zero when doing JSON output of DX12  (the ascii consumer counts calls itself not using the block count).
> Set the Block Index for Method Calls

- USAGE_desktop_D3D12.md
- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx_replay_options.h
- framework/encode/dx12_state_writer.cpp
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
**Problem:**
The GFXR trapped system error "bad allocations" on a VM system. But the system reported it had enough memory room for GFXR to replay.
**Solution:**
Add a replay option to set memory usage to avoid system memory issue.
> Set CPU&GPU memory usage by command line option

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/framework/graphics/CMakeLists.txt
- android/scripts/gfxrecon.py
- framework/decode/vulkan_export_json_consumer_base.cpp
- framework/decode/vulkan_export_json_consumer_base.h
- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- framework/util/CMakeLists.txt
- framework/util/json_util.h
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
PR #1175 was merged with dev, mixing commits into the history and creating a merge commit, which we do not do. I would have had to rewrite history to do the required rebase and push to the original branch which I don't want to do so I made a fresh PR for the final rebase on dev. There were also a couple of small changes, one of which needed my knowledge of upcoming changes to the codebase so I went ahead and made them myself.
> Write replay measurements into a JSON file - Finalised

- framework/graphics/fps_info.cpp
Deleted one of the two `std::remove()`s and documented and checked the other.
> Removed std:remove For Measurements File

- framework/generated/dx12_generators/dx12_struct_to_string_body_generator.py
- framework/generated/dx12_generators/dx12_struct_to_string_header_generator.py
Stray code obviously copied from the enum to string generator removed.
Struct generators don't use:
```
BITS_LIST = [
'_FLAGS', '_STATES', '_STATUS', 'D3D12_SHADER_MIN_PRECISION_SUPPORT',
'D3D12_FORMAT_SUPPORT1', 'D3D12_FORMAT_SUPPORT2'
]
```
These are used to detects enums that are bit flags.
> Removed Dead Copied Code

- framework/generated/vulkan_generators/gencode.py
The error in the XML was fixed at Vulkan Headers release 1.3.267 so the patch is no longer needed.
Left the patching code in-place but commented-out as an example of how to do it next time the spec has an error that affects codegen (It contains Mike Magic).
> Disabled Patching VkFrameBoundaryEXT.pTag XML

- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
**Problem**
Full captures contain annotations, but trimmed ones do not. This is happening because:
- Annotation code only runs if `capture_mode_ == kModeWrite`
- Annotation code runs before trimming is activated, at which point `capture_mode_ == kModeTrack`
**Solution**
Permit annotation code to always run when creating a new capture file. This fixes https://github.com/LunarG/gfxreconstruct/issues/1076
**Testing**
Made sure a single annotation was written when testing 
- Full captures
- `GFXRECON_CAPTURE_TRIGGER`
- `GFXRECON_CAPTURE_FRAMES`
> Permit annotations to be written when trimming is activated

- framework/generated/base_generators/reformat_code.py
- framework/generated/generated_vulkan_enum_to_json.h
- framework/generated/generated_vulkan_export_json_consumer.cpp
- framework/generated/generated_vulkan_struct_to_json.cpp
- framework/generated/generated_vulkan_struct_to_json.h
- framework/generated/vulkan_generators/vulkan_enum_to_json_body_generator.py
- framework/generated/vulkan_generators/vulkan_enum_to_json_header_generator.py
- framework/generated/vulkan_generators/vulkan_export_json_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_to_json_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_to_json_header_generator.py
I made this function for Dx12 Convert\* because `inspect.cleandoc` was infuriatingly not doing what I needed. I've pulled it out and applied it on the Vulkan side of JSON generation to try to keep the DX12 branch manageable. If this lands in dev, that other branch will rebase on these changes and simplify for future reviewers.
For anyone reviewing this it might be helpful to note the changes in the generated files are whitespace-only.
\* https://github.com/andrew-lunarg/gfxreconstruct/tree/andy-enhance-better-d3d12-convert
> C++ Indenter for Python Codegen

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_state_writer.cpp
When capturing trimmed under certain conditions texture data were dumped to the capture file using a staging buffer and at during replay they were loaded back to the texture without a staging buffer. This occasionally led to corrupted textures. This patch should address this issue
> Fix in ProcessInitImageCommand

- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
Alternative implementation of #1297 (see discussion in #1317)
clang's arm64 register allocator really doesn't like that giant switch statement, and making it codegen the switch statement tons of times as a part of a template function isn't helping.
> Improve clang arm64 compile time

- scripts/gfxrecon-replay-renamed.py
When run gfxrecon-replay-rename.py with some gfxr traces, the playback may stuck (hang). The issue seems to be related to stdout and stderr PIPE for subprocess.Popen().
Manually rename `gfxrecon-replay.exe` to the application name, playback does not have the hang issue.
If gfxrecon replay displays many messages in the console, the rename Python script could fail. Some applications output many `No ID3D12StateObject was set on the command list before DispatchRays was called. Unable to map the values in the shader table. Replay may fail.` errors to console 'stdout' and replay hangs. 
According to documentation using poll with `stdout = PIPE` can lead to deadlock. `subprocess.run(command, check=True)` can be used to solve this problem. 
**Result**
Playback of …
> Fix rename playback hang

- framework/decode/custom_dx12_struct_decoders.cpp
- framework/decode/custom_dx12_struct_decoders.h
- framework/decode/custom_dx12_struct_object_mappers.cpp
- framework/decode/dx12_resource_value_mapper.cpp
Made it the same as the underlying D3D12_STATE_SUBOBJECT field. Although it is a custom struct, it should have the same name as the raw struct field so that codegen sees it correctly.
Will be used by feature: https://github.com/andrew-lunarg/gfxreconstruct/tree/andy-enhance-better-d3d12-convert
> Renamed Field of Decoded_D3D12_STATE_SUBOBJECT

- framework/decode/custom_dx12_struct_decoders.cpp
It's good practice to avoid a default case that does nothing for a switch case statement that switches on an enum so that the compiler will complain if one of the enumerants is accidentally missed. By extension it is good practice to always avoid such empty defaults so as not to get in the habit of writing them and to save on lines of code which do nothing.
> Removed Empty Default Cases

- scripts/build.py
distutils is deprecated in Python 3.12.  We were only using it for version number checking, and only for "."-separated lists of integers; we don't require the extended version syntax supported by PEP 440.
Simple version checking can be done easily via list comparison of integers, which supports the same "less than" semantics as version comparison, without requiring any external dependency.
build.py:
- use lists of integers to reflect versions being compared
> build: remove requirement on distutils

- android/framework/util/CMakeLists.txt
- external/precompiled/android/include/zstd.h
Include zstd.h and precompiled arm64-v8a and armeabi-v7a binaries for Android
I took the sources from https://github.com/facebook/zstd
For reference, since I couldn't find any instructions on how to build for Android in that repository, the cmake command I used was:
```
cmake -S ../build/cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -D CMAKE_ANDROID_ARCH_ABI=arm64-v8a -D ANDROID_ABI=arm64-v8a -D CMAKE_ANDROID_STL_TYPE=c++_static -D ANDROID_PLATFORM=26
```
> Enable zstd for Android

- tools/optimize/main.cpp
gfxrecon-optimize tool should now return -1 when it fails to recognise input file. Previously it was returning 0 which can be misleading.
> Fix optimize tool's exit code on error

- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
Don't batch command list executions for reading resource data from GPU for trimmed state capture. May reduce memory use during activation of trimming. Reverts some changes from 0103dcf800
> Don't batch resource data reads for trim capture

- framework/decode/file_processor.cpp
When a decode block error occurs, indicate which frame and block are responsible.  This should help at least diagnose if a block is at the begining or end of a trace.
> Improve decode block error logging

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/dx12_consumer_base.h
- framework/decode/marker_consumer_base.h
- framework/decode/metadata_consumer_base.h
- framework/decode/vulkan_consumer_base.h
Give these functions one shared definition rather than two copies duplicated between the DX12 and Vulkan classes.
Fixes #1335.
> Factored out Metadata and Marker Consumer Bases From Vulkan and D3D12 Consumer Bases

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/referenced_resource_table.cpp
- framework/decode/referenced_resource_table.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/decode/vulkan_referenced_resource_consumer_base.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_referenced_resource_consumer.cpp
- framework/generated/generated_vulkan_referenced_resource_consumer.h
- framework/generated/vulkan_generators/capture_overrides.json
- framework/generated/vulkan_generators/vulkan_referenced_resource_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_referenced_resource_consumer_header_generator.py
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
The optimize tool was not taking under consideration ray tracing
features. As a result when applied on a trimmed capture containing such
calls all relative resources were ommited from the optimized tool
leading to corruption during replay.
One key element missing is the relation between top (tlas) and bottom
(blas) level acceleration structures. This relation is described when
the tlas is being build. However when capturing trimmed the tlas build
commands are likely not to be within the capture range and as a result
they are not dumped into the capture file. This makes it impossible for
the optimize tool to deduce from the used descriptors which blases it
should retain in the optimized file.
To solve this a new metacommand is introduced which describes the tlas
to blas dependency and is …
> Better handle for RT applications from optimize tool

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_constant_maps.h
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/vulkan_constant_maps_generator.py
- tools/replay/replay_settings.h
- tools/tool_settings.h
- Check whether the color space used by swapchain is supported by the replay device. Inform the user through log if it is not.
- Introduce an option, that when enabled, will fallback to supported color space for swapchain.
> Added handling missing VK_EXT_swapchain_colorspace

- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/format/format.h
- tools/info/main.cpp
Several options are recommended when dealing with visual corruption on traces. It would be good to know, which non-default options were used when capturing a trace. 
This change captures this information into the operation annotation, if non-default parameters were used, and can be viewed with `gfxrecon-info` tool.
> Adding the capture options to annotation for display with info tool

- framework/encode/vulkan_state_writer.cpp
Some handle types are not correctly handled at fast forwarding time, in particular some switch cases are missing in `VulkanStateWriter::CheckCommandHandle`. This causes strange artifacts, for example when fast-forwarding Sascha Willem's `pushdescriptors` sample.
> Fix forgotten handles in VulkanStateWriter

- framework/decode/dx12_replay_consumer_base.cpp
The memory exception happen due to the subresource_sizes.size() is not equal to layout_sizes.size(). This is because subresource_size has been set twice in Dx12ReplayConsumerBase::ProcessInitSubresourceCommand . 
Thus, this PR removes the line resource_init_info.subresource_sizes = subresource_sizes; The subresource size will be set only by SetResourceInitInfoState .
> Fix memory exception during memcpy in ApplyBatchedResourceInitInfo

- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/generated_vulkan_consumer.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_replay_consumer.h
- framework/generated/vulkan_generators/blacklists.json
- framework/generated/vulkan_generators/capture_overrides.json
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_json_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_json_consumer_header_generator.py
when using deferred operation object in command vkcreateraytracingpipelines, there are two cases with the driver. One is driver proceed all workload in current thread without deferring this command, another case is deferring this command to other threads. The second case is not covered by existing handling. It cause some
title playback failure because reading wrong pipeline data and capture/playback shader group handle, it also cause trim playback failure because ray tracing pipeline creation failure.
The pull request is the fix for these errors. It added needed handling for deferred command and fixed related errors on pipeline reading, capture/playback shader group handle handling and trim deferred operation object handling.
**Result**
All tests passed …
> Fix Vulkan deferred operation handling errors

- framework/encode/dx12_state_writer.cpp
**Problem**
It has been found that the AddRef and Release calls are missing for State Objects, for trim capture only. During the replay, some State Objects may end up being released before they are used again by SetPipelineState1. If this happens, the replay will crash. 
**Solution**
Add WriteAddRefAndReleaseCommands in Dx12StateWriter::WriteStateObjectsState. 
**Result**
The potential crash will be avoided.
> Fix the null pointer issue for State Object for trim capture.

- framework/encode/vulkan_capture_manager.cpp
Would appreciate being given direction on whether the error handling is appropriate - the error code will be propagated upwards which may cause the application to fail (due to exiting on any error). It may also cause replay to fail because the error code for this command won't be VK_SUCCESS.
> Check return value of GetRayTracingCaptureReplayShaderGroupHandlesKHR [WIP]

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/encode/custom_dx12_wrapper_commands.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_state_writer.cpp
- framework/generated/dx12_generators/capture_overrides.json
- framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
- framework/generated/generated_dx12_wrappers.cpp
- framework/graphics/dx12_resource_data_util.cpp
- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
- Add capture and replay handling for resource creation functions added by the Agility SDK.
- Add additional handling to GetCopyableFootprints for resources created by the new creation functions.
- This fixes a potential trimming issues when those new API calls are used.
> Fix handling for new Agility SDK resource creation methods

- framework/decode/custom_vulkan_struct_to_json.cpp
- framework/decode/descriptor_update_template_decoder.cpp
- Fixes a crash when using `vkUpdateDescriptorSetWithTemplate` with acceleration structures, which was caused by allocating new template memory for the acceleration structure information to fit, but forgetting to correct the cached pointers to previously allocated template memory
- Fixes an incomplete information from convert tool for `vkUpdateDescriptorSetWithTemplate`  (#1203)
> Fixes for handling vkUpdateDescriptorSetWithTemplate

- framework/encode/vulkan_state_tracker.cpp
When the descriptor sets are updated using `vkUpdateDescriptorSetWithTemplate` in the captured application, and the update in question involves updating acceleration structures, the trimmed trace would crash on replay.
This is caused by the fact that state recreation uses `vkUpdateDescriptorSets` and `VkWriteDescriptorSet`, which requires the information for the update of acceleration structures be chained in the `pNext` field of relevant `VkWriteDescriptorSet` with `VkWriteDescriptorSetAccelerationStructureKHR` structure filled appropriately. As the `vkUpdateDescriptorSetWithTemplate` does not share this structure, the `pNext` ends up empty on state recreation, and thus causes a crash.
This change fixes that, by filling out the required structure and copying it.
This change also depends …
> Fix a crash on replay for trimmed trace

- framework/decode/vulkan_replay_consumer_base.cpp
When capturing a replay of a capture and `vkAllocateMemory` is called with `VkMemoryOpaqueCaptureAddressAllocateInfo` already in the `pNext` chain, the precedent behavior was to "add" another `VkMemoryOpaqueCaptureAddressAllocateInfo` in front of it.
I think the best behavior is to check for the presence of this struct in the `pNext` chain and, if present, not to touch anything. That is what this commit does.
> Fix `OverrideAllocateMemory` for trimmed traces

- framework/encode/vulkan_state_tracker.cpp
When building aTLASes both primitiveCount and deviceAddress can be zero. These cases should be ignored by the state tracker
> Fix for acceleration structure tracking in the state tracker

- .gitignore
- framework/decode/dx12_consumer_base.h
- framework/decode/file_processor.cpp
- framework/decode/json_writer.cpp
- framework/decode/json_writer.h
- framework/decode/metadata_consumer_base.h
- framework/decode/metadata_json_consumer.h
- framework/decode/vulkan_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
This PR is to fix issue https://github.com/LunarG/gfxreconstruct/issues/1343 where gfxrecon-convert would not emit indices for metadata blocks.
> gfxrecon-convert: Emit index field when writing metadata JSON blocks

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/replay_options.h
- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
Add option to flush and wait all current GPU work to finish at the end of every frame inside the measurement range.
This allows to take measurements on each frame individually without jobs interleaving between two frames.
> Add --flush-inside-measurement-range option

- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
If an application creates multiple swapchains, the images retrieved with vkGetSwapchainImages() can be the same for different swapchains. The parents of swapchain images were not tracked and when one swapchain was destroyed the swapchain image wrappers were as well, even though another swapchain might still be using them
> Fix swapchain image wrappers lifetime

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_resource_value_mapper.cpp
- framework/graphics/dx12_resource_data_util.cpp
- framework/graphics/dx12_resource_data_util.h
Refactor common code for reading or writing resource data into static
functions. The existing functions work the same. The new functions can
be used to allow more control for reading and writing resources.
> Refactor methods in Dx12ResourceDataUtil

- USAGE_desktop_D3D12.md
- USAGE_desktop_Vulkan.md
- framework/graphics/dx12_image_renderer.cpp
- framework/util/image_writer.cpp
- Fix BMP data size calculation for BMP screenshots.
- Reduce PNG compression for better speed.
- Write opaque screenshot for R10G10B10A2 images.
- Add png format info to desktop usage readme files.
> Screenshot improvements

- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
Trim raytracing handling use a device field of memory object wrapper which is not initialized, the error makes some title run into crash with GFXR trim capturing. 
The fix is adding a CreateWrappedHandle template function for VkDeviceMemory which initialize the field in allocation of the Vulkan memory object.
**Result**
Tested target title with the build of the pull request, it fixed the issue.
> Fix trim raytracing invalid device issue

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_virtual_swapchain.cpp
When a `VkImageCompressionControlEXT` instance is found in the `pNext` chain of a `VkSwapchainCreateInfoKHR` instance at swapchain creation for a virtual swapchain, the same compression control should be used to create the images of virtual swapchain (the one not created by the WSI).
This is what this commit does.
> Propagate virtual swapchain image compression

- .clang-format
This cases newer versions of clang-format to fail to format the file.
> Remove duplicate line in .clang-format

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_offscreen_swapchain.cpp
- framework/decode/vulkan_offscreen_swapchain.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/decode/vulkan_swapchain.cpp
- framework/decode/vulkan_swapchain.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- layer/trace_layer.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
This pull request is in fact two PRs with one depending on the other, built in two commits.
Add support for the frame boundary extension `VK_EXT_frame_boundary`. This includes:
- `VkFrameBoundaryEXT` structures found in the pNext chains of `vkSubmitInfo` and `vkSubmitInfo2` are now interpreted as frame delimiters at capture time if `flags` member has the `VK_FRAME_BOUNDARY_FRAME_END_BIT_EXT` bit set.
- The same structures in the same calls support screenshots at replay time by interpreting `pImages` as the rendered frames.
- `VK_EXT_frame_boundary` is now listed as a supported layer device extension (programs that use the layer have access to the extension even if the driver does not support it)
Extended support for this extension that is NOT implemented by this commit could include:
- …
> Support for `VK_EXT_frame_boundary` and usage in offscreen swapchain

- framework/encode/dx12_state_tracker.cpp
There are two major copy modes for CopyAS
For CLONE mode, the dest AS size should be same as source AS size. For other copy mode, GFXR is not able to get dest size yet, so put 1 for now.
> Tracking correct CopyAS dest resource size

- framework/generated/vulkan_generators/base_generator.py
Changed use of re.sub() with replace() to fix warnings when using some versions of Python3.
> Fix warning in python script

- framework/decode/dx12_replay_consumer_base.cpp
**Problem**
Some trim traces won't go through the replayer or optimizer successfully. If an application is in full-screen state, it should be set back to windowed state at the end of the replay. Currently, for some trim traces, the debug layer also complains with "DXGI ERROR: IDXGISwapChain::Release: Swapchain Released while fullscreen. Switch it to the windowed state first. [ MISCELLANEOUS ERROR https://github.amd.com/Developer-Solutions/gfxreconstruct/pull/66: ]."
**Solution** 
Fixed this bug in Dx12ReplayConsumerBase::SetSwapchainInfo() function. 
**Result**
The error can be avoided.
> Add missed "is_fullscreen" value in DxgiSwapchainInfo

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
Some title proceeds pipeline creation call with pipeline cache object. Foe such title, playback may experience performance hit or failure if the pipeline cache object state is different between capture and playback. 
For example, during capture time, pipeline creation command PCC-a was called with a pipeline cache object PCO-a, therefore a compile operation CO-a is not needed because the pipeline cache data can be used for it. During playback time, if the state of the pipeline cache object PCO-a was fully restored, the compile operation CO-a should be also not needed. But there are some cases which make the playback time state of the pipeline cache object PCO-a is different with capture time due to pipeline cache object missing related data, such difference may trigger …
> Fix pipeline cache data handling issue

- framework/generated/generated_vulkan_stype_util.h
Commit 4577d24 which added support for VK_NV_low_latency and commit cfbdab5 which adds codegen for walking decoded pNext chains were merged without rebasing & rerunning codegen first.
Not sure how to prevent this problem in the future as 1. codegen changes aren't super frequent and 2. it would require rerunning CI ontop of dev before ANY change is merged.
> Rerun codegen to get missing sTypes

- BUILD.md
The -H argument normally prints the help message in CMake, but when the period appears directly afterwards it cancels it out. So "-H." is equivalent to ".".
> Update BUILD.md to remove useless CMake arguments

- framework/decode/vulkan_cpp_consumer_base.cpp
- framework/decode/vulkan_cpp_loader_generator.cpp
- framework/decode/vulkan_cpp_utilities.h
- tools/tocpp/main.cpp
Clean up code regarding tocpp platform
* remove a COUNT enum that is unnecessary
* use map to and from platform enums
* remove unsupported or partial platforms WIN32, XLIB, MACOS
* make XCB the default since WIN32, XLIB, and MACOS are unsupported and Android requires the template file dir
> clean up tocpp platform

- framework/encode/capture_manager.cpp
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_writer.cpp
- framework/encode/parameter_buffer.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/util/file_output_stream.h
- framework/util/memory_output_stream.h
- framework/util/output_stream.h
With full warnings enabled on macOS I saw an error with `OutputStream::Reset()` being shadowed by `FileOutputStream::Reset(FILE*)`.  Resolve this shadow by changing the name of Reset for `MemoryOutputStream` to `Clear` (to match C++ container method names), remove the base class `Reset`, and make `FileOutputStream::Reset` not be an override.
> resolve an overridden function with different signature

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_offscreen_swapchain.cpp
- framework/decode/vulkan_offscreen_swapchain.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- framework/decode/vulkan_swapchain.cpp
- framework/decode/vulkan_swapchain.h
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/decode/vulkan_virtual_swapchain.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
Add an option during replay to skip blitting virtual swapchain to real swapchain to remove the overhead of the blit. This overhead is noticeable for microbenchmarks and impacts hardware counter analysis.
The option is "--vssb" or "--virtual-swapchain-skip-blit".
> Add option to skip blit of virtual swapchain

- HOWTO_android.md
`adb shell "settings put global gpu_debug_layers ''"`
> Fixing the typo under Disable The GFXReconstruct layer

- framework/encode/vulkan_capture_manager.cpp
- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager_uffd.cpp
- framework/util/platform.h
Although original page guard memory tracking method (mprotect) is tracking imported AHB buffers, the initial userfaultfd commit did not add support for them.
With this commit imported AHB buffer are now tracked with the userfaultfd method too.
However there is a caveat:
Userfaultfd requires that both base address and length of registered memory regions to be paged aligned. Since in the case of imported buffers we cannot back the regions with a shadow memory (we cannot intercept their allocation and return a shadow pointer instead of the original one), when registering the buffer to uffd we need to page align both base address and length. This can effectively extend the tracking to memory that is not inside the actual buffer and can lead to undefined behavior. A warning message is printed …
> Track AHB buffers with userfaultfd

- framework/decode/screenshot_handler.cpp
- framework/graphics/dx12_util.cpp
- framework/util/image_writer.cpp
- framework/util/image_writer.h
Fixes #1455 
Added `util::imagewriter::WriteBmpImageNoAlpha()` and `util::imagewriter::WritePngImageNoAlpha()`.
Kept previous versions in case the output of alpha channel becomes a command-line option.
> Alpha channel is discarded in screenshots before writing to disk #1455

- framework/util/json_util.cpp
Fix compilation for Apple clang version 15.0.0 by ignoring `<codecvt> `deprecation-warnings for clang.
the reasoning behind simply silencing the warning is the current absence of any stl-alternative
and a generous timeframe for transitioning to something else.
- deprecation in c++17: https://isocpp.org/files/papers/p0636r0.html
- proposal to remove in c++26: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2871r3.pdf
> Fix compilation for Apple clang version 15.0.0

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_resource_value_mapper.cpp
- framework/decode/dx12_resource_value_mapper.h
**Problem**
The replay checks only DXR and EI related calls without checking whether there are resources involved for outputting the DXR/EI optimization console message. gfxrecon-optimize on the other hand tracks the related resources in order to show proper console messages. 
**Solution**
In the replay, we add the checking on whether gfxrecon-optimize will obtain a list of tracked resources without really tracking the DXR/EI related resources. We won't mention "DXR/EI workloads" in the console INFO message if there are only DXR/EI calls with no related resources involved. 
**Result**
Tested the change with applications with DXR and without DXR. The console  message will depend on whether DXR/EI optimization will really happen with gfxrecon-optimize. The message will be either "This …
> Resolving user message conflict between Optimizer and Replay

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- tools/replay/desktop_main.cpp
GFXR's DX12 frame counting logic changed. In some existing captures, the frame that a screenshot index corresponds to may have changed so log a warning.
> Warn if screenshot indexing change is detected

- framework/application/metal_window.mm
vkDestroySwapchainKHR closes its window, and we took that to mean the user had closed the window and wanted to exit
Also adds a printout on user close so similar issues are easier to debug in the future
> Fix exiting on vkDestroySwapchainKHR on macOS

- framework/decode/vulkan_replay_consumer_base.cpp
If a shadow fence is already signaled then it is erased from modified_fences, and if modified_fence_count is 0 the call to vkWaitForFences should be skipped because that is not valid according to VUID-vkWaitForFences-fenceCount-arrayLength
> Dont call vkWaitForFences with fenceCount 0

- .gitignore
This folder is used by clangd vs code extension and can be ignored
> Add .cache in .gitignore

- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_state_writer.cpp
CreateHardwareBufferCmd will now be written to the capture file even when the AHB payload cannot be retrieve at capture time.
> Write CreateHardwareBufferCmd even without AHB data

- CMakeLists.txt
- cmake/FindLZ4.cmake
we normally link dynamically against liblz4,
but that causes trouble on macOS (and iOS) w.r.t. code signatures.
this PR makes minor changes in our toplevel-CMakeLists and FindLZ4.cmake, in order to use a static liblz4 instead
> Use static liblz4-flavour on Apple-platforms

- CMakeLists.txt
- fail when cmake cannot find LZ4 (currently tolerated)
- add cmake-option 'LZ4_OPTIONAL' to build without found liblz4
> Make dependency liblz4 mandatory with opt-out

- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
this was basically duplicating storage of VkAccelerationStructureKHR-handles and only used to track descriptors containing VkAccelerationStructureKHR. we still need a pNext-pointer/struct later, when assembling VkWriteDescriptorSet, but can create that on-the-fly using stack-memory.
> Do not track raw pnext-data in DescriptorInfo

- framework/decode/custom_vulkan_struct_handle_mappers.cpp
- framework/decode/custom_vulkan_struct_to_json.cpp
- framework/decode/vulkan_cpp_consumer_base.cpp
- framework/decode/vulkan_cpp_structs.cpp
- framework/decode/vulkan_cpp_utilities.cpp
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/custom_vulkan_command_buffer_util.cpp
- framework/encode/custom_vulkan_struct_encoders.cpp
- framework/encode/descriptor_update_template_info.h
- framework/encode/vulkan_state_info.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker_initializers.h
- framework/encode/vulkan_state_writer.cpp
overall a low-hanging fruit, adding into existing infrastructure:
- tracking of a binary blob `inline_uniform_block` in DescriptorInfo
- add-hoc (re-)creation of associated pNext-structure for `VkWriteDescriptorSet`
- adapt places skipping over the feature or labeling it unsupported
- gfxrecon-convert: remove a warning about the feature being unsupported
tested successfully with a capture/replay of Sascha's corresponding sample:
https://github.com/SaschaWillems/Vulkan/blob/master/examples/inlineuniformblocks/inlineuniformblocks.cpp
> Add support for VK_EXT_inline_uniform_block 

- android/scripts/gfxrecon.py
Flush/quit on measurement range options should not have an argument to parse.
Using the following commandline for android replay:
`gfxrecon.py replay --quit-after-measurement-range trace.gfxr`
Will currently generate faulty argument list:
`--quit-after-measurement-range True trace.gfxr`
that won't be parsed properly in the replayer. Correct argument list should be:
`--quit-after-measurement-range trace.gfxr`
This PR removes the extra bool parameter from quit-after-measurement-range flush-measurement-range and flush-inside-measurement-range options.
> Fix measurement options for android

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
Force wait on completion of queue operations for all queues before calling Present. This is needed for accurate acquisition of instrumentation data on some platforms.
> Add wait before present option

- framework/encode/vulkan_state_writer.cpp
- fixes trimmed captures for VK_EXT_shader_object
> Add missing state-write for ShaderEXTWrapper

- framework/decode/custom_vulkan_struct_to_json.cpp
- framework/decode/descriptor_update_template_decoder.cpp
- framework/decode/descriptor_update_template_decoder.h
- framework/decode/vulkan_cpp_consumer_base.cpp
- framework/decode/vulkan_cpp_consumer_base.h
- framework/decode/vulkan_json_consumer_base.cpp
- framework/decode/vulkan_json_consumer_base.h
- framework/decode/vulkan_referenced_resource_consumer_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/descriptor_update_template_info.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_writer.cpp
support for `VK_EXT_inline_uniform_block`was added recently. 
this addresses missing things for the combination with `vkUpdateDescriptorSetWithTemplate`.
note:
there are already only few samples for `VK_EXT_inline_uniform_block`, same for `vkUpdateDescriptorSetWithTemplate`.
so I forked Sascha's samples and added a modified version of **raytracingreflections** to cover this scenario, similar to a fork done by @MarkY-LunarG 
used this to verify the changes work:
https://github.com/fabian-lunarg/Vulkan/blob/custom_samples/examples/raytracingreflectionsdesctemplates_inline_uniform/raytracingreflectionsdesctemplates_inline_uniform.cpp
- descriptors are updated per frame via `vkUpdateDescriptorSetWithTemplate` (update after bind is enabled everywhere)
- uniform-buffer was replaced with an …
> Add missing code-path for VK_EXT_inline_uniform_block

- android/framework/encode/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/api_capture_manager.cpp
- framework/encode/api_capture_manager.h
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/custom_ags_wrappers.cpp
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/generated/dx12_generators/dx12_wrapper_body_generator.py
- framework/generated/generated_dx12_wrappers.cpp
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
Split common and api specific options from isA to refsA relationship.
For single API sessions should be exactly equivalent.
This is a first piece of multiple API support needed for pending feature development.
Issues to be resolved:
Settings Arbitration: different API invocations of the layer may have different settings.  Determining where are complete set of options are (without having to repeat them in every JSON) is one challenge.  Resolving which setting "wins" (first, last, some priority heuristic). Settings side effects (like whether an StateTracker is create) need to be address if later invocations can change settings.
A number of interfaces became "public" to support this.  The other choice is friendship between the various CaptureManagers, thoughts?
Also, concerns about …
> Support multiple simultaneous API capture managers

- USAGE_android.md
- android/scripts/gfxrecon.py
Most of this was motivated by a recent exercise of taking captures to reproduce driver bugs on a stock user Android build:
- Rework the Android Writable Locations to encourage app-specific external storage path which requires no additional permissions
- Modernize the layer loading section to use `gpu_debug_layers_app` along with the replay tool APK
- Remove the global layer instructions, in my experience these cause way more problems than they solve.
- Remove the section on rooting, it should not be required for developers debugging their own apps.
> Android doc cleanup

- framework/encode/custom_openxr_api_call_encoders.cpp
- framework/encode/custom_openxr_api_call_encoders.h
- framework/generated/generated_openxr_api_call_encoders.cpp
- framework/generated/generated_openxr_api_call_encoders.h
- framework/generated/openxr_generators/blacklists.json
Move the xrFrameEnd function to be manually defined so that we can trigger a capture manager EndFrame() call after all is done.
> openxr: Move xrFrameEnd to manually generated encode

- framework/decode/decode_api_detection.cpp
- framework/decode/decode_api_detection.h
- tools/optimize/main.cpp
**Problem**
For some cases, 1000 blocks is not enough for API detection.
**Solution**
If the first round detection with 1000 blocks doesn't return any detection result, we will do a second round API detection with no-block-limit parameter. The detection will be done with no block limit, till one of targeted API calls is found. A message will show in the console if the second round is needed.
**Result**
It looks for most cases, 1000 blocks should be enough for the API detection. The second round detection should always give us the result and it will be performed only the first round detection (short) doesn't provide any result.
> Do second round API detect for optimizer if needed

- framework/decode/descriptor_update_template_decoder.cpp
- framework/encode/custom_vulkan_api_call_encoders.cpp
- framework/encode/parameter_encoder.h
- Do not use `ParameterEncoder::EncodeUInt8Array`,  avoid usage of non-portable `sizeof(size_t)`.
- Add '`ParameterEncoder::EncodeRawBytes`' to write raw-byte-arrays without meta-data (and avoid looping over the bytes with 'EncodeUInt8Value')
> Fix for 32/64-bit portability when encoding inline-uniform-blocks

- framework/format/format.h
- tools/optimize/file_optimizer.cpp
FileOptimizer now should insert empty annotation meta commands in place of the resources that are removed as not referenced in a trimmed capture range. This should keep the block index when replaying an optimized trimmed capture in alignment with the block index calculated at capture time.
> Insert dummy annotations in place of optimized out resources

- framework/format/format.h
Reserve MetaDataType values 28-31 in preparation for incoming portable vulkan raytracing changes
> Reserve MetaDataType

- framework/decode/decoder_util.h
Currently decoder will return true from IsComplete and trigger early exit if it has two consumers and one of them completed before the other. This happens because completed consumers are erased from the consumers list which size is then compared against the count of completed consumers.
With this change decoder will report completion only if all its consumers have completed.
> Fix decoder completion condition

- framework/graphics/vulkan_util.h
In case when searching for a struct on `pNext` chain, if the relevant struct is not the first in the list, we would have an infinite loop. 
This commit fixes that.
> Fix of infinite loop when looping over pNext chain

- CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/handle_pointer_decoder.h
- framework/decode/openxr_next_node.h
- framework/decode/openxr_replay_consumer.cpp
- framework/decode/openxr_replay_consumer.h
- framework/decode/pointer_decoder.h
- framework/decode/vulkan_replay_consumer_base.h
- tools/replay/desktop_main.cpp
Narrow path implementation. Only entry-points used by a single test capture.  Android build not updated.
> openxr: Add openxr replay support to Session

- framework/decode/dx12_dump_resources.cpp
- framework/decode/dx12_dump_resources.h
- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/vulkan_replay_dump_resources_json.cpp
Also changed the name of the output json file to < capturefilename >_dr.json for both DX12 and Vulkan. It previously was < capturefilename >_rd.json.
> Change DX12 dump resource json output header so it is consistant with Vulkan

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_vulkan_encoder_commands.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
Currently only `vkCmdDebugMarkerInsertEXT` (under conditions on the name of the marker) is considered a frame delimiter (aside from queue present).
However, `VK_EXT_debug_marker` is deprecated and promoted to the `VK_EXT_debug_utils` extension that support an almost identical command `vkCmdInsertDebugUtilsLabelEXT`.
This commit only add this command as a frame delimiter under the same conditions on the name of the label (which replaces the marker).
> Add vkCmdInsertDebugUtilsLabelEXT as a frame delimiter

- framework/decode/vulkan_replay_consumer_base.cpp
Fences can be signaled with VkSwapchainPresentFenceInfoEXT through vkQueuePresent, and if we are replaying with --surface-index the surface used by vkQueuePresent might not be used. Therefore we have to shadow signal the fence.
vkGetFenceStatus must also check for shadow fences
Closes #1599
> Add missing shadow fences from VkSwapchainPresentFenceInfoEXT

- framework/application/metal_window.mm
- avoid high-DPI resolution conversions ([screen convertRectFromBacking:]
- added explicit [window setContentSize:] to achieve correct swapchain-size
> MacOS: Correct window-size during replay

- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
These two functions have become very hard to read and modify, and full of small edge-case bugs because of this. With this commit I propose to clean a little these two functions, by:
- Removing some unnecessary nested if that should belong in a validation layer, and eventually replacing them with an assert
- Uniformizing variable names between these two functions as they perform a lot of very similar operations
- Adding VK_EXT_frame_boundary as a DEVICE extension, and not an instance extension, which it has never been (and also doing so before setting the modified_extensions in the create info, not after)
- Adding fake support for VK_EXT_frame_boundary
- Removing unsupported device features should only happen when `--remove-unsupported` option is set
> Fix OverrideCreateInstance and OverrideCreateDevice

- framework/decode/custom_vulkan_struct_handle_mappers.cpp
- framework/decode/custom_vulkan_struct_handle_mappers.h
- framework/decode/vulkan_handle_mapping_util.cpp
- framework/encode/custom_vulkan_struct_handle_wrappers.cpp
- framework/encode/custom_vulkan_struct_handle_wrappers.h
- framework/encode/vulkan_handle_wrapper_util.cpp
- framework/generated/base_generators/base_struct_handle_mappers_body_generator.py
- framework/generated/base_generators/base_struct_handle_mappers_header_generator.py
- framework/generated/generated_vulkan_struct_handle_mappers.cpp
- framework/generated/generated_vulkan_struct_handle_mappers.h
- framework/generated/generated_vulkan_struct_handle_wrappers.cpp
- framework/generated/generated_vulkan_struct_handle_wrappers.h
- framework/generated/vulkan_generators/base_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_wrappers_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_handle_wrappers_header_generator.py
The mapping/unwrapping of handles contained in `VkAccelerationStructureBuildGeometryInfoKHR` was not done correctly for multiple reasons:
- The field `VkAccelerationStructureBuildGeometryInfoKHR::ppGeometries` was not correctly handled because of the double pointer
- The type `VkAccelerationStructureGeometryDataKHR` was ignored because it is a union, even though one of the fields of the union can contains handles to map/unwrap in the pNext chain
- VkMicromapEXT was not entirely handled
I tried to fix this in the most clean way to be able to map/unwrap correctly opacity micromaps
> Fix handle mapping/unwrapping for acceleration structure building

- android/framework/decode/CMakeLists.txt
- framework/application/application.cpp
- framework/decode/CMakeLists.txt
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/preload_file_processor.cpp
- framework/decode/preload_file_processor.h
- framework/decode/vulkan_replay_options.h
- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- tools/optimize/block_skipping_file_processor.cpp
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
- tools/tool_settings.h
Adds --preload-measurement-range option allowing to preload a frame range specified with --measurement-frame-range from the trace file into a continuous, expandable buffer, in order to mitigate the impact of read file commands on performance measurements.
> Add trace preload option

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
Add a replay override for ID3D12DeviceFactory::CreateDevice to perform the same device initialization as the D3D12CreateDevice replay override.
> Add ID3D12DeviceFactory replay override

- framework/decode/dx12_replay_consumer_base.cpp
Some title full trace playback failure caused by the handling error of ID3D12Device::CreateConstantBufferView.
In the API ID3D12Device::CreateConstantBufferView, pDesc is an optional parameter, so we need to include nullptr protection for it.
**Result**
Tested the trace file of the target title with the build of the pull request. It fixes the issue.
> Fix playback handling error of ID3D12Device::CreateConstantBufferView

- framework/decode/custom_dx12_struct_decoders.cpp
- framework/decode/custom_dx12_struct_decoders.h
- framework/encode/custom_dx12_struct_encoders.cpp
Fix encoding/decoding for the D3D12_RENDER_PASS_BEGINNING_ACCESS and D3D12_RENDER_PASS_ENDING_ACCESS union members:
- The Clear/Resolve union members were always encoded/decoded, regardless of render pass access type, resulting in uninitialized pointers being dereferenced when the type was not clear or resolve.
- A new union member, PreserveLocal, added by the Agility SDK, was not being processed for encoding/decoding.
> Fix DX12 Render Pass Union Encode/Decode

- USAGE_desktop_Vulkan.md
- android/framework/graphics/CMakeLists.txt
- android/scripts/gfxrecon.py
- framework/decode/replay_options.h
- framework/decode/vulkan_handle_mapping_util.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_struct_deep_copy.cpp
- framework/generated/generated_vulkan_struct_deep_copy_pnext.cpp
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/replay_async_overrides.json
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_pnext_body_generator.py
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_struct_deep_copy.h
- framework/graphics/vulkan_struct_extract_handles.cpp
- framework/graphics/vulkan_struct_extract_handles.h
- framework/util/threadpool.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
this PR adds a threadpool and uses that to compile graphics-pipelines asynchronously.
- Add Threadpool to utils
- Add a generic `vulkan_struct_deep_copy` to create required deep-copies of input structures
- Add a type-trait `has_handle_future` to add the option to retrieve/sync async-handles via std::future,
-  currently that's only `VkPipeline` (but should also include `VkShaderEXT`)
- Add `AddHandleArrayAsync` routine to handle-mapping API
- Add tracking and deferred deletion of handles that are used as dependencies during asynchronous tasks
-  currently only supports `vkCreateGraphicsPipelines`
- default: do not use any asynchronous operation or threadpool unless explicitly requested:
- Add CLI-option `--pipeline-creation-jobs` or `--pcj` to specify number of background-threads
- …
> Asynchronous Pipeline Creation

- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/graphics/vulkan_resources_util.cpp
The calculations for the size of indirect draw calls param buffer was off.
> vulkan dump resources fixes

- android/framework/graphics/CMakeLists.txt
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_track_struct.h
- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/generated_vulkan_struct_deep_copy.cpp
- framework/generated/generated_vulkan_struct_deep_copy_stype.cpp
- framework/generated/vulkan_generators/gencode.py
- framework/generated/vulkan_generators/replay_async_overrides.json
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_stype_body_generator.py
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_check_buffer_references.h
- framework/graphics/vulkan_struct_deep_copy.h
- framework/graphics/vulkan_struct_extract_handles.cpp
- framework/graphics/vulkan_struct_extract_handles.h
- tools/replay/replay_settings.h
- Extends support for asynchronous pipeline/shader-compilation to `vkCreateComputePipelines`, `vkCreateShadersEXT`
- Add missing sync before destroying `VkPipeline`, same for `VkShaderEXT`
- minor improvement for `vulkan_struct_deep_copy` routine, cover some edge-cases
- minor cleanup/refactoring
> Extend Async Support: vkCreateComputePipelines, vkCreateShadersEXT

- framework/decode/vulkan_cpp_template_strings.h
- framework/generated/generated_vulkan_cpp_consumer.cpp
- framework/generated/generated_vulkan_cpp_structs.cpp
- framework/generated/vulkan_generators/vulkan_cpp_consumer_body_generator.py
- framework/generated/vulkan_generators/vulkan_cpp_struct_generator.py
This fixes a few different crashes/compilation issues seen with gfxrecon-tocpp on Android captures. The bulk of the change is better handling of output (non-const) arguments and struct members.
> tocpp Fixes

- android/framework/graphics/CMakeLists.txt
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_check_buffer_references.cpp
- framework/graphics/vulkan_check_buffer_references.h
- framework/graphics/vulkan_struct_extract_handles.cpp
- framework/graphics/vulkan_struct_extract_handles.h
- `VkPipelineShaderStageCreateInfo` 'can' provide a `VkShaderModuleCreateInfo` in pNext
- Add helper-routines to check for that case
- Add a nullptr-check required in certain cases, in presence of asynchronous pipeline-creation (`--pcj X` option)
- Refactoring and doc of `vulkan_struct_extract_handle_ids`
> Check SPIRV/Buffer-References inlined in pNext

- framework/decode/vulkan_replay_consumer_base.cpp
VkDestroyCommandPool specs state that pool can be a null handle, yet its override in replay asserts the pool info struct pointer.
> Remove assert from DestroyCommandPool

- framework/encode/capture_manager.cpp
As the member variable was not initialized to correct default value if the relevant capture option was not used, it resulted into `gfxrecon-info` incorrectly reporting the capture option usages.
> Fix uninitialized member

- framework/decode/CMakeLists.txt
- framework/encode/CMakeLists.txt
Rather than adding the /bigobj flag to individual files, apply it to the entire static library on MSVC
> build: Apply /bigobj for encode & decode targets

- framework/decode/decode_json_util.h
- framework/decode/pointer_decoder_base.h
- framework/decode/struct_pointer_decoder.h
When converting `vkCmdBuildAccelerationStructuresKHR`, there was incorrect information in the resulting file, namely missing build ranges.
`ppBuildRanges` is a an array of pointers of `infoCount` pointers to arrays of `geometryCount` of a particular build geometry info. Previously, convert was failing to extract this information if the `infoCount` or `geometryCount` was `> 1`.
This commit enables convert to extract the info correctly.
> Fixing ppBuildRanges for gfxrecon-convert

- framework/decode/vulkan_offscreen_swapchain.cpp
- framework/decode/vulkan_offscreen_swapchain.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_swapchain.cpp
- framework/decode/vulkan_swapchain.h
- framework/decode/vulkan_virtual_swapchain.cpp
To submit VkFrameBoundaryEXT, a queue submission is necessary but not having a command buffer inside the queue submission. Empty command buffers are badly handled by some drivers and the management of this buffer uselessly requires some resources and can cause bugs when the replayer terminates unexpectedly.
I propose to simply remove this empty command buffer entirely.
> Remove empty command buffer from frame boundary submission

- framework/util/spirv_parsing_util.cpp
- check for required CapabilityPhysicalStorageBufferAddresses
- bail out early, decrease avg parsing-time
thanks @spencer-lunarg :)
> Check SPIRV-capabilities, early exit parser

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- Keep track of externally synchronized pipeline-caches
- Avoid async operations when using externally synched pipeline-cache
> Avoid async w. externally synched pipeline-caches

- framework/graphics/vulkan_resources_util.cpp
- framework/graphics/vulkan_resources_util.h
When scaling up a dump resources image, the size of the temp memory used was calculated based on the size of the pre-scaled image, resulting in an attempt to access beyond the end of the temp memory.
Also removed method GetImageResourceSizesLinear since it is not referenced anywhere in the code.
> Dump resources: Fix scaling of dump resources images

- framework/decode/dx12_dump_resources.cpp
- framework/decode/file_processor.cpp
- framework/decode/file_transformer.cpp
- framework/decode/json_writer.cpp
- framework/decode/preload_file_processor.cpp
- framework/decode/vulkan_cpp_util_datapack.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_dump_resources_json.cpp
- framework/graphics/fps_info.cpp
- framework/util/buffer_writer.cpp
- framework/util/file_output_stream.cpp
- framework/util/file_output_stream.h
- framework/util/image_writer.cpp
- framework/util/json_util.cpp
- framework/util/logging.cpp
- framework/util/memory_output_stream.cpp
- framework/util/memory_output_stream.h
- framework/util/output_stream.h
- framework/util/platform.h
- tools/extract/main.cpp
These signals are sometimes randomly encountered especially on networked filesystems and should be handled by resuming the file operation, rather than aborting or causing errors later during file processing.
The Windows code was not touched because I do not really know how these functions work on that platform.
> Handle soft signal interrupts during file processing

- framework/decode/dx12_resource_value_mapper.cpp
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
- framework/format/format.h
- framework/graphics/dx12_util.cpp
Add support for BuildRaytracingAccelerationStructure when D3D12_ELEMENTS_LAYOUT_ARRAY_OF_POINTERS is used in the build desc.
> Support D3D12_ELEMENTS_LAYOUT_ARRAY_OF_POINTERS

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/graphics/vulkan_device_util.cpp
- framework/graphics/vulkan_device_util.h
- framework/graphics/vulkan_shader_group_handle.h
- framework/util/hash.h
- extract+provide required raytracing device-properties for capture- and replay-time (handle-sizes & alignments)
- add required vanilla hash-utils (hash_combine, hash_range -> matching boost's utils)
- create an efficient wrapper-type (`shader_group_handle_t`) that can be compared and hashed (-> can be used as key in std::unordered_map)
- provide a LUT inside `decode::PipelineInfo` to map from capture- to replay-time handles.
this matches @bradgrantham-lunarg's [proof-of-concept](https://github.com/LunarG/gfxreconstruct/compare/dev...bradgrantham-lunarg:gfxreconstruct:brad-hack-shader-group-handles), fleshing out some details, but please note:
no re-mapping is actually added/performed (that part of the proof-of-concept was still too hacky). 
so this PR is only a necessary stepping-stone …
> Raytracing: Shader-group-handle mapping

- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/encode/custom_openxr_api_call_encoders.cpp
- framework/generated/generated_openxr_api_call_encoders.cpp
- framework/generated/generated_openxr_replay_consumer.cpp
- framework/generated/generated_openxr_replay_consumer.h
- framework/generated/openxr_generators/gencode.py
- framework/generated/openxr_generators/openxr_api_call_encoders_body_generator.py
- framework/generated/openxr_generators/openxr_replay_consumer_body_generator.py
Integrated two fixes from earlier branches to address VkPhysicalDevice issues, and force the predictedDisplayTime as the endframe displayTime.
Result.  Record and replay on Monado on desktop.
VkPhysicalDevice issues require *recordings* be from this pull request, as earlier recordings will not have the need information.
> Fix physical device and presentation time.

- framework/encode/vulkan_capture_manager.cpp
When AHardwareBuffer does not have usage AHARDWAREBUFFER_USAGE_CPU_READ_MASK, reading from the buffer is skipped and memory is instead filled with 0. All the other paths print a warning, but here it was missing
> Warn when AHardwareBuffer read is skipped

- framework/graphics/dx12_resource_data_util.cpp
Modify copy resource message to only log error when required subresource size is less than the actual subresource size and log debug message if required subresource size is greater than the actual subresource size
> modify copy resource message

- android/framework/graphics/CMakeLists.txt
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker_initializers.h
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_check_buffer_references.cpp
- framework/graphics/vulkan_struct_get_pnext.h
- framework/graphics/vulkan_util.h
- pNext-chains: replace a commonly repeated loop-pattern with an existing utility-function
- resolve sType with existing GetSType-util
- rename, doc and move to dedicated header
- applied in locations matching grep-pattern '== VK_STRUCTURE_TYPE'
> Refactor pNext-util, enforce usage

- framework/graphics/dx12_util.cpp
- framework/graphics/dx12_util.h
The current WriteToSubresource size calculation may not work correctly when either the DstSubresource parameter is greater than 0 or the subresource is a texture with a block compressed format.
The size calculation was updated to handle these cases using texture utility code that was originally added for D3D11, where it is used for the D3D11 UpdateSubresource and WriteToSubresource size calculations.
This fixes some crashes in ID3D12Resource::WriteToSubresource observed when capturing on devices with integrated GPUs.
> Fix D3D12 WriteToSubresource size calculation

- BUILD.md
This bit me when updating to latest dev--just a doc tweak to mention the new Java version required for Gradle #1667
> Clean up Android/Java section of BUILD.md

- framework/decode/dx12_replay_consumer_base.cpp
At replay, the buffer returned by IDXGISwapChain::GetBuffer was always cast to an ID3D12Resource type, which can lead to a crash when the caller requests a different type.
With this change, the returned buffer is only processed as an ID3D12Resource type when the caller specifically requested an ID3D12Resource type.
> Make IDXGISwapChain buffer cast conditional

- BUILD.md
Under the "Additional Linux Command-Linux Prerequisites", there was a hanging back-quote in the android home sdk path. This removes the quote.
> Remove hanging back-quote

- framework/decode/vulkan_object_info.h
- framework/graphics/vulkan_device_util.h
Minor changes to reduce warnings seen when using gfxreconstruct, no (intentional) functional changes.
Using struct as in the definition for forward declaration of the ReplayDeviceInfo tag (clang -Wmismatched-tags)
Explicitly define assignment operators for clang
-Wdeprecated-copy-with-user-provided-copy warning.
clang output:
> definition of implicit copy assignment operator for 'ShaderDescriptorInfo'
> is deprecated because it has a user-provided copy constructor
> Fix warnings

- framework/decode/vulkan_realign_allocator.cpp
- framework/decode/vulkan_realign_allocator.h
- framework/decode/vulkan_resource_tracking_consumer.cpp
- framework/decode/vulkan_resource_tracking_consumer.h
- framework/decode/vulkan_tracked_object_info.h
- framework/decode/vulkan_tracked_object_info_table.cpp
- framework/graphics/vulkan_resources_util.cpp
- framework/graphics/vulkan_resources_util.h
Some applications update data of images which is in mapped memory. For such application, it shows corruption if replaying the captured trace file with -m realign option.
The root cause of the problem is related process doesn't have the handling for updating mapped memory image data. The commit added the handling.
**Result**
Tested the target application with the build of the pull request on the same or different GPU/Driver system with -m realign option, it fixed the issue.
> Fix mapped memory image data update issue

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/vulkan_buffer_tracker.cpp
- framework/decode/vulkan_buffer_tracker.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- Add `VulkanBufferTracker` class -> map device-addresses (ranges) to BufferInfo*, O(log n)
- Add `OverrideGetBufferDeviceAddress`, track capture/replay buffer-addresses during replay
- Add `OverrideCmdTraceRaysKHR`, sprinkle asserts using buffer-tracker queries
- Augment `OverrideBindBufferMemory` with tracking logic
Building up necessary foundation as demonstrated by @bartosz-muszarski-arm's  [portable-raytracing branch](https://github.com/LunarG/gfxreconstruct/pull/1533)
> Track Buffer-Device-Addresses

- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/metadata_consumer_base.h
- framework/decode/openxr_decoder_base.cpp
- framework/decode/openxr_decoder_base.h
- framework/decode/openxr_json_consumer_base.cpp
- framework/decode/openxr_json_consumer_base.h
- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/encode/custom_openxr_encoder_commands.h
- framework/encode/openxr_capture_manager.cpp
- framework/encode/openxr_capture_manager.h
- framework/format/format.h
Capture the view relative location of the `XrCompositionLayer...` at record time, and at replay time create view relative spaces to use for the `XrFrameEndInfo` submitted as proxies for the spaces specified.
View relative information also in JSON output.
Fixes #1720
> Add View Relative data to capture/replay

- framework/encode/dx12_state_writer.cpp
TLAS could point NULL BLASs.
It's valid, we should not discard the TLAS.
> TLAS instance desc NULL pointer

- framework/util/spirv_parsing_util.cpp
Certain optimizations may remove SPIR-V instructions such as OpName (actually some title may remove all such instructions with shader optimization tool), which can lead to a nullptr name in the spirv_reflect SpvReflectDescriptorBinding struct. This occurs because spirv_reflect sets the name by keeping track of these SPIR-V instructions. The error causes an access violation issue when parsing the shader code.
The commit addresses the issue by setting the root_name to empty in handling this scenario when parsing the shader code.
**Result**
Tested the target title with the build of the pull request, it fixed this issue.
> Fix Capture Crash Caused by Error in Parsing Shader Code

- framework/generated/generated_vulkan_struct_deep_copy.cpp
- framework/generated/generated_vulkan_struct_deep_copy_stype.cpp
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_body_generator.py
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_stype_body_generator.py
part 1:
- do not copy 'external'-object-handles, e.g. in `VkSurfaceFullScreenExclusiveWin32InfoEXT`
- do not generate overload for `VkPushDescriptorSetWithTemplateInfoKHR`
When making deep copies of structures, avoid attempting to copy the values referenced by opaque handles and opaque pointers. These are generally pointers to a single value with the void* type, which cannot be safely copied because the size of the referenced value is unknown. For most cases, the referenced value is unneeded because capture treats the address stored in these handles/pointers as external object IDs that are encoded as 64-bit integer values.
Additionally omits `VkPushDescriptorSetWithTemplateInfoKHR` from code-gen, as it requires knowledge about the template's layout, which is not available in the routine's …
> Fix vulkan_struct_deep_copy edge-cases

- framework/encode/d3d12_capture_manager.cpp
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_tracker.h
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
**Problem**
During trim capture of some D3D12 apps, some command allocators may be released during state tracking stage, resulting trace replay crash at CreateCommandList() due to null command allocator.
**Solution**
Create temp command allocator for CreateCommandList when it's allocator has been released during state tracking.
> Fix allocator null for trim capture

- framework/decode/struct_pointer_decoder.h
- framework/encode/openxr_capture_manager.cpp
1) Ensure decoded base header children have defined state
The lower level decoders are always setting values, so force a good
state at initialization (zeros)
2) Make view local viewing 1.0 compatible
Convert xrLocateSpaces calls (which are 1.1 only) to xrLocateSpace -- which is available on XR 1.0
> Two bugfixes to enable OpenXR-SDK-Source HelloXr support --api Vulkan

- framework/decode/vulkan_stats_consumer.h
- tools/info/main.cpp
- analogous to graphics- and compute-pipelines
example output:
```
...
Vulkan pipeline info:
Total graphics pipelines: 36
Total compute pipelines: 3
Total raytracing pipelines: 5
...
```
> gfxrecon-info: Report total number of raytracing-pipelines

- framework/encode/api_capture_manager.h
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/custom_dx12_wrapper_commands.h
- framework/encode/custom_vulkan_encoder_commands.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/generated/dx12_generators/dx12_wrapper_body_generator.py
- framework/generated/generated_dx12_wrappers.cpp
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py
The exclusive lock that was intended to be acquired when writing the trimming state snapshot was only acquired when trimming was activated by a present call, where the exclusive lock was always acquired, which also had a negative impact on capture performance. This change makes the following adjustments:
- Acquire the shared lock at present, instead of the exclusive lock.
- Release the shared lock and acquire the exclusive lock when activating trimming.
- Acquire the exclusive lock when trimming is activated by API calls other than present.
> Adjust trimming state snapshot locking

- framework/decode/custom_openxr_struct_decoders.cpp
- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_openxr_api_call_encoders.cpp
- framework/encode/custom_openxr_encoder_commands.h
- framework/encode/custom_openxr_struct_encoders.cpp
- framework/generated/generated_openxr_replay_consumer.cpp
- framework/generated/generated_openxr_replay_consumer.h
- framework/generated/openxr_generators/gencode.py
- framework/generated/openxr_generators/openxr_replay_consumer_body_generator.py
Implements #1721.
Decoders
- XrVulkan*CreateInf::flags decode fixes
Replay
- Vulkan Replay Consumer
- Add physical device alias support Set/Get
- Includes DRY refactor for GetVkObject
- Add getter for GIPA
- Refactor CreateInstance and CreateDevice for reuse by OpenXR
- OpenXr
- Implement CreateVulkan* functions
- Add xrGetVulkanGraphicsDevice2KHR support
Encoders
- Add physical_device enumeration to xrGetVulkanGraphicsDevice2KHR
- Fix systemID encoding
> Add support for xrCreateVulkan(Instance|Device)

- framework/generated/generated_vulkan_struct_deep_copy.cpp
- framework/generated/vulkan_generators/vulkan_struct_deep_copy_body_generator.py
- affects `VK_EXT_descriptor_buffer`, `VK_EXT_device_generated_commands`
> Handle non-sType union-members in vulkan_struct_deep_copy

- framework/decode/custom_openxr_struct_decoders.cpp
- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/custom_openxr_api_call_encoders.cpp
- framework/encode/custom_openxr_encoder_commands.h
- framework/encode/custom_openxr_struct_encoders.cpp
- framework/generated/generated_openxr_replay_consumer.cpp
- framework/generated/generated_openxr_replay_consumer.h
- framework/generated/openxr_generators/gencode.py
- framework/generated/openxr_generators/openxr_replay_consumer_body_generator.py
Implements #1721
Decoders
- XrVulkan*CreateInfo::flags decode fixes
Replay
- Vulkan Replay Consumer
- Add physical device alias support Set/Get
- Includes DRY refactor for GetVkObject
- Add getter for GIPA
- Refactor CreateInstance and CreateDevice for reuse by OpenXR
- OpenXr
- Implement CreateVulkan* functions
- Add xrGetVulkanGraphicsDevice2KHR support
Encoders
- Add physical_device enumeration to xrGetVulkanGraphicsDevice2KHR
- Fix systemID encoding
> Redo of  xr createinstance and device

- framework/encode/capture_manager.cpp
- avoids segfault on macOS15/Release recaptures
> Add a check for empty env_var-string

- framework/decode/vulkan_replay_consumer_base.cpp
Hello !
Because of an error I made in #1478 features supported by the replaying device were not compared anymore to features requested by the capture when `--remove-unsupported` was not present.
This commit simply fixes it.
> Fix features no longer checked at device creation

- framework/decode/dx12_object_info.h
- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/dx12_api_call_encoders_body_generator.py
- framework/generated/dx12_generators/dx12_base_generator.py
- framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
- framework/generated/dx12_generators/dx12_wrapper_body_generator.py
- framework/generated/generated_dx12_api_call_encoders.cpp
- framework/generated/generated_dx12_replay_consumer.cpp
- framework/generated/vulkan_generators/base_generator.py
This PR adds D3D12 replay support for adjusting the size of the memory allocated for variable length output array parameters to match the actual size reported at replay, which may be different than the size reported at capture.  It is based on the implementation of an existing Vulkan replay feature providing the same functionality.
A simple way to test this change is to find an application that calls IDXGIOutput::GetDisplayModeList and make a capture of it running through a remote desktop session. Then replay the capture on the local device. Fewer values will be reported for the remote desktop session than the local session. With this change, replay will report something similar to:
> [gfxrecon] INFO - Replay adjusted the IDXGIOutput::GetDisplayModeList array count: capture count = 1, …
> Adjust output array sizes for D3D12 replay

- CMakeLists.txt
- framework/decode/vulkan_cpp_structs.cpp
- macOS 14.7, clang-1500.3.9.4
fixes warnings:
```
warning: enumeration value 'VK_INDIRECT_EXECUTION_SET_INFO_TYPE_MAX_ENUM_EXT' not handled in switch [-Wswitch]
warning: 11 enumeration values not handled in switch: 'VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXT', 'VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXT', 'VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXT'... [-Wswitch]
```
those warnings were not treated as errors but should have? fyi @bradgrantham @MarkY-LunarG
> MacOS: Fix compiler-warning about missing switch-cases

- USAGE_android.md
- tools/replay/android_main.cpp
Currently --pbi-all --pbis options are not available on android.
This change adds the android support.
> Add print block info option on android

- framework/decode/vulkan_replay_consumer_base.cpp
When the capture result was `VK_SUBOPTIMAL_KHR` and that the replay result is `VK_SUCCESS`, no warning message should be displayed.
> Don't display warning message for `VK_SUCCESS` over `VK_SUBOPTIMAL_KHR`

- framework/encode/vulkan_state_tracker.cpp
Ran into a case where an app did:
`vkGetPhysicalDeviceQueueFamilyProperties()` to get the count
`vkGetPhysicalDeviceQueueFamilyProperties()` with the count
`vkGetPhysicalDeviceQueueFamilyProperties()` with 1
And we just stored the 1.
> Fix tracking queue family properties

- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/file_transformer.cpp
- framework/decode/file_transformer.h
Remove two FileProcessor functions that aren't used and bring the member variable they referenced into the one function that used that member.
(Help to simplify #1644)
> remove unused FileProcessor functions and simplify file_header usage

- framework/encode/vulkan_state_tracker.h
`VkPipelineBinaryHandlesInfoKHR` contains a dynamic array and must be handled differently. 
Currently any attempt to call `vkCreatePipelineBinariesKHR` would assert in `AddStructGroupEntry`.
> Add missing pipeline binaries struct entry

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/dx_replay_options.h
- framework/decode/openxr_feature_util.cpp
- framework/decode/openxr_feature_util.h
- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_options.h
- framework/decode/replay_options.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- tools/tool_settings.h
Move some replay options into the base class for sharing among all the paths.  Update the OpenXR replay options to be read during replay execution.
Remove unknown extensions if the replay option is enabled.
> openxr: Disable replay w/ unknown extensions

- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
Some dump resources files being created did not start with the capture file name. This PR fixes that.
> dump resources: Fix output filename for dispatch dump

- android/framework/encode/CMakeLists.txt
- framework/decode/api_decoder.h
- framework/decode/file_processor.cpp
- framework/decode/metadata_consumer_base.h
- framework/decode/vulkan_decoder_base.cpp
- framework/decode/vulkan_decoder_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/CMakeLists.txt
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_device_address_tracker.cpp
- framework/encode/vulkan_device_address_tracker.h
- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/format/format.h
- Extend capture/tracking to cover acceleration-structures (AS) and dependencies
- Add meta-commands to rebuild AS during replay
- create all stubs in replay, implement in follow-up
this PR belongs to [portable raytracing initiative](https://github.com/LunarG/gfxreconstruct/issues/1526)
> Add acceleration structure meta-commands

- framework/encode/custom_dx12_wrapper_commands.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_tracker.h
- framework/encode/dx12_state_writer.cpp
**Problem**
Trimmed traces did not replay in HDR mode, but full ones do.
**Solution**
Track `SetColorSpace1` and `SetHDRMetaData` during capture if trimming is enabled. Then write it out to file so that replay can properly setup HDR as it was during live app.
**Testing**
Trimmed trace replays in HDR mode.
> Save swapchain HDR state for trimmed captures

- framework/encode/dx12_state_tracker.cpp
`CreateCommandList1` creates a command list without an allocator so `pCommandAllocator` is nullptr in
`Dx12StateTracker::TrackCommandListCreation`
> Fix crash in CreateCommandList1 when trimming

- framework/decode/custom_ags_replay_consumer.cpp
- framework/decode/custom_ags_replay_consumer.h
Application could create multiple AGS contexts.
But only use one of them to create device.
GFXR have to track the contexts.
> Support Multiple AGS contexts

- framework/encode/vulkan_capture_manager.h
page guard buffers are aligned when the kUserfaultfd mode is enabled
> page guard buffers are aligned when the kUserfaultfd mode is enabled

- framework/decode/custom_ags_replay_consumer.cpp
**Problem**
The `-gpu` option was always selecting GPU 0 when replaying an AGS capture
**Solution**
When creating an AGS device, make the AGS replay consumer honor the adapter coming from `GetAdapter()`
**Testing**
Replaying an AGS trace with `-gpu 1` for example ran on the correct GPU
> Have AGS device creation honor desired adapter

- tools/info/main.cpp
**Problem**
If there are multiple of the same GPUs on a system, using info tool to identify the right GPU isn't straight forward
**Solution**
Expose `SubSysId` beside each enumerated adapter. For some reason DXGI is showing the same adapter twice, so with this change we can identify their uniqueness.
**Testing**
Before (2-GPU system):
```
GPU index       GPU name
0               AMD Radeon RX 7900 XTX
1               AMD Radeon RX 7900 XTX
2               AMD Radeon RX 7900 XTX
3               Microsoft Basic Render Driver
```
After (2-GPU system):
```
GPU index       GPU name                        SubSysId
0               AMD Radeon RX 7900 XTX          123456
1               AMD Radeon RX 7900 XTX          ABCDEF
2               AMD Radeon RX 7900 XTX          123456
3 …
```
> Have info tool expose SubSysId during GPU enumeration

- framework/decode/vulkan_replay_consumer_base.cpp
Retry when capture was `SUCCESS` and replay is `NOT_READY`. Continue in all other cases, including when capture was `NOT_READY` and replay is `SUCCESS`.
Might solve #1800 as well?
> Fix vkGetQueryPoolResults timeout loop

- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
When the replay --use-cached-psos option is not specified, clear the cached PSO data from the ID3D12Device2::CreatePipelineState parameters, similar to what is currently done for the ID3D12Device CreateComputePipelineState and CreateGraphicsPipelineState methods.
> Clear CachedPSO data for CreatePipelineState replay

- framework/decode/dx_replay_options.h
- framework/decode/replay_options.h
- framework/decode/struct_pointer_decoder.h
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/encode/api_capture_manager.h
- framework/encode/capture_manager.h
- tools/replay/android_main.cpp
- tools/tool_settings.h
Add needed decoder and interface extensions
Add interface to get/set capture mode
Expose dispatch table getters
Add initialize to StructPointerDecoder allocation
Add vulkan guard to consumer and decode variables
Split OverrideCreateInstance/Device
Add VkPhysicalDevice aliasing support
Reorganize common options
Not sure if these will interfere with @panos-lunarg  pending changes, will wait if needed
> A handful of interface changes to support OpenXR future rebasing

- framework/util/page_guard_manager.cpp
- framework/util/page_guard_manager.h
Install page guard signal handler using AddSpecialSignalHandlerFn from the libsigchain in the Android runtime. This prevents traced applications from replacing our signal handler when they try to install thier own signal handlers with sigaction.
> Use libsigchain on Android

- framework/encode/vulkan_state_tracker.cpp
#1644 modified `VulkanStateTracker::TrackUpdateDescriptorSetWithTemplate` but this assert was left unchanged
> Fix descriptor info assert during capture

- android/framework/util/CMakeLists.txt
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/replay_overrides.json
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- framework/graphics/vulkan_device_util.cpp
- framework/graphics/vulkan_device_util.h
- framework/graphics/vulkan_shader_group_handle.h
- framework/util/CMakeLists.txt
- framework/util/hash.h
- framework/util/linear_hashmap.h
- framework/util/test/test_linear_hashmap.cpp
- various changes to state-writer: always provide shader-group-handles
- track bound pipelines in replay, retrieve map of old/new handles in CmdTraceRays
- Add a generic murmur32-implementation to util/hash.h
- Add a 'linear hashmap' type (cpu-flavor), populate with handles
- Add unit-test for linear_hashmap
next in follow-up:
- TODO: linear hashmap gpu-flavor
- TODO: run compute-shader over SBT, replace handles (in-place / shadow-buffer)
this PR belongs to https://github.com/LunarG/gfxreconstruct/issues/1526
> ShaderGroupHandles: tracking/trimming

- .github/workflows/ci_build.yml
Enable running tests in GitHub CI by removing `--skip-tests` from `build.py` command lines.
> Also run unit tests in GitHub CI

- framework/encode/vulkan_state_tracker.cpp
The DestroyState() overrides added by 1644 should also do what the default DestroyState is doing. This patch should address this omission
> Fixes for newly added VulkanStateTracker::DestroyState

- framework/generated/generated_vulkan_cpp_structs.cpp
- framework/generated/vulkan_generators/vulkan_cpp_struct_generator.py
Fix invalid conversion errors by casting argument values to their target
platform full types. This fixes compilation issues for code like this:
```cpp
VkWaylandSurfaceCreateInfoKHR waylandSurfaceCreateInfoKHR_17 {
VkStructureType(1000006000),
NULL,
VkWaylandSurfaceCreateFlagsKHR(0),
0,
0x2000000,
};
```
which compiled with g++ 14.2.1 20240912 yields this:
```
src/frame_0000_0000.cpp:132:25:
error: invalid conversion from ‘int’ to ‘wl_surface*’ [-fpermissive]
```
> tocpp: Cast values to platfrom full types

- framework/decode/vulkan_cpp_consumer_base.cpp
- framework/decode/vulkan_cpp_loader_generator.cpp
- framework/decode/vulkan_cpp_template_strings.h
- framework/decode/vulkan_cpp_utilities.h
- tools/tocpp/README.md
I had a look at _tocpp_, noticed there was no wayland support, so I added it. Quite an easy task thanks to [the wayland book](https://wayland-book.com/xdg-shell-basics/example-code.html).
> tocpp: Support wayland

- android/framework/encode/CMakeLists.txt
- framework/encode/CMakeLists.txt
- framework/encode/vulkan_capture_common.cpp
- framework/encode/vulkan_capture_common.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
> Combine common code from vulkan capture manager and vulkan state writer

- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/decode/openxr_replay_session_state.cpp
- framework/decode/openxr_replay_session_state.h
- framework/decode/openxr_replay_swapchain_state.cpp
- framework/decode/openxr_replay_swapchain_state.h
Whether the OpenXR swapchain is explicitly or implicitly destroyed.
Resolves #1718
> openxr: Clean Vulkan virtual swapchain on destroy

- framework/decode/vulkan_resource_allocator.h
Here's my attempt at simplifying the `VulkanResourceAllocator` interface by extracting `*Direct` functions into a separate class `VulkanDirectAllocator`.
This is one option: `VulkanResourceAllocator` subclasses, just need to implement `GetDirectAllocator()`.
Currently, `VulkanDirectAllocator` is just a copy of `VulkanDefaultAllocator`. If we want to keep it decoupled by the other allocators, it can evolve separately.
Another option might be having `VulkanDirectAllocator` accept a pointer to the concrete allocator, and make all direct functions forward their arguments to the concrete allocator. E.g.:
```c++
class VulkanDirectAllocator {
VulkanResourceAllocator& alloc_;
VkResult CreateBuffer(const VkBufferCreateInfo*    create_info,
const VkAllocationCallbacks* allocation_callbacks, …
```
> Add VulkanDirectAllocator

- framework/decode/screenshot_handler.cpp
Report the memory map failure by logging the error, as the screenshot is not generated.
Closes #1853
> screenshot: Print message on memory map failure

- framework/encode/custom_dx12_wrapper_commands.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
IDXGISwapChain::ResizeTarget will resize the window associated with the swapchain. If the window has an event callback, the callback will be invoked for a resize event before ResizeTarget returns. Any API calls made by the callback will not be processed for capture due to the current scope count, resulting in a capture file that will not replay correctly due to missing API calls. The scope count needs to be decremented prior to the call and resotored after the call to ensure that API calls made by the callback are captured.
> Fix IDXGISwapChain::ResizeTargets capture

- framework/decode/dx12_replay_consumer_base.cpp
The value returned by IDXGISwapchain::GetBuffer should only be processed as an ID3D12Resource type if the caller requested an ID3D12Resource.
> Fix OverrideGetBuffer resource handling

- android/framework/decode/CMakeLists.txt
- framework/decode/CMakeLists.txt
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/mark_injected_commands.cpp
- framework/decode/mark_injected_commands.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
- tools/replay/CMakeLists.txt
- tools/replay/android_main.cpp
MainGetCurrentBlockIndex and MainGetLoadingTrimmedState whould de discoveralbe through dlopen + dlsym from the android replay native .so:
- MainGetCurrentBlockIndex(): Returns the current block index as calculated from the file processor
- MainGetLoadingTrimmedState(): Returns wheter file processor is between a FrameStateBegin/FrameStateEnd markers pair
> Expose 2 symbols from android_main

- framework/decode/vulkan_replay_consumer_base.cpp
`OverrideCmdBindPipeline` was added recently, but a mandatory synchronization w. asynchronous operations was dropped. that causes race-conditions and bugs when using the `--pipeline-creation-jobs` feature.
this is fixed here. 
note:
this regression also marks the point where we should enforce CI-coverage for that feature.
> Fix a recent regression related to --pipeline-creation-jobs option.

- framework/util/image_writer.cpp
Move data pitch check before opening the file and report an error on
invalid data pitch.
Related to #1853
> util: Fix leak and report error

- framework/decode/vulkan_replay_consumer_base.cpp
- apply changes suggested by clang-tidy, most important `declaration shadows a local variable`
- this fixes a bug in pipeline-destruction (we did not destroy the pipeline)
note:
in other cases we treat warnings as errors, but apparently tolerate variable-shadowing.
I argue we should be more strict about this. it can create nasty and subtle bugs, as seen here.
> Fix a bug in pipeline-destruction

- framework/encode/capture_settings.cpp
When not specified by the user, the iunknwon_wrapping setting was being set to the value of the disable_dxr setting instead of its default value.
> Fix default iunknown_wrapping initialization

- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/khronos_generators/vulkan_generators/vulkan_replay_consumer_body_generator.py
when adding an override to `vkCmdPushConstants` in a [recent PR](https://github.com/LunarG/gfxreconstruct/pull/1879) ,
an error manifested in our generated code, passing a wrong pointer.
this compiled fine because the parameter happened to be a `void`-pointer
this affected the dump-resource feature, when used in combination with `vkCmdPushConstant`.
this is fixed here.
> Fix a regression in dump-resources, related to vkCmdPushConstants

- framework/encode/vulkan_capture_manager.cpp
Shadow memory size must match that in page guard manager, or it can result in oob access when memory is mapped with an offset.
To demonstrate the problem:
```
VkMemoryAllocateInfo memoryAllocateInfo;
memoryAllocateInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
memoryAllocateInfo.pNext = NULL;
memoryAllocateInfo.allocationSize = 65536;
memoryAllocateInfo.memoryTypeIndex = 0; // Host visible
VkDeviceMemory memory;
vkAllocateMemory(vk->device, &memoryAllocateInfo, NULL, &memory);
void* data;
vkMapMemory(vk->device, memory, 32768, 32768, 0u, &data);
```
This currently asserts as index in vector access in page_guard_manager.cpp:1115
`shadow_memory_info->page_loaded[page_index]`
is out of bounds.
Currently shadow memory is only allocated from the mapped size, not the entire memory size. …
> Fix shadow memory size

- framework/encode/api_capture_manager.h
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
Closing the file can allow external users to keep track of when GFXR is done updating the file and therefore is safe to access it.
> Do not keep asset file open

- framework/generated/generated_vulkan_enum_to_json.cpp
- framework/generated/generated_vulkan_enum_to_string.cpp
This is another header update, but the changes are very minor. Regarding GFXR, it looks like the only effect was renaming one enumerant.
> Update Vulkan Headers to v1.4.304

- framework/decode/custom_dx12_replay_commands.h
- framework/decode/dx12_replay_consumer_base.cpp
- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
- framework/generated/dx12_generators/replay_overrides.json
- framework/generated/generated_dx12_replay_consumer.cpp
Map the IDXGIAdapter LUID values recorded at capture to the values retrieved at replay. This addresses a replay crash caused by swapchain creation failure when swapchain creation depends on an adapter retrieved with IDXGIFactory4::EnumAdapterByLuid.
> Fix LUID related replay crash

- framework/decode/custom_vulkan_struct_to_json.cpp
- framework/decode/custom_vulkan_struct_to_json.h
- framework/decode/metadata_json_consumer.h
- framework/decode/vulkan_json_consumer_base.cpp
- framework/decode/vulkan_json_consumer_base.h
I was looking at another issue and noticed the json output for SetDeviceMemoryPropertiesCommand was missing some information.
Here's a sample diff with the new output (with `--expand-flags`):
```diff
@@ -197,11 +197,67 @@
{
"index": 7,
"meta": {
"name": "SetDeviceMemoryPropertiesCommand",
"args": {
-      "physical_device_id": 2
+      "physical_device_id": 2,
+      "memory_types": [
+        {
+          "property_flags": "VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT",
+          "heap_index": 1
+        },
+        {
+          "property_flags": "VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT",
+          "heap_index": 1
+        },
+        {
+          "property_flags": "VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT",
+          "heap_index": 0
+        },
+        {
+ …
```
> Add missing json fields

- tools/replay/desktop_main.cpp
initialize quit_frame and avoid a VSCode assertion in debug
> initialize quit_frame

- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
VMA does not support external memory. If memory is allocated with AHardwareBuffer we must manually allocate it in rebind
> Fix importing AHB memory with rebind

- framework/encode/vulkan_capture_manager.cpp
From the spec:
> If a VkPipelineBinaryInfoKHR structure with a binaryCount greater than 0 is included in the pNext chain of any Vk*PipelineCreateInfo structure when creating a pipeline, implementations must use the data in pPipelineBinaries instead of recalculating it. Any shader module identifiers or shader modules declared in VkPipelineShaderStageCreateInfo instances are ignored.
> Fix shader wrapper assert when pipeline binaries are used

- framework/decode/custom_ags_replay_consumer.cpp
- framework/decode/dx12_replay_consumer_base.h
The D3D12 device could be created by AGS calls.
So the device info structure have to be set as well.
> Initialize Device Info From AGS

- framework/decode/vulkan_default_allocator.cpp
- framework/decode/vulkan_default_allocator.h
- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_resource_allocator.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/khronos_generators/vulkan_generators/replay_overrides.json
- framework/generated/khronos_generators/vulkan_generators/vulkan_replay_consumer_body_generator.py
When using rebind allocator, lazy allocation make it impossible to have a valid Vulkan handle before binding memory. However, it remains possible to set name and tag of the memory before binding it.
These informations should thus be stored in the allocator, and the appropriate call emitted once the memory is actually allocated.
In addition, even without this lazy allocation issue, only a "fake" handle is stored in `DeviceMemoryInfo`, making it impossible to use even after binding time.
This is what this commit aims to fix.
> Fix `vkSetDebugUtilsObjectNameEXT` and `vkSetDebugUtilsObjectTagEXT` for `VkDeviceMemory` objects when using rebind allocator.

- tools/replay/parse_dump_resources_cli.cpp
Ran into this attempting to run some tests - if the specified dump-resources file does not exist, it's reported as a parse error.  If it actually was not opened, print something more specific.
> if file was not opened, say so

- framework/util/spirv_helper.h
We should be using 1.4.304, and especially for the `vulkan-1.4.304.0` branch.
> Update SPIR-V Headers to 1.4.304

- framework/application/android_window.cpp
- framework/application/android_window.h
- framework/application/display_window.cpp
- framework/application/display_window.h
- framework/application/headless_window.cpp
- framework/application/headless_window.h
- framework/application/metal_window.h
- framework/application/metal_window.mm
- framework/application/wayland_window.cpp
- framework/application/wayland_window.h
- framework/application/win32_window.cpp
- framework/application/win32_window.h
- framework/application/xcb_window.cpp
- framework/application/xcb_window.h
- framework/application/xlib_window.cpp
- framework/application/xlib_window.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/decode/vulkan_virtual_swapchain.h
- framework/decode/window.h
This commit partially fix issue #759 
Fix a crash on `VK_ERROR_OUT_OF_DATE_KHR` when the window of the replayer cannot be resized to the size of the swapchain at capture time and that the replayer uses virtual swapchain.
The idea is to store the actual size of the window that could be opened at replay time in the virtual swapchain so that the virtual swapchain has the same size as at capture time, and the actual swapchain is the size of the window. When the image is copied from the virtual image to the actual image, only a sub-part of the image is copied.
> Fix crash when window cannot be opened with same resolution

- framework/encode/custom_vulkan_encoder_commands.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_handle_wrapper_util.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
The implementation is allowed to destroy and reuse handles for non-acquired swapchain images as soon as the parent swapchain is retired. Update the handle tracking logic to treat these handles as destroyed, so that if they are reused, we don't get collisions in the handle tables.
Android is particularly sensitive to this as it will often immediately reuse image handles from retired swapchains, even before the retired swapchain is destroyed.
> Remove retired swapchain images immediately

- framework/decode/vulkan_address_replacer.cpp
- Add missing check for zero-sized address-regions
- Fix for shader-binding-table assembly when using multiple miss- and/or hit-groups
> Portable RT: Fixes for shader-binding-table assembly

- framework/util/spirv_parsing_util.cpp
- framework/util/spirv_parsing_util.h
this is relevant for raytracing applications, which use extra data in shader-binding-tables. 
-> https://docs.vulkan.org/spec/latest/chapters/raytracing.html#shader-binding-table
this fixes the symptom of spamming `Storage class 5343 not handled`
> Add missing StorageClassShaderRecordBufferKHR to spirv-parser

- framework/decode/vulkan_stats_consumer.h
- tools/info/CMakeLists.txt
- tools/info/main.cpp
gfxrecon-info reports resolutions used in vulkan traces based on data provided in vkCreateSwapchainKHR and vkCreateSharedSwapchainsKHR calls.
Sample output:
```
Exe info:
Application exe name: 
Application version: 0.0.0.0
Application Company name: 
Product name: 
File info:
Compression format: LZ4
Total frames: 11
Application info:
Application name: ray_queries
Application version: 0
Engine name: Vulkan Samples
Engine version: 0
Target API version: 4198400 (1.1.0)
Used resolutions: 1280x720
Physical device info:
Device name: NVIDIA GeForce RTX 2060
Device ID: 0x1e89
Vendor ID: 0x10de
Driver version: 2181955968 (0x820e0180)
API version: 4206797 (1.3.205)
Device memory allocation info:
Total allocations: 12
Min allocation size: 3932160
Max allocation size: 134217728
Pipeline info:
Total …
```
> Add used resolutions info

- android/scripts/gfxrecon.py
Added a check whether the ANDROID_SERIAL was set.
This change is needed as when more than one device is connected, the script crashes if the selection is not explicitly specified. This change makes the error message more transparent and suggests the way to fix it.
> Check whether ANDROID_SERIAL was set when working with multiple devices

- cmake/FindDXC.cmake
extend CMP0135 to CMake 3.24 and remove directive causing an issue
> Fix issues building without tests on CMake 3.22

- framework/application/application.cpp
- tools/replay/android_main.cpp
It makes more sense to have messages for both when the application is paused and unpaused than only when paused.
In addition, in the context of an automated process, it is useful to be able to differentiate, only with the logs, an application that was paused because of a manual input to an application paused because of a lose of focus.
This commit adds these log messages
> Add log message on app gain/loss of focus and when unpausing application

- android/framework/encode/CMakeLists.txt
- android/framework/util/CMakeLists.txt
- framework/decode/vulkan_default_allocator.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_initializer.cpp
- framework/encode/CMakeLists.txt
- framework/encode/api_capture_manager.h
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/command_writer.cpp
- framework/encode/command_writer.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/graphics/vulkan_struct_get_pnext.h
- framework/util/CMakeLists.txt
- framework/util/file_output_stream.h
- framework/util/output_stream.h
- framework/util/thread_data.cpp
- framework/util/thread_data.h
Initial support for VK_KHR_external_memory_fd.
Capture: once a device memory imported from external FD is bound to a buffer, an InitBuffer command is generated with the current content of the memory.
Replay: the import memory FD structure is removed from the pNext chain of `VkMemoryAllocateInfo`, and the initial content of the buffer is initialized through the InitBuffer command.
It supports images as well!
> External memory FD

- framework/decode/vulkan_resource_initializer.cpp
Images with multiple layers cause, from layer 1 and onwards, to use the same image as sampled image and render target at the same time.
> Fix in pixel shader resource init path

- test/test_apps/host-image-copy/app.cpp
- test/test_apps/multisample-depth/app.cpp
- test/test_apps/pipeline-binaries/app.cpp
- test/test_apps/shader-objects/app.cpp
- test/test_apps/triangle/app.cpp
- tools/replay/android_main.cpp
Preserve messages from derived exceptions for more informative logging.
Catching them by value means making a copy of the thrown exception, and if it was actually derived from the type named at the catch point, that will be a slicing copy, throwing away the fields of the derived type which might contain information it uses to provide a helpful `what()` message. Indeed, the virtual `what()` function will resolve to the base class version, returning an empty string in the cases of the test apps.
[Ref: C++ Core Guidelines, E.15: Throw by value, catch exceptions from a hierarchy by reference.](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference)
> Catch Exceptions by Reference to Avoid Slicing

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
Missing variable initialization was causing multiview structure to be added when creating render passes even when there was not multiview in play.
> VDR: Initialize multiview flag

- framework/decode/common_object_info_table.cpp
Fix crash on used cases where multiple replay consumers are created and deleted.
> Fix CommonObjectInfoTable reference count

- framework/util/image_writer.cpp
The mapping from Unorm16 encoded depth images did map half of the range to the max color value, hence causing that the same gray tones were used twice, for values < 0.5 (0x8000 before unorm), or >= 0.5. Fixing the normalization to linearly map the whole range.
> Map depth image in Unorm16 for full range

- framework/encode/vulkan_state_writer.cpp
Add `<chrono>` include to file using std::chrono::high_resolucion_clock to fix the VS 17.13.0 build.
> Include <chrono> for high_resolution_clock

- tools/capture-vulkan/CMakeLists.txt
- tools/capture/CMakeLists.txt
- tools/gfxrecon/CMakeLists.txt
Started getting this warning on CMake 3.31+:
```
CMake Warning (dev) at tools/capture-vulkan/CMakeLists.txt:3 (add_custom_command):
The following keywords are not supported when using
add_custom_command(TARGET): DEPENDS.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
From `cmake --help-policy CMP0175`:
> CMake 3.30 and earlier silently ignored unsupported keywords and missing or
> invalid arguments for the different forms of the ``add_custom_command()``
> command. CMake 3.31 implements more rigorous argument checking and will flag
> invalid or missing arguments …
> Fix CMake warning CMP0175

- framework/decode/dx12_replay_consumer_base.cpp
Gfxr replay redirect CreateSwapChainForComposition to CreateSwapChainForHwnd. But CreateSwapChainForComposition don't have DXGI_SWAP_CHAIN_FULLSCREEN_DESC parameter. So that the replay should handle the case.
> Fix Replay Crash at CreateSwapChainForComposition

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
Make sure messenger_create_info memory is still valid when it goes out of scope since the modified_create_info holds a pointer to it and it needs it when calling the create instance function.
> replay: Fix instance info

- test/test_apps/common/test_app_base.h
This is a small PR to remove the footgun from the test framework's VERIFY_VK_RESULT() macro by ensuring `result` is evaluated only once.
> Macro VERIFY_VK_RESULT no longer evaluates result twice

- framework/encode/custom_dx12_wrapper_commands.h
- framework/encode/d3d12_capture_manager.cpp
- framework/encode/d3d12_capture_manager.h
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_tracker.h
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
Our trimmed traces don't contain object names. This is because we don't restore `SetName()` calls if the app made them.
This PR makes it D3D12 object names are preserved in trimmed traces. Helps to debug.
> Preserve D3D12 object names while trimming

- framework/decode/dx12_replay_consumer_base.h
- framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py
- framework/generated/generated_dx12_replay_consumer.cpp
Add COM pointer array support to the replay consumer code generator:
- Handle output arrays of COM pointers, adding them to the object table.
- Support variable length arrays of output COM pointers.
For the generated replay override code, the `SetConsumerData` call was also moved behind the same `IsNull` conditional check performed for `SetHandleLength`, because the consumer data won't be set when there are no handles to associate it with. This was primarily done for the array of COM objects case, to skip initialization of a vector of objects, but also applies to the single COM object case.
IDXGIDevice::CreateSurface is currently the only function that outputs an array of COM pointers, but this change was pulled from the D3D11 branch where there are multiple D3D11 cases
> Update D3D replay codegen for arrays of COM pointers

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/graphics/vulkan_device_util.cpp
- a change got introduced with https://github.com/LunarG/gfxreconstruct/pull/1955
and influences under which conditions the `rayTracingPipelineShaderGroupHandleCaptureReplay`
is used.
- motivation for that change was a validation-warning/error when replaying with `-m rebind`. 
we now make a different attempt to prevent this.
- this PR reverts behavior and fixes issues with gfxrecon-replay / raytracing on some devices
> Fix: Revert a change affecting RT-feature selection

- framework/encode/dx12_state_tracker.cpp
- framework/encode/dx12_state_tracker.h
Problem:
Game could put input geomtory data into a few of resources instead of one resource.
Solution:
GFXR should locate each resource and its offset, then copy over to stagging buffer.
> BuildAS Input Data In Multi-Resources

- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/decode/vulkan_replay_dump_resources_common.h
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
Min max vertex indices should be initialized to zero when for non indexed draw calls.
> VDR: Fix in vertex buffer offset calculation

- framework/encode/d3d12_capture_manager.cpp
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
Problem:
Application might release heap before it release PlacedResource.
Solution:
GFXR should discard all invalid resource while dump resource.
> Skip Invalid PlacedResource

- framework/decode/common_handle_mapping_util.h
- framework/decode/vulkan_address_replacer.cpp
- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_object_info_table_base.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
changes to pipeline handle-synchronization when using async compilation.
- fixes issues in combination with `-m rebind` option and address-replacement
- fixes validation-errors for pipeline-handle leaks when using asynchronous pipeline-compilation (`--pcj X`)
- found and removed some dead code
- added debug-labels to internal VkPipelines in VulkanAddressReplacer during debugging
to reproduce the reported issue with address-replacement this sample can be used:
https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/ray_tracing_reflection
`gfxrecon-replay -m rebind --pcj -1 ray_tracing_reflection.gfxr`
> Fix issues around async pipeline-handle assignment/cleanup

- framework/encode/vulkan_state_tracker.cpp
during capture we store buffer-contents of last used input-buffers (triangle/aabb/instance/transform) to `vkCmdBuildAccelerationStructures`. 
we also store contents of scratch-buffers, which is not necessary and removed here.
> Do not track contents of AccelerationStructure scratch-buffers

- framework/decode/referenced_resource_table.cpp
- framework/decode/referenced_resource_table.h
- framework/decode/vulkan_referenced_resource_consumer_base.cpp
- framework/decode/vulkan_referenced_resource_consumer_base.h
Device addresses can end up in places where the optimizer cannot (currently) detect and as a result can optimize out buffers that are actually used by an application.
> Optimizer: Mark all buffers targets of GetBufferDeviceAddress as used

- tools/convert/main.cpp
- tools/tool_settings.h
Frame range option allows to only retrieve relevant data and reduce waiting time, especially useful for  bigger traces
Change-Id: I3b7298a20c41d2c67a59069ddf31961f37a3b12d
> Added Frame Range Option to Convert Tool

- framework/decode/dx12_object_info.h
- framework/decode/dx12_resource_value_mapper.cpp
- framework/graphics/dx12_resource_data_util.cpp
**Problem:**
If both of MaxCommandCount and CountBuffer are valid, the actual number of operations to be performed are defined by the minimum of them. But GFXR only takes the value from CountBuffer.
**Solution:**
Track the MaxCommandCount value, once resource value mapping GFXR should compare the two values and take the minimum one.
> Handle ExecuteIndirect MaxCommandCount

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- surfaced together with either dump-resources or `-m rebind`
- Re-add the count-member to decode::VulkanDescriptorSetLayoutInfo::DescriptorBindingLayout
- Restores behavior: Resize inline-uniform-block arrays appropriately
one of the symptoms, we started hitting an assert here:
https://github.com/LunarG/gfxreconstruct/blob/223a12fc10bb295ad3d365d304b539044a13c222/framework/decode/vulkan_replay_consumer_base.cpp#L10022
to reproduce the issue this example can be used: https://github.com/SaschaWillems/Vulkan/blob/master/examples/inlineuniformblocks/inlineuniformblocks.cpp
> Fix a regression when using inline-uniform-blocks

- framework/encode/vulkan_capture_manager.cpp
Check for null before accessing the wrapper of
VkBindImageMemoryInfo::memory.
Fixes #2091
> Null pointer dereference in BindImageMemory2

- layer/trace_layer.cpp
Removes compiler warning from our "strict" environment.
Probably better code generation too!
> Change loop iterator var to const ref

- framework/decode/vulkan_address_replacer.cpp
- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/graphics/vulkan_resources_util.cpp
- framework/graphics/vulkan_resources_util.h
- framework/util/compressor.h
- framework/util/lz4_compressor.cpp
- framework/util/lz4_compressor.h
- framework/util/zlib_compressor.cpp
- framework/util/zlib_compressor.h
- framework/util/zstd_compressor.cpp
- framework/util/zstd_compressor.h
Instead of sequentially processing image/buffer-copies (each time doing a queue-submit + sync),
we can batch them together using a provided target-size for a combined staging-buffer.
This can drastically reduce the number of queue-submissions and improves scalability 
when processing larger quantities of textures and/or buffers.
The target-size for staging-buffers is set to `min(128Mb, total_num_staging_bytes)`, which might increase
memory-footprint during state-writes (don't think this a problem).
additional:
- Add debug-lables to internal resources in VulkanResourceUtil via `vkSetDebugUtilsObjectNameEXT`
- Remove dead code in VulkanResourcesUtil
- Add a nullptr check in VulkanAddressReplacer
- Add const-qualifiers to util::Compressor's API
> Batch queue-submissions in ProcessBufferMemory / ProcessImageMemory

- framework/application/application.cpp
- framework/application/metal_window.mm
- framework/decode/vulkan_address_replacer.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_delegate.h
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_resource_tracking_consumer.cpp
This prevents errors with CLANG in strict
environments e.g. "warnings as errors"
> Reorder Member Variable Initializers

- framework/generated/generate_vulkan.py
- framework/generated/generated_vulkan_pnext_struct_decoder.cpp
Since 7d0801210f5fc43e2a6dcbd46bf57466ece550cd, the file was not
properly generated.
> generate_vulkan: fix typo for pnext_struct_decoder

- framework/decode/vulkan_address_replacer.cpp
- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
- framework/graphics/vulkan_resources_util.cpp
- framework/graphics/vulkan_resources_util.h
- framework/util/compressor.h
- framework/util/lz4_compressor.cpp
- framework/util/lz4_compressor.h
- framework/util/zlib_compressor.cpp
- framework/util/zlib_compressor.h
- framework/util/zstd_compressor.cpp
- framework/util/zstd_compressor.h
Reverts LunarG/gfxreconstruct#2089
We discovered incorrect results from screenshots from replaying trimmed captures in a recent Release build extended testing run.  Running trimmed capture of some tests in Debug build indicates an assertion which would not have fired in Release.
> Revert "Batch queue-submissions in ProcessBufferMemory / ProcessImageMemory"

- framework/encode/capture_settings.cpp
Currently most capture settings are shared between platforms, yet some definitions used for processing settings are still separated. 
This code duplication is unnecessary, adding new capture settings requires developers to define the same setting twice - for android and desktop separately, which is easy to miss.
This change creates a section for settings shared between android and desktop and a separate section for the few android-specific capture settings.
> Unify capture settings definitions

- framework/graphics/fps_info.cpp
- framework/graphics/fps_info.h
- framework/util/date_time.h
- tools/replay/android_main.cpp
- tools/replay/desktop_main.cpp
Having uniform/standardized log formats/behaviors allow for automation tools to be easier to implement and maintain.
As the measurements done by GFXReconstruct are performance free and were already done on the whole replay if no frame-range was specified, I propose to consider `gfxrecon-replay` as always acquiring measurements, either on the whole replay or on the specified frame-range.
Thus there is no need for special message/behavior depending if a frame-range has been manually specified. That's what this commit implements:
- A measurement file is always created if the replay has been run successfully
- The same log message at the end of the replay is displayed, no matter if a range has been specified or not and no matter how much time the (potentially non-existant) load has taken
In …
> Uniform behavior for measurements in `FpsInfo`

- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/encode/vulkan_state_tracker_initializers.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/khronos_generators/vulkan_generators/capture_overrides.json
- framework/generated/khronos_generators/vulkan_generators/vulkan_api_call_encoders_body_generator.py
From the spec:
> pInheritanceInfo is a pointer to a VkCommandBufferInheritanceInfo structure, used if commandBuffer is a secondary command buffer. If this is a primary command buffer, then this value is ignored.
This would crash if pInheritanceInfo is pointing to invalid memory.
> Fix crash in vkBeginCommandBuffer

- framework/decode/vulkan_resource_initializer.cpp
- framework/decode/vulkan_resource_initializer.h
Instead of uploading each resource with a separate queue submission,
batch several resources into a larger staging buffer and upload them
with a single queue submit
> Batch resources initialization

- framework/generated/khronos_generators/khronos_api_call_encoders_generator.py
- framework/generated/khronos_generators/vulkan_generators/vulkan_api_call_encoders_body_generator.py
Derived classes shouldn't be required to define variable needed by functional mixins, but instead they should be passed, or defined (at least as empty) in a base class.
No change to generated code.
> codegen: Refactor check_write/make multi-api safe

- framework/decode/decode_json_util.cpp
When a `PointerDecoder` didn't contain any value (because it was a nullptr) the value was still read by `FieldToJson` and written to the output of `gfxrecon-convert`.
The reason to that bug is that the test was:
```
if (len > 1)
output a JSON array
else
output a JSON integer
```
leaving begind the case where `len` is `0`.
This commit fixes this issue by implementing the same condition as in `HandleToJson` for `HandlePointerDecoder`.
For the following struct:
```
{
int* x = {1, 2, 3};
int* y = {1};
int* z = nullptr;
}
```
The output was:
```
{
"x": [1, 2, 3],
"y": 1,
"z": some garbage value
}
```
The output is now:
```
{
"x": [1, 2, 3],
"y": [1],
"z": null
}
```
> Fix JSON conversion of `PointerDecoder`

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/util/logging.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
Resolves #2112 
`DebugUtilsCallback` will silently omit messages that don't set `pCallbackData->pMessageIdName`. This causes an issue with layers that don't set that field, such as RenderDoc
This PR makes the function print `(nullptr)` in place of `pCallbackData->pMessageIdName` when it is null.
Additionally, this PR unconditionally registers the debug callback so that messages from layers are displayed even when the captured app didn't set the debug callback, and sets the callback severity based on a new option `--debug-messenger-level`
> Resolve issues around DebugUtilsCallback()

- BUILD.md
- CMakeLists.txt
- android/layer/CMakeLists.txt
- android/layer/build.gradle
- android/test/test_apps/triangle/build.gradle
- android/tools/quest_replay/CMakeLists.txt
Two commits:
```
openxr: Add ability to disable OpenXR in gradle
Add the ability to disable OpenXR when building the GFXR layer
in Gradle.
Also add some better error messages.
```
```
Fix android test build with Gradle
The build failed for me because some components were built with
AndroidX packages and others were not.
```
> Marky fix disable openxr

- android/tools/multi-win-replay/src/main/com/lunarg/gfxreconstruct/replay/ReplayActivity.java
- framework/application/android_jni.cpp
- framework/application/android_window.cpp
This commit fixes two bugs.
The first is a simple forgotten call to `ANativeWindow_release` on window destruction.
The second is a synchronization issue in the Java code: During window recreation, a destroy call and a create call closely follow each other. Each of these calls is sent to the UI thread, that will then trigger the callbacks `surfaceDestroyed` and `surfaceCreated` later.
If the call to `addNewView` happens before the UI thread calls `surfaceDestroyed`, then `mSurface` is set to the destroyed surface (which is not null), which allows `addNewView` to return with the incorrect surface set, which results in a failed surface recreation.
I propose to solve this bug by simply not setting `mSurface` in `surfaceDestroyed` and `surfaceChanged` callbacks, as `mSurface` is exclusively …
> Fix Android multi-window surface recreation

- framework/decode/vulkan_replay_consumer_base.cpp
Set debug-messenger messageType to `VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT`
Fixes a validation-warning during init when using `--validate`:
```
Validation Error: [ VUID-VkDebugUtilsMessengerCreateInfoEXT-messageType-parameter ] | MessageID = 0xdf09e3a0
vkCreateDebugUtilsMessengerEXT(): pCreateInfo->messageType contains flag bits (0x7fffffff) which are not recognized members of VkDebugUtilsMessageTypeFlagBitsEXT.
```
> Fix validation-warning when initializing debug-messenger

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_options.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/khronos_generators/vulkan_generators/replay_overrides.json
- tools/tool_settings.h
- Move debug messenger object to InstanceInfo and clean it up during vkDestroyInstance to fix validation error
- Mark debug message create/destroy calls as injected commands
- Set default debug messenger severity to error OR warning (most validation messages will come as error)
- Make each `--debug-messenger-level` level include prior levels (similar to our logging option)
- Add `--debug-messenger-level` to docs and `android/scripts/gfxrecon.py`
> Misc debug messenger fixes

- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.h
Fix different crashes:
- implement missing support for `VK_KHR_imageless_framebuffer` in dump-resources 
- handle (legit) nullptrs (from spec: `pStrides is NULL or a pointer to an array of buffer strides`)
> Fix crashes when using --dump-resources

- framework/decode/struct_pointer_decoder.h
One-liner correcting index to match inner loop.  Affect all 2D Array decodes.
> decode: Fix inner loop index for 2D array decode

- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
Currently the image aspect for copy operation is hardcoded as VK_IMAGE_ASPECT_COLOR_BIT. This can casue issues with processing depth and stencil data. This commit fixes the problem for single-planar formats by resolving aspect based on image format.
> Resolve image aspect in rebind allocator resource initialization

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
PR #2188 cleaned up the internal replay messenger, but only in cases where there was a replayed `vkDestroyInstance` call. This change moves the cleanup into a helper so it can be done both when replaying `vkDestroyInstance` and when cleaning up live objects in the `VulkanReplayConsumerBase` destructor.
> Always clean up internal debug messenger

- framework/decode/vulkan_address_replacer.cpp
- (when using `-m rebind`) this affected VulkanAddressReplacer::UpdateAddresses()
> Correct enum in barrier, fix a validation-warning

- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
Use correct vertex-input data when using `VK_DYNAMIC_STATE_VERTEX_INPUT_EXT`
- retrieve information about dynamic_vertex_input from optional `VkPipelineLibraryCreateInfoKHR`
> Dump-Resources: Fix empty vertex-buffers

- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
the root-cause 'could' be related to `VK_EXT_multisampled_render_to_single_sampled` being used.
as first step, just try not to crash:
- Change a check/assert to an if-condition, avoid nullptr dereference
> Fix dump-resource crash wrt. missing depth

- framework/decode/openxr_replay_consumer_base.cpp
- framework/decode/openxr_replay_consumer_base.h
- framework/generated/generated_openxr_replay_consumer.cpp
- framework/generated/generated_openxr_replay_consumer.h
- framework/generated/khronos_generators/openxr_generators/gencode.py
- framework/generated/khronos_generators/openxr_generators/openxr_replay_consumer_body_generator.py
Handle a different amount of display rates returned in the replay from the capture for the xrEnumerateDisplayRefreshRatesFB command.
> Handle xrEnumerateDisplayRefreshRatesFB incomplete

- framework/application/android_window.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
We currently assume identity orientation of capture and replay device match and it is portrait, then when pre-rotation is requested, we set the orientation accordingly.
It might still show some issues with devices that have a landscape native orientation (either capture or replay device, or both), so my guess is that it will need more testing on different devices.
> android: Fix orientation when pre-rotation is set

- framework/util/platform.h
It has no reason to be static and should be inline the same way all other functions in the file are.
> Change SetSpuAffinity qualification to inline

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/graphics/vulkan_device_util.cpp
Resolves #2132 
This PR implements two changes to `replay`:
-  If the replay device's `VkPhysicalDeviceDriverProperties::driverID` is _not_ MoltenVK, we omit the `VK_KHR_portability_subset` extension
-   If `vkCreateInstance` fails with `VK_ERROR_EXTENSION_NOT_PRESENT`, we remove the `VK_KHR_portability_enumeration` extension and try again. This is important because some tools, like RenderDoc, do not support even the enumeration extension.
> Fix handling of portability extensions

- framework/decode/vulkan_rebind_allocator.cpp
In rebind allocator, the allocation size has some issue and vkAllocateMemory returns VK_ERROR_INVALID_EXTERNAL_HANDLE
This will cause resource memory binding to fail
Change-Id: I635c5c708ef32ce70db2fa20ccce80f288652c15
> Fix resource memory binding failure

- framework/decode/value_decoder.h
Relative time logic is present in frame loop replay logic which should be sufficient.
Just capturing this as a WIP.  Haven't tested it, beyond showing that converts are now consistent run to run.
> openxr: Remove relative time logic from decoders

- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
Fix in the calculation of the buffer size when the vertex binding has 0 stride
> VDR: Fix for vertex bindings with 0 stride

- framework/decode/vulkan_object_cleanup_util.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
Fixes production issues with missing/corrupted images when using trimming.
the visible issues went along with validation-errors:
`VUID-VkImageMemoryBarrier-oldLayout-01213: vkCmdPipelineBarrier(): pImageMemoryBarriers[0].newLayout (VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) is not compatible with VkImage 0x3180000000318 usage flags VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT`
and successive
`VUID-vkCmdCopyBufferToImage-dstImage-00177: vkCmdCopyBufferToImage(): dstImage (VkImage 0x31d000000031d) was created with VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT but requires VK_IMAGE_USAGE_TRANSFER_DST_BIT`
which suggests a straight-forward fix :)
also adds missing state-cleanup for `VkMicromapEXT`
closes #2214
> Fix image-issues when using trimming

- android/scripts/gfxrecon.py
- framework/decode/vulkan_replay_dump_resources_delegate.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.h
- framework/decode/vulkan_replay_dump_resources_json.cpp
- framework/decode/vulkan_replay_options.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
The new replay option --dump-resources-dump-unused-vertex-bindings can be used to dump vertex bindings which are not referenced by a vertex attribute
> VDR: Option to dump unreferenced vertex bindings

- framework/encode/vulkan_state_writer.cpp
On Android, each log maps to a separate call to androids log system, hence when looking at the timestamps of the 4 log calls we can measure how long the first 3 log statements did need. For a specific case I did see 26 us and 31 us seconds. This is not that much, but it is also very simple to improve. Hence combining the 4 log statements. Dropping the line separation (at least on Android, there is no guarantee that it is not mixed with other content, especially as there is a 31 us time period this can happen. By only issuing a single log statement, the same information can be logged with 57 us less time.
Here the log statements I did see:
1.209 678 593 I gfxrecon com.khronos.vulkan_samples --------------------------------------
1.209 704 140 I gfxrecon com.khronos.vulkan_samples …
> Use a single log for writing time information

- framework/decode/vulkan_replay_consumer_base.cpp
- account both for trimming and non-trimming case
- cleanup only for relevant device(s)
follow up on https://github.com/LunarG/gfxreconstruct/pull/2267
tested using SaschaWillems/raytracinggltf using `-m rebind` with and without trimming.
> Fix cleanup for VulkanAddressreplacer

- tools/convert/main.cpp
This will always assert with `gfxrecon-convert --output stdout`
> Remove output file assert in gfxrecon-convert

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources.h
- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/decode/vulkan_replay_dump_resources_common.h
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.h
- framework/decode/vulkan_replay_dump_resources_delegate.cpp
- framework/decode/vulkan_replay_dump_resources_delegate.h
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.h
- framework/decode/vulkan_replay_dump_resources_json.cpp
- framework/decode/vulkan_replay_dump_resources_json.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/khronos_generators/vulkan_generators/replay_overrides.json
When dumping descriptors for compute and ray tracing there was an
attempt to distinguish between "outputs" (storage descriptors) and the
rest of the descriptors. This commit merges outputs into descriptors.
> VDR: Merge comp and RT outputs into descriptors

- USAGE_android.md
- USAGE_desktop_D3D12.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/encode/capture_settings.cpp
- framework/util/logging.cpp
- framework/util/logging.h
- tools/capture-vulkan/gfxrecon-capture-vulkan.py
- tools/replay/replay_settings.h
- tools/tool_settings.h
When running GFXReconstruct in automation, it can be useful to have timestamps in front of each message for debug purpose.
This commit add the boot time in front of each logged message on desktop platforms (linux/windows) if log-level is debug.
Here's an example of logs with this commit:
```
GFXReconstruct Version 1.0.5-jenkins-c790995d (7d059ae*) Release
Vulkan Header Version 1.4.304
[gfxrecon][681347.146449] DEBUG - Failed to connect to an X server
[gfxrecon][681347.221838] DEBUG - Skip vkGetPhysicalDeviceSurfaceSupportKHR for offscreen.
[gfxrecon][681347.462342] DEBUG - Skip vkGetPhysicalDeviceSurfaceCapabilitiesKHR for offscreen.
[gfxrecon][681347.462359] DEBUG - Skip vkGetPhysicalDeviceSurfaceFormatsKHR for offscreen.
[gfxrecon][681347.462378] DEBUG - Skip …
```
> Add '--log-timestamps' option

- framework/encode/d3d12_capture_manager.cpp
- framework/encode/dx12_object_wrapper_info.h
- framework/encode/dx12_state_writer.cpp
- framework/encode/dx12_state_writer.h
The heap is created in a non-resident state, must be calling MakeResident() explicatly in tha application.The state tracking/writting have to inject MakeResident() to the heaps.
> Fix D3D12_HEAP_FLAG_CREATE_NOT_RESIDENT Heap's State Writing

- framework/decode/json_writer.cpp
- framework/util/json_util.cpp
- tools/convert/main.cpp
When stdout is set for the output, and a "--include-binaries" option is used, we were outputting to a folder called "stdout". This should not have been the case because according to our own usage info, it should have reverted to the GFXR capture file name.
Fixes #2202
> convert: Fix binary out dir when stdout used

- android/framework/decode/CMakeLists.txt
- android/framework/graphics/CMakeLists.txt
- framework/application/headless_context.cpp
- framework/decode/CMakeLists.txt
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/generated/generated_vulkan_feature_util.cpp
- framework/generated/khronos_generators/vulkan_generators/vulkan_feature_util_body_generator.py
- framework/graphics/CMakeLists.txt
- framework/graphics/vulkan_feature_util.cpp
- framework/graphics/vulkan_feature_util.h
Fix `VK_EXT_frame_boundary` fake support at device creation at capture and replay time when `VkPhysicalDeviceFrameBoundaryFeaturesEXT` is present by removing it before the actual call to the driver (and adding it again at capture time to not have a visible difference from user's perspective)
> Fix `VK_EXT_frame_boundary` fake support

- android/framework/decode/CMakeLists.txt
- android/framework/graphics/CMakeLists.txt
- framework/application/headless_context.cpp
- framework/decode/CMakeLists.txt
- framework/decode/vulkan_feature_util.cpp
- framework/decode/vulkan_feature_util.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_capture_manager.cpp
- framework/generated/generated_vulkan_feature_util.cpp
- framework/generated/khronos_generators/vulkan_generators/vulkan_feature_util_body_generator.py
- framework/graphics/CMakeLists.txt
Reverts LunarG/gfxreconstruct#1902
This commit caused `dev` to fail to compile.  My guess is that GitHub didn't detect a merge conflict and yet the code either used a lost function or didn't bring in a function it needed.
> Revert "Fix `VK_EXT_frame_boundary` fake support"

- android/scripts/gfxrecon.py
- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources.h
- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/decode/vulkan_replay_dump_resources_common.h
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.h
- framework/decode/vulkan_replay_dump_resources_delegate.cpp
- framework/decode/vulkan_replay_dump_resources_delegate.h
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.h
- framework/decode/vulkan_replay_dump_resources_json.cpp
- framework/decode/vulkan_replay_dump_resources_json.h
- framework/decode/vulkan_replay_options.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_state_writer.cpp
- framework/graphics/vulkan_resources_util.cpp
- framework/graphics/vulkan_resources_util.h
- framework/util/buffer_writer.cpp
- framework/util/buffer_writer.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
- vulkan_dump_resources.md
`--dump-resources-binary-file-compression-type` chooses between the available options. Default is uncompressed
> VDR: Add option to compress files that are dumped raw

- framework/decode/vulkan_replay_dump_resources_common.cpp
- framework/decode/vulkan_replay_dump_resources_common.h
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
Apparently some implementations (i.e. Adreno) don't have a transfer queue. According to spec, graphics and compute queues also support transfer operations.
> VDR: Fix in detecting transfer queue

- framework/decode/vulkan_address_replacer.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/encode/vulkan_handle_wrappers.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_writer.cpp
Simplify acceleration-structure (AS) tracking and trimming by **not** differentiating between build-modes: 'build' and 'update', just treat everything as 'build'.
when replaying a trimmed capture, during state-init, we rebuild acceleration-structures from scratch.
`VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR` would rely on a pre-existing AS, which does not apply here.
associated scratch-buffers for an 'update' are normally smaller compared to 'build', so they could not be used when rebuilding from scratch.
for this reason we relax a condition and allow VulkanAddressReplacer to substitute those missing (or not large enough) buffers, also without using `-m rebind`.
**Fixed in this PR**:
capture:
`[gfxrecon] WARNING - vulkan_wrappers::GetWrappedId() couldn't find Handle: 0x46d6c0e27d0's …
> Fix for trimming AccelerationStructures

- framework/decode/file_processor.cpp
- framework/format/format.h
reserving high-bit for 'special purposes' (like testing, experimentation, specializations, etc.)
- the intention is to provide a vendor-neutral way to have non-conflicting custom IDs
> Add maximum enum-value for format::MetaDataType

- framework/encode/custom_vulkan_encoder_commands.h
- framework/encode/vulkan_capture_manager.cpp
- framework/encode/vulkan_capture_manager.h
- framework/generated/generated_vulkan_api_call_encoders.cpp
- framework/generated/khronos_generators/vulkan_generators/capture_overrides.json
- move correction from OverrideBeginCommandBuffer() to a CustomEncoderPreCall
- cleanup override, not required anymore
closes [#2349](https://github.com/LunarG/gfxreconstruct/issues/2349)
> Fix crash when primary cmd-buf has invalid inheritance-data

- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_allocator.h
According to the Vulkan specification:
(VUID-VkMemoryAllocateInfo-allocationSize-02383)
If the parameters define an import operation and the external handle type is `VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID`, `allocationSize` must be the size returned by
`vkGetAndroidHardwareBufferPropertiesANDROID` for the Android hardware buffer.
As per the current state of the code, this function can only be reached if `memory_alloc_info->ahb` is not `nullptr`, so this applies. Thus `allocationSize` must neither be the one returned by `vkGetImageMemoryRequirements` nor the capture time allocation size.
I also added a `GFXRECON_ASSERT` to make sure that `memory_alloc_info->ahb` cannot be `nullptr`.
> Fix `VulkanRebindAllocator::AllocateAHBMemory`

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- framework/encode/capture_manager.cpp
- framework/encode/capture_manager.h
- framework/encode/capture_settings.cpp
- framework/encode/capture_settings.h
- tools/replay/desktop_main.cpp
- tools/replay/replay_settings.h
When running `gfxrecon-replay --capture`, replay sets up the log file. The capture manager also intializes the log file, overwriting the setup from replay. This change skips the log setup in the capture manager so that logging is done based on the settings provided to replay.
> Use replay log settings when doing recapture

- framework/decode/vulkan_cpp_consumer_base.cpp
- framework/util/logging.cpp
- tools/convert/main.cpp
Having introduced a double-close (double-free) with a non-null'd FILE * after close accidentally, I searched the codebase and found the following locations that have persistent FILE * variables or members after file close and thus *could* be subject to a double-close.
> Zero file handle pointer after close

- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.cpp
- framework/decode/vulkan_replay_dump_resources_compute_ray_tracing.h
When dumping both draw calls and dispatch/trace rays from the same queue submit draw calls are dumped first. If wait semaphores are used in the submission then the first submission (draw calls) will sucessfully wait for the semaphore while the second submission (dispatch) will hang.
> VDR: Filter semaphores on same submission

- framework/graphics/vulkan_resources_util.cpp
In case of multi sampled images the resolved image was never used. Instead the CopyImageToBuffer was attempting to copy directly from the multi sampled image causing visual artifacts.
> Fix in ReadImageResources

- framework/decode/preload_file_processor.cpp
- framework/decode/preload_file_processor.h
Fixes regression to preload caused by file processor IO cleanup.
> Correct read errors with preload enabled

- framework/generated/khronos_generators/openxr_generators/gencode.py
- framework/generated/khronos_generators/vulkan_generators/gencode.py
Fix spelling of "emitExtensions" in a debug print.  This doesn't impact our compiled code, but still helpful to prevent confusion
> fix typo in fixEtensions

- framework/decode/vulkan_replay_dump_resources.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
- framework/decode/vulkan_replay_dump_resources_draw_calls.h
When --dump-resources-before-draw was set, command parameters for indirect draw were beeing copied twice, once for the "before" command and once for the "after" command. This should be fixed now
> VDR: Fetch draw indirect params only once

- framework/decode/vulkan_object_info.h
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_consumer_base.h
- framework/generated/generated_vulkan_replay_consumer.cpp
- framework/generated/khronos_generators/vulkan_generators/replay_overrides.json
This PR fixes issues with captures using swapchain color-format `VK_FORMAT_A2B10G10R10_UNORM_PACK32`.
even when this format is not supported during **replay**,
GFXR would allow using it, for created `VkImageView`s onto the swapchain-images. 
symptom were color-sampling distortions due to different data-layouts:
- Add `OverrideGetPhysicalDeviceSurfaceFormatsKHR`, keep track of supported formats
- fallback to safe format if we are sure a configuration is not supported
- adjust image-views for swapchain-images if necessary
> Fix color-distortion when capture uses HDR color-format

- USAGE_android.md
- USAGE_desktop_Vulkan.md
- android/scripts/gfxrecon.py
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_replay_options.h
- framework/util/options.h
- tools/replay/replay_settings.h
- tools/tool_settings.h
Add an option to adjust the swapchain's present mode used at replay time.
Present mode may need to be modified for performance measurement reasons or for portability reasons.
This commit allows to set a particular present mode to use.
> Add `--present-mode` option

- framework/decode/file_processor.cpp
- framework/decode/vulkan_offscreen_swapchain.cpp
- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_tracking_consumer.cpp
- framework/decode/vulkan_virtual_swapchain.cpp
- framework/graphics/vulkan_resources_util.cpp
- framework/util/logging.cpp
- framework/util/page_guard_manager.h
These are fairly random fixes of things I noticed while going through the output of clang-check from clang 22. Its warnings are getting quite useful, although the amount of false positives and plain noise is still very high.
> Fix a few errors and warnings found by clang-check

- framework/graphics/vulkan_resources_util.cpp
GetImageResourceSizesOptimal was checking if the provided extent was in accordance with the number of the provided mip levels. When scaling is requested with VDR this could trigger this warning as the scaled down extent can have less mip levels than the original dimensions.
This should be ok and in practice desired when scaling down images and their subresources. For example dumping an image 4x4 with 3 levels at scale 0.5 should still dump 3 mip levels with dimensions (2x2), (1x1) and (1x1).
So this warning message is obsolete and is removed by this commit.
> Remove obsolete warning message

- android/framework/util/CMakeLists.txt
- framework/decode/file_processor.cpp
- framework/decode/file_processor.h
- framework/decode/preload_file_processor.cpp
- framework/decode/preload_file_processor.h
- framework/util/CMakeLists.txt
- framework/util/file_input_stream.cpp
- framework/util/file_input_stream.h
- framework/util/heap_buffer.cpp
- framework/util/heap_buffer.h
For improved encapsulation and simplification of IO to drive block processing down a common path for all block processing operations. 
Current based on https://github.com/LunarG/gfxreconstruct/pull/2415
> Refactor to all FileProcessor IO through single read-to-block buffer

- framework/decode/vulkan_replay_consumer_base.cpp
follow-up to https://github.com/LunarG/gfxreconstruct/pull/2429
during replay, when we cannot support a requested swapchain VkFormat, we fall back to a 'safe' format.
later during runtime, when `VkImageView`s onto swapchain images are created,
we again have to apply corrections.
in both cases we also need to account for SRGB formats.
e.g. `VK_FORMAT_R8G8B8A8_UNORM` -> `VK_FORMAT_B8G8R8A8_UNORM`
and `VK_FORMAT_R8G8B8A8_SRGB` -> `VK_FORMAT_B8G8R8A8_SRGB`
also: 
during swapchain creation we check for usage of `VK_KHR_swapchain_mutable_format`
apply corrections, if necessary.
fixes #2414
> Fix dark colors when capture uses an SRGB swapchain-format

- framework/generated/dx12_generators/dx12_json_consumer_body_generator.py
- framework/generated/generated_dx12_json_consumer.cpp
Add null check for D3D12 enum pointers in gfxrecon-convert special case.
> Fix gfxrecon-convert null dereference

- framework/decode/file_processor.cpp
also ensure all locations where SkipBytes was deleted to update success as they would have before.
Rebases and replaces https://github.com/LunarG/gfxreconstruct/pull/2440  contributed by @JerryAMD .
> Skip Unsupported and Reserved Meta-data Block Successfully

- framework/decode/vulkan_rebind_allocator.cpp
- framework/decode/vulkan_rebind_allocator.h
For rebind, it allocated memory when a object was bound to a memory. It could allocate duplicated memory when two objects were bound to the same memory to cause OUT_OF_MEMORY. In order to reduce memory usage, it attempts to find a compatible existing `VmaMemoryInfo` before allocating new memory. Plus, it needs to consider offset for binding because the memory could not be specifically allocated to an object.
> Reuse memory to reduce memory usage for rebind

- framework/decode/vulkan_replay_consumer_base.cpp
- framework/decode/vulkan_resource_initializer.cpp
- framework/decode/vulkan_resource_initializer.h
- framework/encode/vulkan_state_tracker.cpp
- framework/encode/vulkan_state_tracker.h
- framework/encode/vulkan_state_writer.cpp
- framework/encode/vulkan_state_writer.h
two different things are corrected in this PR. both are related to trimming and deleted buffers
used for AS-builds.
1) tracking/recreation of deleted AS input-buffers during capture had a regression after recent rework
2) a longer standing issue we didn't notice caused errors/crashes during replay for trimmed raytracing-captures 
(when using default-allocator, `-m rebind` was fine)
-> this was since an optimization of `decode::VulkanResourceInitializer` which deferred copying of data until destruction.
->  the symptom was attempted buffer-copies, but the temporary buffer was already deleted again.
-> fixed by splitting AS state-init into resource-upload / build+cleanup
also:
- Fix validation-error in `decode::VulkanResourceInitializer`
-> query …
> Fix tracking of deleted AS input-buffers during capture

- .github/CODEOWNERS
Add CODEOWNERS file, which has special meaning to GitHub, containing the "GFXReconstruct Architecture Reviewers" team that we have defined internally.  That team will be automatically added as a reviewer and we can at some future date if desired block merges without that review.
> Add team responsible for reviewing PRs or assigning review of PRs
