BUILD.md, layer/USAGE_android.md, layer/USAGE_desktop.md
* Large BUILD.md update
* Large USAGE_desktop.md update
* Corrections to USAGE_android.md
=> Usage and Build Documentation Update

framework/application/xcb_application.cpp, framework/application/xcb_window.cpp, framework/application/xcb_window.h
* Updates for full screen mode.
* Flush after window destroy.
=> Updates for XCB Window Handling

framework/encode/custom_encoder_commands.h, framework/encode/trace_manager.h, framework/encode/vulkan_handle_wrappers.h, framework/encode/vulkan_state_table.h, framework/encode/vulkan_state_tracker.cpp, framework/encode/vulkan_state_tracker.h, framework/encode/vulkan_state_tracker_initializers.h, framework/encode/vulkan_state_writer.cpp, framework/encode/vulkan_state_writer.h
Initial support for tracking fence, event, and semaphore states.
=> Add Synchronization Object Tracking for Trimming Snapshot

framework/encode/descriptor_update_template_info.h, framework/encode/trace_manager.cpp, framework/encode/vulkan_handle_wrappers.h, framework/encode/vulkan_state_tracker.cpp, framework/encode/vulkan_state_tracker.h, framework/encode/vulkan_state_writer.cpp, framework/encode/vulkan_state_writer.h
Miscellaneous changes to address issues discovered when testing the current trimming code with vkcube and the Sascha Willems Vulkan examples.
=> Misc Trimming Updates and Fixes

framework/encode/trace_manager.h, framework/encode/vulkan_state_writer.cpp, framework/encode/vulkan_state_writer.h
Fixes for trimming issues discovered when testing with Android.
=> Additional Fixes for Trimming State Snapshot

framework/encode/trace_manager.cpp
- Fix issue when capturing multiple frame ranges with consecutive end
and begin frames (e.g. '101,102,103').
- Log a message when finished recording a frame range.
=> Adjust trimming frame range tracking

framework/util/page_guard_manager.cpp
When the pageguard signal handler recieves a signal that is not a SIGSEGV signal generated for memory that the pageguard implementation protected with mprotect(), it will now forward the signal to the original signal handler that it replaced.
This fixes an issue with capturing a Unity demo on Android, where the pageguard signal handler appears to have been interfering with Mono exception handling.
=> Update pageguard sigaction behavior

framework/encode/trace_manager.cpp, framework/encode/trace_manager.h, framework/generated/generated_vulkan_struct_handle_mappers.cpp, framework/generated/vulkan_generators/base_generator.py
* Fix duplicate pNext processing in code generated handle mapping functions for replay.
* Fix issue with disabling capture after processing all trimming frame ranges.
=> Misc Code Generation and Trimming Fixes

framework/encode/vulkan_state_tracker.cpp
Fix trimming state tracking for secondary command buffer execution:
- Transfer recorded query state from secondary command buffer wrapper
to primary command buffer wrapper at command execution.
- Fix secondary handle wrapper assignment bug where the primary
command buffer handle was used to obtain both the secondary and
primary command buffer wrappers.
=> Fix Trimming Secondary Command Buffer Tracking

android/scripts/gfxrecon.py
- Use the Python argparse module to parse arguments provided to the
gfxrecon.py launcher script for Android
- Fix issue with Windows path separators being stripped from the
filename provided to the install-apk command
- Properly handle arguments provided to the replay command
=> Fix Android Launch Script Argument Parsing

framework/encode/vulkan_state_tracker.cpp
Fix an issue with tracking writes to descriptor arrays when VkWriteDescriptorSet::dstArrayElement was not 0.
=> Fix Descriptor Array Write Tracking

framework/encode/trace_manager.cpp
When the vkMapMemory size parameter was VK_WHOLE_SIZE, the capture layer treated size as the entire allocation size instead of (allocation size - mapped offset).
=> Fix vkMapMemory capture with VK_WHOLE_SIZE

framework/decode/pointer_decoder.h, framework/decode/pointer_decoder_base.h, framework/decode/string_decoder.h, framework/encode/parameter_encoder.h, framework/format/format.h
Change-Id: I330483aefb61f6ac02f2545716784c0640a6fffc
=> Fix encode/decode of wchar_t strings

framework/decode/vulkan_enum_util.h, tools/replay/android_main.cpp
* Fix non-static function definition in header file.
* Fix null pointer dereference on exit after exception for Android replay app.
=> Minor code fixes

android/framework/util/CMakeLists.txt, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_consumer_base.h, framework/util/CMakeLists.txt, framework/util/hash.cpp, framework/util/hash.h, framework/util/platform.h, tools/CMakeLists.txt, tools/extract/CMakeLists.txt, tools/extract/main.cpp
Add gfxrecon-extract tool which extracts all shaders from trace into
individual files.
Change-Id: I86eed9268dde6cfbb688a6d4087b868d3d8ee77b
=> Shader extract feature

framework/util/page_guard_manager.cpp
When setting the page guard signal handler, include the SA_ONSTACK flag if we are replacing a signal handler that was originally registered with the SA_ONSTACK flag.
=> Conditionally set SA_ONSTACK with sigaction

framework/application/wayland_application.cpp, framework/application/wayland_application.h, framework/application/wayland_window.cpp, framework/application/wayland_window.h, framework/util/wayland_loader.cpp, framework/util/wayland_loader.h
- Fix issue with window size doubling on HiDPI displays (reported here: #327).
- Add support for fullscreen replay.
=> Wayland replay improvements

framework/util/keyboard.cpp
Add include for logging.h to keyboard.cpp
=> Add missing logging.h include

BUILD.md, CMakeLists.txt, cmake/GenerateLayerJson.cmake, layer/CMakeLists.txt, tools/compress/CMakeLists.txt, tools/extract/CMakeLists.txt, tools/info/CMakeLists.txt, tools/replay/CMakeLists.txt, tools/toascii/CMakeLists.txt
=> Add CMake install rules

tools/CMakeLists.txt, tools/capture/CMakeLists.txt, tools/capture/gfxrecon-capture.py, tools/gfxrecon/CMakeLists.txt, tools/gfxrecon/gfxrecon.py
Adds the following scripts:
- gfxrecon-capture.py: Launch an application after setting capture environment variables.
- gfxrecon.py: Experimental script to serve as a single command for launching command line utilities such as 'gfxrecon-replay' when invoked as 'gfxrecon replay'.
=> Initial implementation of gfxrecon-capture.py and gfxrecon.py

framework/util/page_guard_manager.cpp
When replacing a signal handler that was set with the SA_ONSTACK flag, also replace the alternate signal stack with memory that is guaranteed to be valid for the replacement signal handler. Both the original signal handler and stack will be restored when the layer's signal handler is removed.
=> Replace alt signal stack with SA_ONSTACK override

framework/encode/capture_settings.cpp
Reading the settings from the filter name following layers conventions
=> Fix interaction with vkconfig.

framework/decode/file_processor.cpp, framework/decode/vulkan_default_allocator.cpp, framework/decode/vulkan_rebind_allocator.cpp, framework/decode/vulkan_replay_consumer_base.cpp, framework/util/lz4_compressor.cpp, framework/util/zstd_compressor.cpp, tools/compress/main.cpp, tools/extract/main.cpp, tools/info/main.cpp, tools/replay/desktop_main.cpp, tools/replay/replay_settings.h, tools/toascii/main.cpp
Adds the following to assist with debugging:
- Error logging for compression failures.
- Additional debug code and error logging for replay memory allocation.
- Options to disable the 'Abort, Retry, Ignore' message box that is displayed for assertion failures with Visual Studio debug builds.
=> Additional Error/Debug Reporting

.github/workflows/ci_build.yml, .github/workflows/release_build.yml, .github/workflows/sdk_android_build.yml, USAGE_android.md, USAGE_desktop.md, layer/vk_layer_settings.txt
* Add a sample vk_layer_settings.txt file with entries describing each available setting.
* Update usage documentation with a settings file description.
Fixes #391
=> Add settings file sample and documentation

framework/generated/generated_decode_pnext_struct.cpp, framework/generated/generated_encode_pnext_struct.cpp, framework/generated/generated_vulkan_struct_decoders.cpp, framework/generated/generated_vulkan_struct_decoders.h, framework/generated/generated_vulkan_struct_decoders_forward.h, framework/generated/generated_vulkan_struct_encoders.cpp, framework/generated/generated_vulkan_struct_encoders.h, framework/generated/generated_vulkan_struct_handle_wrappers.cpp
- Update external/Vulkan-Headers submodule to v1.2.148
- Regenerate source files
=> Update header to 1.2.148

USAGE_android.md, USAGE_desktop.md, android/scripts/gfxrecon.py, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_options.h, tools/replay/replay_settings.h
Adds a -s/--sync option for replay, which will call vkQueueWaitIdle after each call to vkQueueSubmit.
=> Add replay option to sync queue submissions

.github/workflows/ci_build.yml, .github/workflows/release_build.yml, CMakeLists.txt, cmake/CodeStyle.cmake, cmake/Cpp.cmake, cmake/Test.cmake, cmake/Utils.cmake, scripts/build.py, scripts/test.py
* Each configuration + platform + architecture configuration now has
it's own output directory
* Each configuration + platform + architecture configuration now has
it's own cmake files output directory
Fixes: #369
Change-Id: Id6ee2a227c4cdfb1ede55cd3ef2a129b0ea1b0b1
=> Changes to the build output directories

USAGE_android.md, USAGE_desktop.md, android/scripts/gfxrecon.py, framework/decode/screenshot_handler.cpp, framework/decode/screenshot_handler.h, tools/replay/replay_settings.h
- Fix screenshot format conversion / preserve sRGB
- Add --screenshot-all option to generate screenshots for all replayed frames
- Update Android gfxrecon.py script and usage docs for new options
=> Screenshot Updates

USAGE_desktop.md, tools/gfxrecon/gfxrecon.py
Add an entry for gfxrecon-optimize to the USAGE_desktop.md document.
=> Add gfxrecon-optimize usage documentation

tools/capture/gfxrecon-capture.py
Normalize the mapping of command-line arguments to environment variables
and always omit unspecified options from the capture environment.
Previously, there were a few options which were unconditionally set.
This resulted in extra [INFO] messages from the capture layer.
Change-Id: I4544dfd0bf2fcc738f436fcaf7b5031a484424fa
=> Tweak gfxrecon-capture.py environment setup

.github/workflows/sdk_android_build.yml, BUILD.md, android/.gitignore, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/layer/build.gradle, android/tools/replay/build.gradle, android/tools/replay/src/main/AndroidManifest.xml, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_consumer_base.h, tools/replay/android_main.cpp
* Update gradle version via Android Studio version update.
* Keep screen on while replay is active.
* Ensure orientation is set correctly with older capture files.
* Stop process on activity exit.
=> Miscellaneous Android updates

android/tools/replay/src/main/AndroidManifest.xml, framework/decode/resource_util.cpp, framework/decode/resource_util.h, framework/decode/vulkan_rebind_allocator.cpp, framework/decode/vulkan_rebind_allocator.h, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_consumer_base.h, tools/replay/android_main.cpp
- Simplify Android process termination.
- Fix AHardwareBuffer memory writes for images with different capture/replay strides.
=> Misc Android updates

BUILD.md, tools/capture/gfxrecon-capture.py
1) Modified build.md.
2) Fixed python print bug.
=> Bug fix & Modify build.md

framework/format/api_call_id.h, framework/generated/generated_decode_pnext_struct.cpp, framework/generated/generated_encode_pnext_struct.cpp, framework/generated/generated_layer_func_table.h, framework/generated/generated_vulkan_api_call_encoders.cpp, framework/generated/generated_vulkan_api_call_encoders.h, framework/generated/generated_vulkan_ascii_consumer.cpp, framework/generated/generated_vulkan_ascii_consumer.h, framework/generated/generated_vulkan_consumer.h, framework/generated/generated_vulkan_decoder.cpp, framework/generated/generated_vulkan_decoder.h, framework/generated/generated_vulkan_dispatch_table.h, framework/generated/generated_vulkan_feature_util.cpp, framework/generated/generated_vulkan_replay_consumer.cpp, framework/generated/generated_vulkan_replay_consumer.h, framework/generated/generated_vulkan_struct_decoders.cpp, framework/generated/generated_vulkan_struct_decoders.h, framework/generated/generated_vulkan_struct_decoders_forward.h, framework/generated/generated_vulkan_struct_encoders.cpp, framework/generated/generated_vulkan_struct_encoders.h, framework/generated/generated_vulkan_struct_handle_wrappers.cpp
- Update external/Vulkan-Headers submodule to v1.2.166
- Add API call IDs for VK_NV_acquire_winrt_display
=> Update header to 1.2.166

framework/encode/trace_manager.cpp
- At layer initialization, log both the GFXReconstruct version and the supported Vulkan header version.
- Log a warning when vkCreateInstance is called with an apiVersion that exceeds the supported Vulkan header version.
=> Report capture layer version

framework/decode/vulkan_replay_consumer_base.cpp
When replaying vkGetEventStatus, limit the number of retries performed when attempting to get the replay result to match the capture result, to avoid a potential infinite loop.
=> Limit the number of vkGetEventStatus retries

framework/decode/vulkan_replay_consumer_base.cpp
Follows the recent change to `vkGetEventStatus` - https://github.com/LunarG/gfxreconstruct/pull/523
When replaying `vkGetQueryPoolResults`, limit the number of retries
performed when attempting to get the replay result to match the capture
result, to avoid a potential infinite loop.
This happened in a number of D3D11 games running with DXVK.
I'm a bit hesitant to do the same for `vkGetFenceStatus` since I don't have 
any real-world app to suffer from it. So I just left a comment.
=> Limit the number of vkGetQueryPoolResults retries

USAGE_desktop.md
This PR updates `USAGE_desktop.md` with `gfxrecon-toascii` description and usage.
=> vk-to-ascii-documentation

framework/decode/vulkan_replay_consumer_base.cpp
Change the assertion condition to allow the "submission count == 0" case.
=> The queue submit info count may be 0

framework/decode/CMakeLists.txt, framework/encode/capture_settings.cpp, framework/util/file_path.cpp, tools/tool_settings.h
Change-Id: I5f64bbb639f75d253b3cd31bbb8e7e2c2b7016b8
=> Fix for VS2015

CMakeLists.txt, framework/application/CMakeLists.txt, framework/application/application.cpp, framework/application/display_context.cpp, framework/application/display_context.h, framework/application/display_window.cpp, framework/application/display_window.h, tools/replay/desktop_main.cpp, tools/tool_settings.h
Try vkCreateDisplayPlaneSurfaceKHR() from VK_KHR_display extension on Unix systems before falling back to the headless mode.
=> Add direct display support

android/framework/decode/CMakeLists.txt, framework/generated/generated_decode_pnext_struct.cpp, framework/generated/vulkan_generators/decode_pnext_struct_generator.py
https://github.com/LunarG/gfxreconstruct/issues/586
=> Print VkStructureType string

framework/util/page_guard_manager.cpp, framework/util/page_guard_manager.h
=> allocate s_alt_stack at startup with size probed from system

framework/encode/custom_vulkan_struct_handle_wrappers.cpp, framework/encode/custom_vulkan_struct_handle_wrappers.h, framework/encode/vulkan_capture_manager.h, framework/encode/vulkan_handle_wrapper_util.h, framework/encode/vulkan_handle_wrappers.h, framework/encode/vulkan_state_tracker.cpp, framework/encode/vulkan_state_tracker.h, framework/encode/vulkan_state_writer.cpp, framework/generated/generated_vulkan_struct_handle_wrappers.cpp, framework/generated/generated_vulkan_struct_handle_wrappers.h, framework/generated/vulkan_generators/vulkan_struct_handle_wrappers_body_generator.py, framework/generated/vulkan_generators/vulkan_struct_handle_wrappers_header_generator.py
https://github.com/LunarG/gfxreconstruct/issues/273
- vkBindImageMemory2 and vkBindBufferMemory2
- VkBindImageMemorySwapchainInfoKHR
Test code: https://github.com/locke-lunarg/Vulkan-Tools/tree/locke-bind_memory2
=> Trimming: Bind memory2

framework/encode/custom_vulkan_encoder_commands.h, framework/encode/vulkan_capture_manager.cpp, framework/encode/vulkan_capture_manager.h, framework/encode/vulkan_handle_wrappers.h, framework/encode/vulkan_state_tracker.cpp, framework/encode/vulkan_state_tracker.h, framework/encode/vulkan_state_writer.cpp, framework/encode/vulkan_state_writer.h
https://github.com/LunarG/gfxreconstruct/issues/273
-  VK_EXT_inline_uniform_block
-  VK_EXT_full_screen_exclusive
Test: https://github.com/locke-lunarg/Vulkan-Tools/tree/locke-test2
=> Trimming: VK_EXT_inline_uniform_block and VK_EXT_full_screen_exclusive

framework/application/application.cpp
Fixes a warning in the Android build
=> use strcmp to compare strings and use defined constant

framework/decode/vulkan_enum_util.h, framework/decode/vulkan_rebind_allocator.cpp, framework/decode/vulkan_replay_consumer_base.cpp, framework/encode/custom_vulkan_encoder_commands.h, framework/encode/vulkan_capture_manager.cpp, framework/encode/vulkan_capture_manager.h, framework/encode/vulkan_handle_wrappers.h, framework/encode/vulkan_state_info.h, framework/encode/vulkan_state_tracker.cpp, framework/encode/vulkan_state_writer.cpp
https://github.com/SaschaWillems/Vulkan#hardware-accelerated-ray-tracing
It can do trimming for SaschaWillems's Ray tracing five examples.
=> Trimming Ray Tracing KHR extensions

framework/decode/file_processor.cpp, framework/decode/file_transformer.cpp, framework/format/format_util.cpp
Fixes #670
Also fix spelling in two places.
=> clarify errors for disabled file compression module

framework/encode/handle_unwrap_memory.h, framework/encode/vulkan_capture_manager.cpp
In my previous commit https://github.com/LunarG/gfxreconstruct/commit/7a0573c882ac61cc222f20a40df7c87b26143a5a, I lost this commit  https://github.com/LunarG/gfxreconstruct/commit/1e1853aea10c43232c64d8cd572ff1d4b98a7688.
https://github.com/LunarG/gfxreconstruct/pull/562.
=> Fix compiling with gcc11

framework/decode/vulkan_ascii_consumer_base.cpp
also pull some lambdas apart for clarity
=> remove unsequenced modification and access

USAGE_android.md, android/scripts/gfxrecon.py, framework/decode/replay_options.h, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_consumer_base.h, framework/generated/generated_vulkan_replay_consumer.cpp, framework/generated/vulkan_generators/replay_overrides.json, tools/replay/replay_settings.h, tools/tool_settings.h
Add the option string, description of option, and detection of option.
Override vkGetAndroidHardwareBufferPropertiesANDROID and implement the
option.
=> add new option --omit-null-hardware-buffers

external/catch2/catch.hpp
Fixes failure of unit tests to build under Ubuntu 19.10.
Issue #695
=> Updated Catch2 Header to Latest

framework/generated/generated_layer_func_table.h, framework/generated/vulkan_generators/layer_func_table_generator.py, layer/trace_layer.cpp, layer/trace_layer.h
=> Provide a GetPhysicalDeviceProcAddr function

framework/util/page_guard_manager.cpp
On error mmap returns the value MAP_FAILED (that is, (void *) -1), not
NULL
=> Correct check of mmap's return value

framework/decode/vulkan_replay_consumer_base.cpp
When replaying the AndroidHardwareBuffer usage flags were altered
compared to the recorded flags. This caused vkAllocateMemory to fail
when importing an AHB on Android 12.
=> Keep same usage flags for AHB when replaying

framework/encode/vulkan_capture_manager.cpp
=> move addition of VK_KHR_EXTERNAL_MEMORY_CAPABILITIES to CreateInstance

framework/decode/vulkan_replay_consumer_base.cpp
It fixed this issue https://github.com/LunarG/Projects/issues/544. The discussion is in the bottom.
=> BugFix: If it only calls GetSwapchainImages once

tools/capture/gfxrecon-capture.py
This is useful for
1. Make it easier to use GFXR even when the SDK is not installed
2. Make it easier to debug and test versions of GFXR during development.
=> Add an option to the capture script use a capture layer in a given directory

framework/decode/custom_vulkan_struct_decoders_to_string.cpp, framework/generated/generated_vulkan_struct_decoders_to_string.cpp, framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
=> don't assert on non-decoded and print null instead of ""

framework/util/to_string.h
=> print null if the passed array was actually nullptr

USAGE_desktop.md
Trivial change to match other headers (noun describing what is done rather than the agent doing it).
=> Heading Consistency

framework/encode/vulkan_capture_manager.cpp
AHardwareBuffer_lock can succeed and yet not provide a data pointer
=> don't dereference a possibly null pointer

tools/capture/gfxrecon-capture.py
Reverts LunarG/gfxreconstruct#581
=> Revert "Add an option to the capture script use a capture layer in a given directory"

USAGE_desktop.md, tools/convert/README.md
Describes the Convert tool, the JSON format it outputs (informally) and gives some recipes for processing that.
Fixes #820
Ready for review.
=> Document gfxrecon-convert and JSON Lines Format

framework/decode/custom_vulkan_ascii_consumer.h, framework/decode/custom_vulkan_struct_decoders_to_string.cpp, framework/generated/generated_vulkan_struct_decoders_to_string.cpp, framework/generated/generated_vulkan_struct_to_string.cpp, framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py, framework/generated/vulkan_generators/vulkan_struct_to_string_body_generator.py, framework/util/custom_vulkan_to_string.cpp, framework/util/test/main.cpp, framework/util/to_string.h
JSON String Escaping
Fixes Issue #847
Made JSONEscape() and unit test.
Centralised C-String conversions in one function CStrToString() which
calls the escape function.
Plumbed it in to generated and custom code.
=> JSON String Escaping

USAGE_desktop.md, tools/convert/README.md, tools/convert/main.cpp
Fixes Issue #832
This previously passed CI with Convert enabled in the build.
=> Convert - Changed Default Extension to jsonl

USAGE_desktop.md, tools/CMakeLists.txt, tools/gfxrecon/gfxrecon.py
This should be the last piece to fix #818
=> Add Convert to gfxrecon.py and Enable it in Build

framework/encode/capture_manager.cpp, framework/encode/capture_settings.cpp, framework/util/logging.cpp, framework/util/logging.h
=> send all except kCommandSeverity and kAlwaysSeverity to stderr

framework/encode/capture_manager.cpp, framework/encode/capture_settings.cpp, framework/util/logging.cpp, framework/util/logging.h
This reverts commit c745ce3e18f05d80d1ce9b1e824f085906ae8ba7.
Logging did not work correctly after that commit.
=> Revert #873

framework/generated/generated_vulkan_api_call_encoders.cpp, framework/generated/generated_vulkan_dispatch_table.h, framework/generated/generated_vulkan_replay_consumer.cpp, framework/generated/vulkan_generators/vulkan_api_call_encoders_body_generator.py, framework/generated/vulkan_generators/vulkan_dispatch_table_generator.py, framework/generated/vulkan_generators/vulkan_replay_consumer_body_generator.py
=> Use GetInstanceProcAddr for SetDebugUtilsObject{Name,Tag}

framework/encode/custom_dx12_wrapper_commands.h, framework/encode/d3d12_capture_manager.cpp, framework/encode/d3d12_capture_manager.h
=> Final Plumbing of Device4::CreateReservedResource1 for Encode

framework/decode/vulkan_virtual_swapchain.cpp
=> fix sync val error in virtual swapchain Blit

framework/encode/vulkan_state_table_base.h
Reduce mutex/lock overhead by switching from mutex to shared_mutex. Use a unique_lock when modifying the table and a shared_lock when reading from the table.
=> Use shared_mutex in VulkanStateTable

USAGE_desktop_D3D12.md, tools/replay/replay_settings.h
The message is out of date.
Update the message.
=> Update Help Output and USAGE File

CMakeLists.txt, framework/decode/custom_vulkan_struct_to_json.cpp, framework/decode/info_decoder.h, framework/decode/vulkan_json_util.h, framework/generated/generated_vulkan_struct_to_json.cpp, framework/generated/vulkan_generators/vulkan_struct_to_json_body_generator.py
Built on:
```
.-/+oossssoo+/-. 
`:+ssssssssssssssssss+:`           ------------------------------
-+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS x86_64
.ossssssssssssssssssdMMMNysssso.       Host: Alienware m15 R7
/ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-42-generic
+ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 15 hours, 35 mins
/sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2545 (dpkg), 14 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2560x1440
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark …
```
=> Fixed Build for Clang-14

HOWTO_android.md
Apply Erika's comments and wordsmithing to the doc.
=> Cleanup Android Howto doc

framework/encode/capture_settings.cpp
=> Fix error in parsing trim settings on Android

framework/encode/capture_manager.cpp, framework/encode/vulkan_capture_manager.cpp
Block index counter at capture was misaligned. This should fix it
=> Fix for capture block index count

.github/workflows/sdk_android_build.yml, CMakeLists.txt
Update the SDK tag Android build action to catch `vulkan-sdk-*`
=> use new SDK tagging scheme

framework/generated/dx12_generators/dx12_api_call_encoders_body_generator.py, framework/generated/dx12_generators/dx12_api_call_encoders_header_generator.py, framework/generated/dx12_generators/dx12_ascii_consumer_header_generator.py, framework/generated/dx12_generators/dx12_base_generator.py, framework/generated/dx12_generators/dx12_consumer_header_generator.py, framework/generated/dx12_generators/dx12_decoder_body_generator.py, framework/generated/dx12_generators/dx12_decoder_header_generator.py, framework/generated/dx12_generators/dx12_enum_to_string_body_generator.py, framework/generated/dx12_generators/dx12_enum_to_string_header_generator.py, framework/generated/dx12_generators/dx12_replay_consumer_body_generator.py, framework/generated/dx12_generators/dx12_replay_consumer_header_generator.py, framework/generated/dx12_generators/dx12_struct_decoders_body_generator.py, framework/generated/dx12_generators/dx12_struct_decoders_forward_generator.py, framework/generated/dx12_generators/dx12_struct_decoders_header_generator.py, framework/generated/dx12_generators/dx12_struct_object_mappers_header_generator.py, framework/generated/dx12_generators/dx12_struct_to_string_body_generator.py, framework/generated/dx12_generators/dx12_struct_to_string_header_generator.py, framework/generated/dx12_generators/dx12_struct_wrapper_body_generator.py, framework/generated/dx12_generators/dx12_struct_wrapper_header_generator.py
=> Methond to Method

framework/decode/json_writer.h, framework/decode/metadata_json_consumer.h
Now we have straight-line code that can be stepped through without jumping around.
=> Removed Lambda Indirection For MetaCommand to JSON

framework/decode/json_writer.cpp
A minor perf tweak to benefit from short circuit eval.
=> Reordered Integer Compare Before String

framework/decode/vulkan_replay_consumer_base.h
Reduce unnecessary message spew in builds.
=> android: Fix build warning

framework/decode/metadata_json_consumer.h
SetRayTracingShaderGroupHandleCommand ->
SetRayTracingShaderGroupHandlesCommand
set_raytracing_shader_group_handle.bin ->
set_raytracing_shader_group_handles.bin
=> Fix missing s typo in JSON output

framework/decode/vulkan_replay_consumer_base.cpp
=> fixes #1422: gfxrecon-replay to create --screenshot-dir if it doesn't exist

framework/encode/vulkan_state_writer.cpp
Fix a merge error that occurred when a Reset snuck in after initial CI success with #1410 .
=> fix merge error

framework/graphics/dx12_resource_data_util.cpp
When transitioning subresource state after copy, take into account implicitly promoted copy state. Also, when copying resource data, transition all subresources before copying any subresource data.
=> Fix debug layer errors when writing/loading trim state

.github/workflows/ci_build.yml
=> Add --parallel option to macOS CI builds

framework/util/page_guard_manager.cpp, framework/util/page_guard_manager.h, framework/util/page_guard_manager_uffd.cpp
- Do not use O_NONBLOCK
- _UFFDIO_ZEROPAGE is actually not used
- Use a more aggresive strategy in blocking threads
- Small adjustment in thread synchronization which should fix some random hangs
=> Some small changes in uffd

framework/decode/dx12_resource_value_tracker.cpp
**Problem**
During the optimization, one operation may just erase one element from a vector and then put the same element back into the vector. For certain traces, the optimization takes hours to finish. 
**Solution**
Skip those unnecessary update operations. 
**Result**
For some traces, the optimization time is reduced, from hours to minutes.
=> Improve the optimizer performance

framework/decode/dx12_detection_consumer.h, framework/decode/vulkan_detection_consumer.h, tools/info/main.cpp
Run all common and API-specific stat gatherers in a single pass. Print API stats depending on what API(s) were detected.
=> Refactor code for gathering info from capture file

framework/decode/custom_dx12_struct_decoders.cpp, framework/decode/custom_dx12_struct_decoders.h, framework/generated/dx12_generators/dx12_struct_decoders_to_json_body_generator.py
=> Add missing properties to Decoded_D3D12_UNORDERED_ACCESS_VIEW_DESC

CONTRIBUTING.md, framework/generated/generated_dx12_struct_decoders_to_json.cpp
Update generated files and expand note on generation in CONTRIBUTING.md
=> update generated files and expand note on generation in CONTRIBUTING.md

BUILD.md
=> Add paragraph for MacOS/codesigning to build instructions

framework/decode/openxr_replay_consumer.cpp, framework/decode/openxr_replay_consumer.h
Correctly follows state machine and call ordering through first attempted present.
=> openxr: Add replay support through EndFrame

framework/util/page_guard_manager_uffd.cpp
It is possible that the signal send by the uffd logic to block the applications threads cannot be delivered. For this reason do pthread_cond_timedwait on the condition variable instead of pthread_cond_wait which causes a deadlock in these cases.
=> uffd: Do pthread_cond_timedwait instead

framework/encode/custom_vulkan_api_call_encoders.cpp, framework/format/format.h
=> Add pipeline creation attempt annotation

framework/decode/vulkan_replay_dump_resources_draw_calls.cpp
Fetching of indirect draw call params should be fetched at all times, not only when dumping of vertex buffers is requested
=> Vulkan dump resources: Fix indirect params fetching

vulkan_dump_resources.md
The same option is listed a few lines above
=> Remove duplicated line in dump resources doc

framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_consumer_base.h
- resolve vkDestroyFoo for tracked async-handles:  sync/block instead of deferred-delete
-> Avoids shuffling of certain vkDestroyFoo calls when using `--pcj X` option
=> Rework async-dependency-tracking to be deterministic

framework/decode/vulkan_replay_consumer_base.cpp
running an (inactive) capture from our NAS revealed a recent regression in vkDestroy*** calls.
related to work on:
https://github.com/LunarG/Projects/issues/749
goal is to re-add the capture referenced above to our internal CI asap, it's covering relevant edge-cases.
=> Fix regression: handle vkDestroy*** calls being passed null-handles

framework/decode/openxr_next_node.h, framework/decode/openxr_replay_consumer_base.cpp, framework/decode/openxr_replay_consumer_base.h, framework/decode/struct_pointer_decoder.h, framework/decode/vulkan_replay_consumer_base.h, framework/encode/api_capture_manager.h, framework/encode/capture_manager.h, framework/encode/custom_openxr_api_call_encoders.cpp, framework/encode/custom_openxr_encoder_commands.h, framework/encode/parameter_encoder.h, framework/encode/struct_pointer_encoder.h, framework/generated/base_generators/base_struct_decoders_header_generator.py, framework/generated/generated_openxr_api_call_encoders.cpp, framework/generated/generated_openxr_replay_consumer.cpp, framework/generated/generated_openxr_replay_consumer.h, framework/generated/generated_openxr_struct_decoders.h, framework/generated/generated_openxr_struct_encoders.cpp, framework/generated/generated_openxr_struct_encoders.h, framework/generated/openxr_generators/base_generator.py, framework/generated/openxr_generators/gencode.py, framework/generated/openxr_generators/openxr_api_call_encoders_body_generator.py, framework/generated/openxr_generators/openxr_consumer_header_generator.py, framework/generated/openxr_generators/openxr_replay_consumer_body_generator.py, framework/generated/openxr_generators/openxr_struct_encoders_body_generator.py, framework/generated/openxr_generators/openxr_struct_encoders_header_generator.py
openxr: Add virtual swapchain support 
openxr: Add support for XrType based allocation
openxr: Prevent reentrant capture in OpenXr calls
openxr: Add Session and Event replay overrides
openxr: Clean unused code add UpdateState template
openxr: Fix OpenXR replay common table usage
openxr: Add correct base struct pointer encode
=> Add functionality through a running frame loop on Windows/monado

framework/decode/openxr_replay_consumer_base.cpp
During replay, when xrPollEvent should be returning a valid value, instead of checking every 1 nanosecond for a new event, start at a nanosecond and double every time we check.  This should reduce the amount of xrPollEvent spam we see occur on replay.
=> openxr: Modify xrPollEvent check frequency

framework/encode/vulkan_state_writer.cpp
Check if AHardwareBuffer has cpu read mask usage, before locking it for cpu read. This fixes some of the AHardwareBuffer_lock issues and stutters.
The same check is already in vulkan_capture_manager.cpp with similar code.
=> Check if AHardwareBuffer is cpu readable in trim

framework/encode/custom_openxr_api_call_encoders.cpp, framework/generated/generated_openxr_api_call_encoders.cpp, framework/generated/openxr_generators/openxr_api_call_encoders_body_generator.py
also, move custom handle expansion into locked section
=> openxr: Relocate the prelock call to be prelock

framework/graphics/vulkan_resources_util.cpp
=> Check for unsupported formats when resolving image during WriteState

tools/tool_settings.h
Add the missing trace preload option
Change-Id: I9d6cf4e4cca28b9ce765c5dcfb6f13fe4c0ce72d
=> Restore trace preload option

framework/encode/capture_manager.cpp
page_guard_external_memory_  was usued uninitialized
=> Properly init page_guard_external_memory_

cmake/FindAGS.cmake
If the values are invalid, clear the cached value and try to find new values.
=> Validate cached CMake AGS variables

framework/encode/vulkan_capture_manager.cpp
All the other paths have this memory dump, but here it was missing.
=> Add missing AHB fill memory command

framework/encode/vulkan_state_tracker.cpp
Update asserts to support both uniform and storage buffers.
=> trimming: Fix descriptor update template buffers

android/tools/replay/src/main/AndroidManifest.xml
=> Fix replay restarting on orientation change

framework/graphics/fps_info.h
From question on #1891 
Mostly just waiting to see that this compiles correctly on all platforms
=> make one frame number instance consistent

USAGE_android.md, USAGE_desktop_Vulkan.md, android/scripts/gfxrecon.py, framework/decode/replay_options.h, framework/graphics/fps_info.cpp, framework/graphics/fps_info.h, tools/replay/android_main.cpp, tools/replay/desktop_main.cpp, tools/replay/replay_settings.h, tools/tool_settings.h
Provide `--quit-after-frame N` to exit replay after frame N.
=> Option to quit after specific frame when replaying

framework/decode/custom_vulkan_struct_to_json.cpp
This reverts commit dd4ba5c2fd1792c920cc99b857abeea6d62dab73.
=> Revert "Do not emit sampler for input attachment in json (#1959)"

framework/decode/vulkan_replay_dump_resources_common.cpp
Amend #1961
PR 1961 should have fixed the calculation of the image stride passed to the image writer instead of messing up with compressed images.
=> fix the calculation of the image stride passed to the image writer

framework/util/spirv_parsing_util.cpp
- also add some checks/asserts
=> Raise SPIRV-Reflect version to vulkan-sdk-1.4.304.0

framework/format/format.h
Reserving for upcoming optimizer-based vulkan raytracing support
=> Reserve MetaDataType 35

framework/decode/vulkan_virtual_swapchain.cpp
The commandbuffer of virtual swapchain may not be fully executed. Add waitForFence before destroying it.
=> Add waitForFence before destroying virtual swap chain resources

framework/decode/file_processor.h
This resolves an assertion in gfxrecon-optimize on DX12 content
=> make empty file stack equivalent to file completion

framework/decode/vulkan_replay_consumer_base.cpp
OverrideUpdateDescriptorSets was nesting the descriptor count foor loop twice by mistake, causing the function to take exceptionally long for descriptor updates that updated large arrays of descriptors.
=> VDR: For loop was mistakenly nested

framework/decode/vulkan_pnext_node.h, framework/decode/vulkan_replay_consumer_base.cpp, framework/generated/generated_vulkan_struct_handle_mappers.cpp, framework/generated/generated_vulkan_struct_handle_wrappers.h, framework/generated/khronos_generators/khronos_base_generator.py, framework/generated/khronos_generators/khronos_decode_extended_struct_generator.py, framework/generated/khronos_generators/khronos_dispatch_table_generator.py, framework/generated/khronos_generators/khronos_encode_extended_struct_generator.py, framework/generated/khronos_generators/khronos_enum_to_string_body_generator.py, framework/generated/khronos_generators/khronos_enum_to_string_header_generator.py, framework/generated/khronos_generators/khronos_json_consumer_body_generator.py, framework/generated/khronos_generators/khronos_replay_consumer_body_generator.py, framework/generated/khronos_generators/khronos_struct_decoders_body_generator.py, framework/generated/khronos_generators/khronos_struct_decoders_header_generator.py, framework/generated/khronos_generators/khronos_struct_handle_mappers_body_generator.py, framework/generated/khronos_generators/khronos_struct_handle_mappers_header_generator.py, framework/generated/khronos_generators/khronos_struct_handle_wrappers_body_generator.py, framework/generated/khronos_generators/khronos_struct_handle_wrappers_header_generator.py, framework/generated/khronos_generators/khronos_struct_to_json_body_generator.py, framework/generated/khronos_generators/khronos_struct_to_json_header_generator.py, framework/generated/khronos_generators/khronos_struct_type_util_generator.py, framework/generated/khronos_generators/vulkan_generators/vulkan_pnext_struct_encode_generator.py, framework/generated/khronos_generators/vulkan_generators/vulkan_replay_consumer_body_generator.py
JSON Child type support
Fix decode node and default values
Fix multi-api next en|decode
Clean up mappers and related types
type util fix for multi-api
Only a comment and whitespace change to code.
=> Final codegen cleanups for OpenXr support

framework/decode/vulkan_replay_consumer_base.cpp
We need to check the VkExternalMemoryHandleTypeFlags during both vkCreateImage and vkCreateBuffer calls and if they use FD, strip out the handle type from the corresponding
"VkExternalMemory..CreateInfo" struct.  If there are no other flags after that is stripped, just remove the external memory struct from the create info pNext chain.
Also, converted a few asserts to GFXRECON_ASSERT and added some additional logging info.
=> Fix external FD replay

README.md
This table indicates GFXR support on various platforms for various features.
This change incorporates feedback from other engineers as well.
=> Add table to indicate support for various features

framework/decode/openxr_replay_consumer_base.cpp, framework/decode/openxr_replay_consumer_base.h, framework/generated/generated_openxr_replay_consumer.cpp, framework/generated/generated_openxr_replay_consumer.h, framework/generated/generated_openxr_struct_encoders.cpp, framework/generated/khronos_generators/khronos_struct_encoders_body_generator.py, framework/generated/khronos_generators/openxr_generators/gencode.py, framework/generated/khronos_generators/openxr_generators/openxr_replay_consumer_body_generator.py
Additional openxr capabilities to support Openxr Tutorial 4
=>  openxr tutorial4 support

framework/encode/custom_openxr_api_call_encoders.cpp
Currently, it is not supported to capture OpenXR without capturing Vulkan (known issue).  Added a test/fatal message/assert to provide information to users.
=> openxr:  Add FATAL error message for capture misconfiguration (i.e. Vulkan capture not enabled)

framework/decode/vulkan_address_replacer.cpp, framework/decode/vulkan_replay_dump_resources_common.cpp, framework/encode/vulkan_capture_manager.cpp, framework/encode/vulkan_state_writer.cpp, framework/encode/vulkan_state_writer.h, framework/graphics/vulkan_resources_util.cpp, framework/graphics/vulkan_resources_util.h, framework/util/compressor.h, framework/util/lz4_compressor.cpp, framework/util/lz4_compressor.h, framework/util/zlib_compressor.cpp, framework/util/zlib_compressor.h, framework/util/zstd_compressor.cpp, framework/util/zstd_compressor.h
this PR contains the changes from https://github.com/LunarG/gfxreconstruct/pull/2089
along with additional corrections. the branch has been tested against additional cases.
=> Batch queue-submissions in ProcessBufferMemory / ProcessImageMemory (2nd)

USAGE_desktop_Vulkan.md
=> Update list of supported WSI in Vulkan usage doc

android/test/test_apps/common/CMakeLists.txt, android/test/test_apps/launcher/CMakeLists.txt, test/CMakeLists.txt, test/test_apps/ahb/CMakeLists.txt, test/test_apps/ahb/ahb_app.h, test/test_apps/ahb/app.cpp, test/test_apps/launcher/test_launcher.cpp, test/test_cases/ahb.cpp
Requires https://github.com/LunarG/gfxreconstruct/pull/2093
=> AHB test app

framework/decode/dx12_replay_consumer_base.h
Fix a crash that can occur with D3D12 replay when resource creation succeeds at replay but failed at capture. For this case, the created resource will not have a valid capture ID, so will be released instead of being added to the object table. This leads to a null dereference in SetResourceDesc() when attempting to initialize a resource record returned by GetObjectInfo(). This change adds a check to skip the initialization when GetObjectInfo() returns null.
=> Fix D3D12 resource init crash

framework/decode/vulkan_replay_consumer_base.cpp
Creating a list of Vulkan api calls which should be allowed to return a different error code during replay
=> Allowlist for different return code from capture

framework/decode/openxr_replay_consumer_base.cpp
Reference space changed events are not critical, and sometimes do not re-occur during the replay.  So add them to the list of events we're allowed to skip.
Also fix a bug caught by Brad where we were spitting out the incorrect event information when storing it to the pending event array.
=> [openxr] Ignore refer space change events

framework/decode/vulkan_object_info.h, framework/decode/vulkan_replay_consumer_base.cpp, framework/decode/vulkan_replay_dump_resources.cpp, framework/decode/vulkan_replay_dump_resources_draw_calls.cpp, framework/decode/vulkan_replay_dump_resources_draw_calls.h
- Handle vkCreateRenderPass2
- Handle pNext structs in both vkCreateRenderPass functions
=> VDR: Handle vkCreateRenderPass2

framework/encode/CMakeLists.txt, framework/encode/capture_manager.cpp, framework/encode/capture_manager.h, framework/encode/capture_settings.cpp, framework/encode/capture_settings.h
1. When there are multiple Apps are opened and they are all rendered by vulkan, the user can specify the App name to be captured.
=> Trace the specified App

CMakeLists.txt
This is an alternative to PR #2230.
=> [openxr] Force static linkage on all platforms to openxr loader
